### ISSUE TITLE
Question: Where does the QnA action take the input from?

### ISSUE THREAD

**Issue by eluchsinger** [microsoft/botbuilder-dotnet#4396] opened 2020-08-04 08:24 UTC
When I add a QnA action, the tutorial shows that by adding an unknown intent trigger. That works fine, but I would like to have an explicit QnA call in my bot, read: I would like to ask my QnA service using a variable as input.

What kind of  input does the QnA action use? There seems to be nothing I can use as an input in the QnA action itself, so I believe it uses a predefined input variable.

By the way, this would be an excellent addition to the Bot Framework Composer Docs.

**Comment by eluchsinger** [comment] 2020-08-06 07:23
I would like to add it's not just the `dialog`'s memory. The whole response is somehow duplicated aswell. The last response in the screenshot should start with a **2**.

**Comment by DishaAgarwal** [comment] 2020-08-06 14:49
@vishwacsena When QnA Maker can't find an answer it just returns a "No QnAMaker answers found" response. It doesn't influence the dialog state in anyway. It is possible that there is a bug in how the response is handled thereafter at the composer end?

In the scenario when QnA maker does return a multi-prompt answer and user does select one of the prompts, I believe the fallback intent is triggered again and that's why the dialog loop executes again.

**Comment by vishwacsena** [comment] 2020-08-07 20:29
@DishaAgarwal can you get someone to debug this? I suspect something in qnamaker dialog is causing the parent adaptive dialog's `dialog` scope to get overwritten. Also the issue is not with fallback intent triggering or multi-turn etc. In a simple flow, after qnamaker action completes, the dialog state as it was prior to qnamaker action should be available.

**Comment by eluchsinger** [comment] 2020-08-10 13:42
I've built a custom service to query QnA via REST, because the QnA Action right now is not good enough to use it in our customer projects. Would be happy to hear any news about the debugging and or further advancements with the QnA action.

**Comment by DishaAgarwal** [comment] 2020-08-11 07:13
@vishwacsena We will look into it and get back to you.

**Comment by lauren-mills** [comment] 2020-08-25 18:15
@DishaAgarwal - Any update here?

**Comment by DishaAgarwal** [comment] 2020-08-31 07:36
@lauren-mills I apologize for the delay. We tried replicating the issue on new BF SDK and we found that the same issue doesn't occur with the new BF SDK (4.10.*).  The relevant screenshots are included below:

![image](https://user-images.githubusercontent.com/11506427/91693794-31657100-eb89-11ea-82cc-6d7bc5b0d809.png)
![image](https://user-images.githubusercontent.com/11506427/91693809-36c2bb80-eb89-11ea-8fa2-c4ca832d68b7.png)

However, the issue is existent on BF SDK (4.9.*) which is used by composer by default. This would probably be fixed in the next composer release.

Meanwhile, this issue can be mitigated by the user on updating the runtime of bot to latest version.

- Follow steps provided in "Eject Runtime" Documentation.
- Download runtime from https://github.com/microsoft/BotFramework-Composer/tree/main.
- Replace runtime folder of the bot with download runtime.

These steps should update the runtime of bot to refer to BF SDK (4.10.*).

**Comment by GeoffCoxMSFT** [comment] 2020-09-10 18:25
With Composer 1.1.1 released this issue should be fixed.  Please re-open if you encounter the problem again.

**Closed by GeoffCoxMSFT** 2020-09-10 18:25 UTC
Labels: Area: Adaptive, Bot Services, customer-replied-to, customer-reported

**Comment by Prerana-acce** [comment] 2021-03-10 14:11
Hi All, 
I need to fetch the source URL and other details from QnA action in Bot Composer. Is it technically feasible or any workaround for ? Any help or pointers will be highly appreciated.

**Comment by avkumar8** [comment] 2021-10-04 06:35
Is there any solution found for this yet? I am also facing the same issue. Need to explicitly call the QnA and pass the question which is stored in a variable
