### ISSUE TITLE
Confirm prompt  throws error when replied with value 'n'

### ISSUE THREAD

**Issue by utkarsh24** [Microsoft/botbuilder-dotnet#1259] opened 2018-12-24 14:40 UTC
Microsoft.Bot.Builder.Dialog 4.1.5

In version 4.1.5 Confirm Prompt also gives suggestion by default for yes and no.

But when i don't select from the choices and enter value  n  

the bot framework throws exceptions

exception
 Type : `KeyNotFoundException`
Message : 

`> The given key '' was not present in the dictionary.`

StackTraceString": " 

`>   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.Bot.Builder.Dialogs.ConfirmPrompt.OnRecognizeAsync(ITurnContext turnContext, IDictionary`2 state, PromptOptions options, CancellationToken cancellationToken) in D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\Prompts\\ConfirmPrompt.cs:line 150\r\n   at Microsoft.Bot.Builder.Dialogs.Prompt`1.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken) in D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\Prompts\\Prompt.cs:line 82\r\n   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\DialogContext.cs:line 130\r\n   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken) in D:\\a\\1\\s\\libraries\\Microsoft.Bot.Builder.Dialogs\\ComponentDialog.cs:line 65\r\n   at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken) in ---`

**Comment by Zerryth** [comment] 2018-12-24 19:17
@utkarsh24 we'd need to see some actual code to bury down into the issue further, however your issue may be a duplicate of https://github.com/Microsoft/BotBuilder/issues/5060#issuecomment-424873265

Check out the link, as there's a solution posted as well

**Comment by utkarsh24** [comment] 2018-12-26 08:48
Hi @Zerryth, thanks for the quick response,

for the code reference i have downloaded the bot builder samples and tried with "05.multi-turn-prompt" sample :
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/05.multi-turn-prompt

please find screenshot ...

![image](https://user-images.githubusercontent.com/30922653/50439732-1739b100-0919-11e9-8136-5398c455469f.png)

**Comment by utkarsh24** [comment] 2018-12-26 09:58
Not only for 'n' but for every other matching values of ConfirmPrompt, it throws error...

**Comment by drub0y** [comment] 2018-12-26 17:49
Fwiw I've also run into this issue, but when I went to create a simple repro last week in isolation from a more complex project I couldn't trigger it.

My attempt at a repro was basically a one step waterfall with the confirm prompt on first step. Worked fine tho. 😕 It must be related to a more complicated scenario that I'll continue to try to repro when back from holiday.

**Comment by Zerryth** [comment] 2018-12-31 21:56
@utkarsh24 thank you, I was able to repro the error. Investigating further

**Comment by Zerryth** [comment] 2018-12-31 23:12
@utkarsh24 it looks like in C# `05.multi-turn-prompt` sample, the `.csproj` file specifies to use version `4.1.5`. Cloning the repo and restoring/running just with how the samples are as is yielded in the error where you couldn't us a confirmation that wasn't one of the `yes` or `no` choices given.

However updating to the most current stable SDK version, `4.2.0`, looks like the confirm prompt no longer breaks and can handle input that is different from the choices given. See images below.

4.1.5
![image](https://user-images.githubusercontent.com/35248895/50568876-9f4efa80-0d0d-11e9-9e9d-1312bfe154e8.png)

4.2.0
![image](https://user-images.githubusercontent.com/35248895/50568878-b7267e80-0d0d-11e9-814b-f3b11dd816f3.png)

So update to `4.2.0` and you should be good as well. 

Making note that the team needs to comb through the Samples repo and make sure they are all targeting the most current version of the SDK as well

**Closed by Zerryth** 2018-12-31 23:12 UTC
