### ISSUE TITLE
Enable warnings as errors for analysis tools

### ISSUE THREAD

**Issue by axelsrz** [microsoft/botbuilder-dotnet#4036] opened 2020-06-10 00:52 UTC
This issue is related to #2367 and should be done after configuring hierarchical rules for the repo and adhered current code to the standard.

**Comment by mrivera-ms** [comment] 2020-06-27 04:49
@axelsrz , this seems to be a duplicate of #4061. Unless this item is meant for a specific project not addressed there. Please advise.

**Closed** 2020-06-29 20:07 UTC
Labels: BF Code Quality, P1, R10
