### ISSUE TITLE
Datetimes are improperly caste to another type when stored in properties in Adaptive dialogs

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-dotnet#4522] opened 2020-08-26 17:06 UTC
## Version
4.9

## Describe the bug

When storing a datetime in a property, it is somehow caste into a different type, making it incompatible with datetime expressions or comparisons.

For example, setting a property to =utcNow() and then immediately echoing that value results in *different values*

![Screen Shot 2020-08-26 at 11 55 34 AM](https://user-images.githubusercontent.com/729873/91333401-2b3f5100-e793-11ea-87a6-c3f795986e4e.png)
![Screen Shot 2020-08-26 at 11 55 39 AM](https://user-images.githubusercontent.com/729873/91333405-2c707e00-e793-11ea-84af-43d6637d4f9c.png)

Similarly, using getPastTime to generate a date in the past results in a value that *fails the conditional test* to check if it is actually in the past.

![Screen Shot 2020-08-26 at 12 00 42 PM](https://user-images.githubusercontent.com/729873/91333874-c9cbb200-e793-11ea-849d-4ccecb412929.png)
![Screen Shot 2020-08-26 at 12 00 53 PM](https://user-images.githubusercontent.com/729873/91333884-ce906600-e793-11ea-87a4-f1d22a14f1bd.png)

In addition, once stored in a property, these date time values can no longer be used with datetime formatting tools such as month:

${ month(utcNow() } works
${ month(dialog.date) } fails with an error

![Screen Shot 2020-08-26 at 12 05 06 PM](https://user-images.githubusercontent.com/729873/91334328-68f0a980-e794-11ea-8d92-a0b3ff9182f1.png)
![Screen Shot 2020-08-26 at 12 05 09 PM](https://user-images.githubusercontent.com/729873/91334332-6a21d680-e794-11ea-9d06-d4ab19f0eb4a.png)

## To Reproduce

1. Set a property called dialog.date to =utcNow()
2. Set a property called dialog.pastDate to =getPastTime(1,"year")
3. Send an activity with the text Compare ${ dialog.date } > ${ dialog.pastDate } = ${ dialog.date > dialog.pastDate }

This will result in the comparison evaluating to FALSE, which is incorrect.

## Expected behavior

Datetime values stored in properties should continue to be datetimes.

Here is a Composer project that exhbits all of these problems
[dateBugs.zip](https://github.com/microsoft/botbuilder-dotnet/files/5131286/dateBugs.zip)

**Comment by vishwacsena** [comment] 2020-08-26 17:08
@boydc2014 can you have someone look into this?

**Comment by xieofxie** [comment] 2020-08-27 00:40
Related https://github.com/microsoft/botbuilder-dotnet/issues/4223

**Comment by boydc2014** [comment] 2020-08-27 06:04
@cosmicshuai this is related to the settings for JSON serialization of DialogStateManager, right?

**Comment by boydc2014** [comment] 2020-08-27 06:09
@vishwacsena it's the same issue with #4223 as @xieofxie  said. 

The root cause is DSM used json converter to convert the value before set to the memory, then the default behavior of json converter will detect the datetime format and try to convert to a datetime object. 

My recommendation is disable this feature\bug.

**Comment by boydc2014** [comment] 2020-09-30 04:23
@benbrown hi, after triaged in SDK team, we think this is the C#'s convention and disabling this datetime convention will be a huge break change. So we will keep the current behavior that a ISO string, once set to memory, will be converted a DateTime object.  And in R10, we are making all pre-built functions support DateTime as input, such as "addMonth", "addDay", etc.

In the case that, if user surely want ISO string, formatDate(dialog.date) will get what you need. Will this looks good to you? Closing it for now.

**Closed by boydc2014** 2020-09-30 04:23 UTC
Labels: Area: Adaptive expression, P1, bug

**Comment by cosmicshuai** [comment] 2020-09-30 08:27
I added a new issue to track DateTime comparison.
