### ISSUE TITLE
OAuth prompt not working for Teams

### ISSUE THREAD

**Issue by fkuehnSAG** [microsoft/botbuilder-dotnet#5950] opened 2021-11-05 12:21 UTC
## Version
4.14.1

I tested this with the sample code of the BotBuilder-Samples repository (https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/46.teams-auth).

After i wrote something in the teams client and received the OAuth Prompt from the bot i tried clicking on "sign in". When doing that with the teams client the api is returning 501 Not Implemented and nothing happens. When doing that with the bot emulator or the azure web chat it is working though. 

After having a look into this i recognized, that the emulator and the teams client are handling the OAuth promt answer in a different way: the bot emulator is using a turnContext with the "event" activity type and the activity name "tokens/response" while the teams client is using the activity type "invoke" with the activity name "signin/verifyState".
So when having a look at OnSignInInvokeAsync in the ActivityHandler you can see that this invoke action is indeed not implemented.

I also tried to override the OnInvokeActivityAsync to simulate a similar behavior as for the emulator but this was also not working for me.

I know that this was working a few months ago so did maybe teams change its behavior here? I would be grateful if anyone could help me out with this issue :)

## Steps to reproduce
Follow the instructions of this documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample#install-and-test-the-bot-in-teams

**Edit:** i just tested this with the nodejs implementation and it is working there. When checking the teamsBot.js they just continue with the dialog at this point see: https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/javascript_nodejs/46.teams-auth/bots/teamsBot.js

I tried changing to the TeamsActivityHandler, overwriting the OnTeamsSigninVerifyStateAsync method and calling Dialog.RunAsync there and it worked for me. But its still not good that its not working at all without overwriting the method + the official examples in the BotBuilder-Samples project are wrong if i am right.

**Comment by stevkan** [comment] 2021-11-05 23:40
@fkuehnSAG, just to clarify, you were able to get it working for you? The issue is now between the SDK and the sample and the correct implementation so it is working out-of-the-box, correct?

**Comment by fkuehnSAG** [comment] 2021-11-08 07:19
@stevkan yes, i got it working for me. The issue is just, that the OAuth Prompt is not working by default for teams now. I think it would make sense to create a base implementation in the ActivityHandler or TeamsActivityHanlder for this event, or if there is a reason to not do that at least update the dotnet bot samples so people know how to handle it in the future.

Thank you for your fast reply :)

**Comment by stevkan** [comment] 2021-11-10 21:12
Thank you for your suggestion. It will be considered.

Closing as resolved.

**Closed by stevkan** 2021-11-10 21:12 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to
