### ISSUE TITLE
Bot packages incompatibility with Azure Key Vault

### ISSUE THREAD

**Issue by nimbusparis** [microsoft/botbuilder-dotnet#3197] opened 2019-12-26 20:24 UTC
## Version
4.7.0

## Describe the bug
When adding `Microsoft.Bot.Builder` package to a working ASP.NET Core 3.1 app using Azure Key Vault make the app crash since `Microsoft.IdentityModel.Clients.ActiveDirectory.Platform` package cannot be found. This package doesn't exist anymore, something in the required packages of `Microsoft.Bot.Builder` should be wrong.

## To Reproduce
* clone the project on https://github.com/nimbusparis/TestAKVWithBot
* Remove the package `Microsoft.Bot.Builder` from the project
* Deploy under Linux
* Deploy a Azure Certificate on the server
* Run the app, it should work.

* Restore the package `Microsoft.Bot.Builder` in the project
* Run the app
* It crash with the following stack:
`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationOptions.GetTokenFromClientCertificate(String authority, String resource, String clientId, X509Certificate2 certificate)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationOptions.GetTokenFromClientCertificate(String authority, String resource, String clientId, X509Certificate2 certificate)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationOptions.<>c__DisplayClass1_0.<.ctor>b__0(String authority, String resource, String scope)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.PostAuthenticate(HttpResponseMessage response)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at TestAKVWithBot.Program.Main(String[] args) in /opt/TestAKVWithBot/TestAKVWithBot/Program.cs:line 17
`

## Expected behavior
Bot Builder should work with Azure Key Vault, not asking an obsolete library.

## Additional context
This occurs on Linux when using Certificates to access to AKV.

[bug]

**Comment by christopheranderson** [comment] 2019-12-27 19:49
This looks like it is crashing in Azure Key Vault's code because it has the lower version requirement from `Microsoft.Bot.Builder`.

It looks like they both depend on `Microsoft.IdentityModel.Clients.ActiveDirectory` via a dependency:

`Microsoft.Bot.Builder` 4.7.0
-> `Microsoft.Bot.Connector` 4.7.0
     -> `Microsoft.IdentityModel.Clients.ActiveDirectory` (>= 5.2.4)

`Microsoft.Extensions.Configuration.AzureKeyVault` 3.1.0
-> `Microsoft.Azure.Services.AppAuthentication` 1.3.1
     -> `Microsoft.IdentityModel.Clients.ActiveDirectory` (>= 4.3.0)

I checked and we added the ActiveDirectory (5.x) in 4.2.x of Connector. Previously we didn't have a dependency on it.

In this case, I'd actually recommend that we open the bug up on the KeyVault library. They are a major version behind of AAD support which will make them not work with ANY new library, not just bot framework. Thoughts @sgellock, @tomlm, @johnataylor, @cleemullins ?

**Comment by christopheranderson** [comment] 2019-12-27 20:01
I also tried this on `dotnet`@3.0.100 and couldn't repro. I did have to modify the code, though, because I don't have certs installed in this machine that matches the config, so I just used the non-cert based KeyVault config and used BS strings. In that case, my setup fails with a 400 error, which I'd expect.

<details>
<summary>Expected 400 error message</summary>

```
Number of certificates 6
Unhandled exception. Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS700016: Application with identifier 'bar' was not found in the directory '72f988bf-86f1-41af-91ab-2d7cd011db47'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 116cca0f-0018-4eb8-a2f8-bc6468ee3d00
Correlation ID: 859cbafa-903e-4bc6-9f46-d8886365004a
Timestamp: 2019-12-27 19:55:54Z
 ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: Response status code does not indicate success: 400 (BadRequest).
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
        ErrorCode: BadRequest
        StatusCode: 400
   --- End of inner exception stack trace ---
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T](Boolean respondToDeviceAuthChallenge)
   at Microsoft.Identity.Core.OAuth2.OAuthClient.GetResponseAsync[T]()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendHttpMessageAsync(IRequestParameters requestParameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.SendTokenRequestAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.CheckAndAcquireTokenUsingBrokerAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenForClientCommonAsync(String resource, ClientKey clientKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, ClientCredential clientCredential)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationOptions.GetTokenFromClientSecret(String authority, String resource, String clientId, String clientSecret)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.PostAuthenticate(HttpResponseMessage response)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at TestAKVWithBot.Program.Main(String[] args) in C:\w\scratch\TestAKVWithBot\TestAKVWithBot\Program.cs:line 17
        ErrorCode: unauthorized_client
        StatusCode: 400
```

</details>

<details>
<summary> Modified Program.cs </summary>

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace TestAKVWithBot
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, config) =>
                {
                    var builtConfig = config.Build();
                        
                    using var store = new X509Store(StoreName.My);
                    store.Open(OpenFlags.ReadOnly);
                    Console.WriteLine($"Number of certificates {store.Certificates.Count}");
                    var certs = store.Certificates
                        .Find(X509FindType.FindByThumbprint,
                            builtConfig["AzureADCertThumbprint"], false);

                    config.AddAzureKeyVault(
                        $"https://foobar.vault.azure.net/",
                        "bar",
                        "baz");

                    store.Close();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                
        ;
    }
}
```
</details>

**Comment by EricDahlvang** [comment] 2019-12-31 21:41
As @christopheranderson mentioned, this is an issue with [Microsoft.Extensions.Configuration.AzureKeyVault](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureKeyVault) depending on [Microsoft.Azure.Services.AppAuthentication/1.0.3](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.0.3) which depends on [Microsoft.IdentityModel.Clients.ActiveDirectory/3.14.2](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/3.14.2)

Microsoft.IdentityModel.Clients.ActiveDirectory.Platform was removed from Microsoft.IdentityModel.Clients.ActiveDirectory >= 4.3.0
![image](https://user-images.githubusercontent.com/11055362/71634286-910d1600-2bcf-11ea-9d0b-d06d9f443ea0.png)

This means Microsoft.Extensions.Configuration.AzureKeyVault cannot be used with Bot Builder until these other libraries are updated.  

Further reading on this:
[Azure Key Vault Configuration 3.0 updates
](https://github.com/aspnet/AspNetCore.Docs/issues/12346)

Waiting on:
[[FEATURE REQ] Release Microsoft.Azure.Services.AppAuthentication major version supporting Microsoft.IdentityModel.Clients.ActiveDirectory 5.x](https://github.com/Azure/azure-sdk-for-net/issues/7457)

Related preview Package (could use this, and code from https://github.com/aspnet/Configuration/tree/master/src/Config.AzureKeyVault to create a workaround):
[Azure.Security.KeyVault.Certificates](https://www.nuget.org/packages/Azure.Security.KeyVault.Certificates)

**Comment by nimbusparis** [comment] 2020-02-02 10:08
How can a blocked issue can be closed before it had been un-blocked?

**Comment by sgellock** [comment] 2020-02-02 18:06
@nimbusparis, we have some automation that flags issues that have no new activity over a 30 day period.  This is the most recent comment from the automation bot "gitHub-actions". As Eric documents, there is a dependency chain here with a root assembly provided by the AAD team.  We'll push on this team to see where they are at with this work on their specific roadmap.  But to be upfront, this is not an issue we can fix for you until we get a fix from another team.

**Comment by nimbusparis** [comment] 2020-02-02 18:46
Yes, I understood that this issue is blocked by another team, but this issue should not be closed until the issue on Azure Key Vault is fixed. each blocked team/project should add pression to AAD team to fix this issue, that had been discovered in september...

**Comment by EricDahlvang** [comment] 2020-02-02 19:06
Thanks @nimbusparis 

We should be able to keep this open until the packages are updated.  

Jan 28th we were informed here https://github.com/Azure/azure-sdk-for-net/issues/7457#issuecomment-579539881 the `Microsoft.IdentityModel.Clients.ActiveDirectory` dependency in `Microsoft.Azure.Services.AppAuthentication` should be updated "within the next couple of weeks"  After this rolls out, `Microsoft.Extensions.Configuration.AzureKeyVault` will need to be updated to use it, then we can update `Microsoft.Bot.Builder` . <whew>

**Comment by EricDahlvang** [comment] 2020-02-07 23:30
https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.4.0 has just been released.


Now, waiting on an update of `Microsoft.Extensions.Configuration.AzureKeyVault`: [github issue](https://github.com/dotnet/extensions/issues/1728)

**Comment by cleemullins** [comment] 2020-02-10 22:37
@EricDahlvang - any update here in the last few days?

**Comment by EricDahlvang** [comment] 2020-02-11 00:38
@cleemullins still waiting to hear on [KeyVault 2.2 nuget: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform'](https://github.com/dotnet/extensions/issues/1728)

There was a new release of `Microsoft.Extensions.Configuration.AzureKeyVault` last month, but it is still dependent on `Microsoft.Azure.Services.AppAuthentication` (>= 1.0.3)
![image](https://user-images.githubusercontent.com/11055362/74203002-00d8dc80-4c23-11ea-844c-3508a46b2f13.png)


If I find some time, i could make a PR to fix...

**Comment by heaths** [comment] 2020-02-19 03:36
The older Microsoft.Azure.* and related packages like this one are no longer under active development and we recommend customer upgrade to the newer Azure.* packages that are faster with less memory overhead, and easier to use - all supported languages (a growing list of languages) were designed to be easy, consistent, but idiomatic.

Specific to this issue, MSAL has caused lots of problems with broken dependencies. The newer libraries don't rely on it by design to avoid those problems.

Pretty soon we'll be releasing a comparable package named something like Azure.Extensions.Configuration.Secrets (final name pending). Is it possible to wait a few weeks for this release?

**Comment by cleemullins** [comment] 2020-02-19 21:48
@heaths Thanks! We'll hold off until Azure.Extensions.configuration.secrets (or whatever the final name is) is out. For now I've punted this bug to R9 (which will ship for us in May), as it sounds like that will align with your release cycle.

**Comment by EricDahlvang** [comment] 2020-02-20 01:25
We do not actually have a dependency in our libraries waiting on a fix.  There is some confusion in that users tend to think the issue is with the Bot Builder packages.  But, we are already using Microsoft.IdentityModel.Clients.ActiveDirectory (>= 5.2.4)

This issue (#3197) is only open for tracking, while waiting for an official KeyVault extension ( Azure.Extensions.Configuration.Secrets?) which does not have a dependency on the older Microsoft.IdentityModel.Clients.ActiveDirectory.

@heaths  Please do let us know when there is a replacement for Microsoft.Extensions.Configuration.AzureKeyVault

**Comment by heaths** [comment] 2020-02-20 19:09
@pakrym can confirm, but a preview of the packages should be shipping very soon with a GA planned in March.

**Comment by EricDahlvang** [comment] 2020-03-24 23:55
Hi @heaths or @pakrym 

It looks like a new version of Microsoft.Extensions.Configuration.AzureKeyVault was released today.  However, it is still using Microsoft.Azure.Services.AppAuthentication v1.0.3

Is there a different package to use for certificates on Azure Key Vault which do not have a dependency tree reliant on the older version of ADAL ?

![image](https://user-images.githubusercontent.com/11055362/77487495-d36d7a00-6def-11ea-8282-97a8e5f63eed.png)

**Comment by pakrym** [comment] 2020-03-25 18:33
There is a preview of replacement: https://www.nuget.org/packages/Azure.Extensions.Configuration.Secrets/1.0.0-preview.1

But we are not GAing it this month.

**Comment by EricDahlvang** [comment] 2020-03-30 15:02
Closing this, since a new library has been provided.  Thanks @pakrym

**Closed by EricDahlvang** 2020-03-30 15:02 UTC
Labels: Bot Services, P1, R9, blocked, customer-replied-to, customer-reported
