### ISSUE TITLE
 Danish Language Support in Confirm Prompt Bot v4 (C#/.Net Core)

### ISSUE THREAD

**Issue by mutanttech** [microsoft/botbuilder-dotnet#2466] opened 2019-09-02 11:40 UTC
Danish Language is not supported by the Confirm Prompt Class and no way provided to extend it.

## Version
v4.5.0

## Describe the bug
Danish Language is not supported by the Confirm Prompt Class and no way provided to extend it.
Essentially, this code is required -
```{ Danish, (new Choice("Ja"), new Choice("Nej"), new ChoiceFactoryOptions(", ", " of ", ", of ", true)) },```

Take a look at code here -
[https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs
)

## To Reproduce
1. Add a Confirm Prompt in V4 Bot
2. Try to set Default Locale to Danish

## Expected behavior
Danish Locale should be added. And it should be made configurable/injectable for different languages to make it decoupled.

## Additional context
Please take action on this as soon as possible.

**Comment by mdrichardson** [comment] 2019-09-02 15:52
@mutanttech I'll roll this into [this PR](https://github.com/microsoft/botbuilder-dotnet/pull/2463). Thank you for providing the appropriate translations

**Comment by mdrichardson** [comment] 2019-09-02 16:10
@mutanttech 	Actually, I may not be able to roll that in due to the below.

@cleemullins / @sgellock :

[This JS PR](https://github.com/microsoft/botbuilder-js/pull/1121) that just got merged added `Recognizers-Text.Culture` to Choice and Confirm Prompt so that it would be more in line with the Dotnet Repo. I've used [this Dotnet PR](https://github.com/microsoft/botbuilder-dotnet/pull/2463) to better integrate it with `Recognziers-Text.Culture` as well. The main point of those two PRs is to normalize locale interpretation so that passed in locales like "fr-fr", "fr-FR", "FR" all get mapped appropriately to "fr-fr".

The issue with adding Danish, as @mutanttech requested is that [`Recognizers-Text.Culture` doesn't support Danish](https://github.com/microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text/Culture.cs#L6). I could see a few different ways of handling this issue/DCR:

1. Don't support non-Recognizers-Text languages
2. Handle non-Recongizers-Text languages differently
3. Remove integration with Recognizers-Text and handle the normalization ourselves

@cleemullins / @sgellock  **Do you have a preferred way you'd like the SDK to handle this?** I can implement any of those 3 (I'd probably recommend #3), just want to make sure I move things in the right direction.

**Comment by mutanttech** [comment] 2019-09-03 04:26
@mdrichardson ,
Thanks for addressing the issue. And my suggestion would be to not limit Locale Support by integrating it with something which does not offers variety support. There is lots of Danish MS Bot customers, who would want to see first class treatment with the Language. 
And just one question to ask if you might share details, when is the adaptive card based prompts coming in the SDK. I am looking forward to use them. Please make this change available sooner if possibly, I dont want to make changes to SDK source code even for short term basis.

Please comment. Thanks

**Comment by mdrichardson** [comment] 2019-09-03 14:55
@mutanttech I also believe it would be preferable to de-couple from other packages, specifically in this case.

Unfortunately, I'm a support engineer and this is a design decision a bit out of my approval level.

I'll reach out and see if we can get some traction on this.

**Comment by cleemullins** [comment] 2019-09-17 18:35
To points here:

Point 1: 
Given that our [recognizers library] (https://github.com/Microsoft/Recognizers-Text) doesn't support Danish, I don't think this is a change we can take. To do this, we would have to start with the recognizers, then move up the stack. 

Point 2: We *should* allow you to extend this. I would support something like:
public static void AddDefaultChoiceItem( ... )
{
}

That would be run at startup, or some similar time, and would modify the static dictionary. 

Would that work? 

A more flexible option may be to have:
public static void SetDefaultChoices(Dictionary<>) which replaces the entire dictionary.

**Comment by mdrichardson** [comment] 2019-09-18 18:33
@mutanttech I'm going to close this issue as it's been confirmed that we're not going to specifically support Danish unless/until Recognizers-Text does so.

Once approved, merged, and released, you'll be able to add your own Locale Dictionaries to Choice and Confirm Prompt through something like:

```csharp
ConfirmPrompt.CustomLocaleOptions = new Dictionary<string, (Choice, Choice, ChoiceFactoryOptions)>()
{
    {
        "da-DK",
        (new Choice("Ja"),
        new Choice("Nej"),
        new ChoiceFactoryOptions
        {
            IncludeNumbers = true,
            InlineOr = " eller ",
            InlineOrMore = ", eller ",
            InlineSeparator = ", ",
        })
    },
};
```

**Closed** 2019-09-18 18:33 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by mdrichardson** [comment] 2019-09-20 19:58
Note: The code in the above comment was based on a draft I was working on. It's going to change a bit, but will still be that easy.

**Comment by mutanttech** [comment] 2020-06-23 07:23
@mdrichardson, Just wanted to check if story has changed for Danish Support. I found that Health Bot supports it -
https://docs.microsoft.com/en-us/healthbot/supported_locales
Any comments?

**Comment by mdrichardson** [comment] 2020-06-23 23:15
@mutanttech No official support at this time. [I added a few additional languages back in December](https://github.com/microsoft/botbuilder-dotnet/pull/3129), but officially, we follow the [Recognizers-Text library](https://github.com/microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text/Culture.cs).

I'm not sure if you saw the workaround PR, though, where you can [pass in your own `choiceDefaults`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ConfirmPrompt.cs#L72) after building your own [`PromptCultureModel`](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/PromptCultureModel.cs). [Here's how I do it in our tests](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Dialogs.Tests/ConfirmPromptLocTests.cs#L171)

**Comment by mutanttech** [comment] 2020-07-02 09:40
@mdrichardson, Thanks for update. I will take reference from from the PR.
