### ISSUE TITLE
Custom Action Events arrive in wrong order

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#4817] opened 2020-10-19 05:30 UTC
When emitting events from a custom action, they arrive in the wrong order;

![image](https://user-images.githubusercontent.com/49873947/96405118-d6d9b000-11dc-11eb-9530-64d9ef2cb226.png)
![image](https://user-images.githubusercontent.com/49873947/96405136-e0631800-11dc-11eb-86b2-db46401d753c.png)
![image](https://user-images.githubusercontent.com/49873947/96405151-ea851680-11dc-11eb-9dda-e627cfa76a18.png)

```
namespace Microsoft.BotFramework.Composer.CustomAction
{
    public class EventEmitter : Dialog
    {
        [JsonConstructor]
        public EventEmitter([CallerFilePath] string sourceFilePath = "", [CallerLineNumber] int sourceLineNumber = 0)
            : base()
        {
            this.RegisterSourceLocation(sourceFilePath, sourceLineNumber);
        }

        [JsonProperty("$kind")]
        public const string Kind = "EventEmitter";

        public async override Task<DialogTurnResult> BeginDialogAsync(DialogContext dialogContext, object options = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            await dialogContext.EmitEventAsync("Event1", null);
            await dialogContext.EmitEventAsync("Event2", null);

            return await dialogContext.EndDialogAsync();
        }
    }
}
```

**Comment by stevengum** [comment] 2020-10-19 18:13
@mrivera-ms can you assign someone with dialogs-experience to investigate this issue and get a repro? Thanks!

**Comment by boydc2014** [comment] 2020-10-20 08:18
At a first glance, looks like not related to the order of event itself, this looks like to be the trigger firing order isn't as ordered as you might see, and that's by design. 

@stevengum @mrivera-ms free feel to assign to me or @Danieladu.

**Comment by chrimc62** [comment] 2020-10-23 18:28
@boydc2014 I don't think this is selector related assuming the Event2 handler looks like the Event1 one.  If so, then Event1 is emitted and there is a single trigger which matches.  Then Event2 is emitted and there is a single trigger that matches.  Events should be emitted in order.  @Stevenic or @tomlm do you see anything that would cause this issue?  I suspect we need someone to repro.

**Comment by EricDahlvang** [comment] 2020-10-24 00:15
Changing this line:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/ActionContext.cs#L65

from `queue.Add(changes);` to `queue.Insert(0, changes);`  fixes the issue:

![image](https://user-images.githubusercontent.com/11055362/97063219-3d4f2d00-1553-11eb-827d-90af35558425.png)


I don't know if this is a valid fix or not.

**Comment by EricDahlvang** [comment] 2020-10-24 01:51
It turns out that fixes this one specific issue, but others arise.

**Comment by EricDahlvang** [comment] 2020-10-25 16:01
Here is a repro:

[customaction.zip](https://github.com/microsoft/botbuilder-dotnet/files/5435153/customaction.zip)

[TestEventEmitter2_export.zip](https://github.com/microsoft/botbuilder-dotnet/files/5435156/TestEventEmitter2_export.zip)

```cs
        public async override Task<DialogTurnResult> BeginDialogAsync(DialogContext dialogContext, object options = null, CancellationToken cancellationToken = default(CancellationToken))
        {
            await dialogContext.EmitEventAsync("Event1", null);
            await dialogContext.Context.SendActivityAsync("After Event 1, before Event2");
            await dialogContext.EmitEventAsync("Event2", null);
            await dialogContext.Context.SendActivityAsync("After Event 2");

            return await dialogContext.EndDialogAsync();
        }
```


![image](https://user-images.githubusercontent.com/11055362/97112285-a1cbd280-16a0-11eb-9120-9e1529ea4427.png)

**Comment by gabog** [comment] 2020-11-05 17:45
Hi Dong, can you also look at #4662 and make sure we address that issue as part of this one?

**Comment by boydc2014** [comment] 2020-11-06 07:50
> Hi Dong, can you also look at #4662 and make sure we address that issue as part of this one?

Thanks @gabog, we've looked at #4662 and can't repro it on our side, and i've pinged Steve to put more details on that one. And i don't think these two are related. 

Regarding specifically this one, the root cause, as far as i can tell, is this "EmitEventAsync" perhaps not designed as a public API, it's designed as a internal API that used as internal implementation (like EmitEvenAction) and have coded in a specific order to apply events. 

We tried fixing this by reversing the order how events are applied, see the PR #4885 above. It fixes this issue, but breaks other existing issues, so we closed it for now.  I will work with Tom and Steve soon to get a triage on this one.

**Comment by boydc2014** [comment] 2020-11-06 07:53
> Changing this line:
> https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/ActionContext.cs#L65
> 
> from `queue.Add(changes);` to `queue.Insert(0, changes);` fixes the issue:
> 
> ![image](https://user-images.githubusercontent.com/11055362/97063219-3d4f2d00-1553-11eb-827d-90af35558425.png)
> 
> I don't know if this is a valid fix or not.

Yes, this event\changelist apply order is specific designed to be able to support the case of interruption. So, changing that will break other cases.

**Comment by Danieladu** [comment] 2020-11-12 06:50
For some coupling relationships between dialog and "EmitEventAsync" function, there indeed exists some gap between calling "EmitEventAsync" function directly and maintain the order of the events.

We suggest using the existing "EmitEvent" action to accomplish the same function.
I have committed a branch that gives a sample about emit several events:

https://github.com/microsoft/botbuilder-dotnet/blob/hond/emit-events/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/ActionTests/Action_EmitEventList.test.dialog

**Comment by boydc2014** [comment] 2020-11-12 12:43
@cxbuilders we did a group triage on this one today and identified that this is an issue related to something very deep in how event and actions are applied. And this function "EmitEventAsync" has certain implications in a customized action context and there isn't a easy fix to correct the order this. 

The general guidance we came up for this "EmitEventAsync" function is, we recommend only calle this function once in a customized functions.  If in your scenarios, you do reply on sending out multiple events inside one action and the order really matters, an alternative we recommend is like the comment above, please save your events in a memory and return from the customized action. Then continue fire up the events using the built-in "EmitEvent" action, it will give you the correct order of the events. 

Let us know if this helps. Thanks

**Comment by cxbuilders** [comment] 2020-11-12 18:04
@boydc2014 thanks for that. I now have simply reversed the order and it seems stable. Can you confirm that the order is always just reversed as I could  work with that.

**Comment by boydc2014** [comment] 2020-12-02 07:24
> @boydc2014 thanks for that. A bit unfortunate it cannot be properly fixed. I now have simply reversed the order and it seems stable. Can you confirm that the order is always just reversed as I could work with that.

At current implementation, it is. But i can't really say it's guaranteed. 

The alternative suggested above, using multiple `EmitEvent` actions, outside the customized action, is a guaranteed behavior.

**Closed** 2021-01-08 08:17 UTC
Labels: Area: Adaptive, Bot Services, Size: M, bug, customer-replied-to, customer-reported
