### ISSUE TITLE
MemoryTranscriptStore.GetTranscriptActivitiesAsync may end up in infinite loop

### ISSUE THREAD

**Issue by piotrzajac** [microsoft/botbuilder-dotnet#3665] opened 2020-04-02 10:15 UTC
## Version
4.7.2

## Describe the bug
The `ContinuationToken` within the `MemoryTranscriptStore.GetTranscriptActivitiesAsync` relies on last `Activity.Id` of loaded `PagedResult`.
`Microsoft.Bot.Builder.AI.QnA.QnAMaker.GetAnswersRawAsync` emits trace activities with `Activity.Id` being set to empty string (`""`).
When invoking `MemoryTranscriptStore.GetTranscriptActivitiesAsync` it may happen that trace activity is the last one on `PagedResult` thus `ContinuationToken` is being set to empty string (`""`).
Because of the following condition `.SkipWhile(a => a.Id != continuationToken)` we may and up loading the same `PagedResult`(s) over and over again.

## To Reproduce
1. Create knowledge base with some content (e.g. chitchat).
2. Save & Test > Publish
3. Create bot from Publish website
4. Download bot source code
5. Register `MemoryTranscriptStore` and `TranscriptLoggerMiddleware` logger in `Startup`
```cs
services.AddSingleton<ITranscriptStore, MemoryTranscriptStore>();
services.AddSingleton(sp => new TranscriptLoggerMiddleware(sp.GetService<ITranscriptStore>()));
```
6. Modify `AdapterWithErrorHandler` to use registered `TranscriptLoggerMiddleware`
```cs
public AdapterWithErrorHandler(
    IConfiguration configuration,
    ILogger<BotFrameworkHttpAdapter> logger,
    TranscriptLoggerMiddleware transcriptLoggerMiddleware,
    ConversationState conversationState = null)
        : base(configuration, logger)
    {
        // ...
        this.Use(transcriptLoggerMiddleware);
        // ...
    }
```
7. Enrich bot with a logic of retrieving transcript messages, e.g.:
```cs
public async Task<IEnumerable<IMessageActivity>> GetTranscriptAsync(IActivity activity)
{
    if (activity == null)
    {
        throw new ArgumentNullException(nameof(activity));
    }

    var activities = new List<IMessageActivity>();
    string continuationToken = null;

    do
    {
        var pagedTranscript = await this.store.GetTranscriptActivitiesAsync(
            activity.ChannelId,
            activity.Conversation?.Id,
            continuationToken);
        var entries = pagedTranscript.Items
            .Where(a => a.Type == ActivityTypes.Message)
            .Select(a => (IMessageActivity)a);
        activities.AddRange(entries);

        continuationToken = pagedTranscript.ContinuationToken;
    }
    while (continuationToken != null);

    return activities;
}
```
8. Compile and publish with publishing profile.

## Expected behavior
The store should ensure to return stored activities without risk of infinite loop.

[bug]

**Comment by Zerryth** [comment] 2020-04-04 03:02
Ah, nvm, got it 😄! 

![image](https://user-images.githubusercontent.com/35248895/78417317-a8e8a180-75e5-11ea-9bc7-53aafaf2ea0f.png)

And yes, I see that the transcript logger is indeed storing activities without an id.

Got the repro down, and I'll work on a fix. We shouldn't store activities without an id in the transcript.

**Comment by Zerryth** [comment] 2020-04-06 23:27
Aaaand this is why weekends are important, because sometimes you're so tired, you see what you want to see.

The screenshot I took was not actually me reproducing the bug that you are describing--you see `["trace"]""` with empty string next to trace, but that doesn't mean the Id is missing, but only that it doesn't have any `Text`.

Trace in Transcript/PagedResult:
![image](https://user-images.githubusercontent.com/35248895/78614063-64961500-7822-11ea-9b91-e1039d941ebd.png)
...
![image](https://user-images.githubusercontent.com/35248895/78614087-77a8e500-7822-11ea-8bba-4f952712965f.png)
![image](https://user-images.githubusercontent.com/35248895/78614111-87c0c480-7822-11ea-9736-55da27096f0b.png)

**So `MemoryTranscriptStore` will *not* break on QnA traces, as they do get assigned an ID, coming back from the channel.**

___

That being said, you are right in that it *is* possible for an infinite loop to occur if the circumstances are right with regards to Activities being recorded by the logger that don't have an ID. And according to the [Activity spec in botframework-sd](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#id), not all activities actually do get assigned an Id by the channel:
> The id field establishes the identity for the activity once it has been recorded in the channel. Activities in-flight that have not yet been recorded do not have identities. Not all activities are assigned identities (for example, a typing activity may never be assigned an id.)

So right now I'll investigate further to ensure that there's code to ensure that there are guards to handle situations where IDs are not assigned for the logger to consume without breaking, before closing this issue.

**Closed** 2020-04-15 16:48 UTC
Labels: Bot Services, P2, R9, bug, customer-replied-to, customer-reported
