### ISSUE TITLE
ComponentDialog::BuildDialogState throws NullReferenceException

### ISSUE THREAD

**Issue by WueF** [microsoft/botbuilder-dotnet#6576] opened 2023-01-16 04:05 UTC
## Version
SDK 4.19
.NET 7

## Describe the bug
BuildDialogState throws NullReferenceException (in line `if (state.DialogStack == null)`
Dialog isn't properly restored in line `state = instance.State[PersistedDialogState] as DialogState;`, although `instance` object is set properly, and State seems to be proper JObject. It looks like deserialization goes wrong. Issue appears only after upgrade to 4.19, on 4.18.1 no exception is thrown.

## To Reproduce
In my bot:
1. Conversation is initiated
2. First dialogstack is built
3. Response to user is sent.
4. User sends message
5. On rebuilding stack exception is thrown

## Expected behavior
DialogState is properly rebuilt

**Comment by anishprasad01** [comment] 2023-01-16 18:38
Hi @WueF,

Using a fresh copy of [C# Sample 13 - Core Bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/13.core-bot), I attempted to reproduce your issue by doing the following:

* Change build target to .NET 7.0
* Update all Bot Builder packages to 4.19.0
* Update .NET packages to 7.x
* Clean and Rebuild Project
* Run bot and proceed through the example dialog flow

After performing these steps, I was able to go through the entire mock travel booking without encountering any NullReferenceExceptions in the ComponentDialog.

If there is more information about this issue that can help narrow down what is causing it (such as what other services are integrated, potentially incompatible packages and so on), please let me know so that I can investigate further.

**Comment by markbeau** [comment] 2023-01-20 16:23
I'm experiencing what I believe is a related issue in my code in OnMessageAcitivityAsync() at
`await Dialog.RunAsync(turnContext, ConversationState.CreateProperty<DialogState>("DialogState"), cancellationToken);`   

```
This exception was originally thrown at this call stack:
    [External Code]
    DigitalMarx_IOT_Bot.Bots.DialogBot<T>.OnMessageActivityAsync(Microsoft.Bot.Builder.ITurnContext<Microsoft.Bot.Schema.IMessageActivity>, System.Threading.CancellationToken) in DialogBot.cs
```

Upgrading one Nuget package at a time, I get the exception only after upgrading Microsoft.Bot.Builder.Azure to 4.19.x. in either the .NET6 or .NET7 target frameworks.  The other packages I use don't seem to be the issue.

I'm using CosmosDb to store user and conversation state.
`services.AddSingleton<IStorage>(new CosmosDbPartitionedStorage(settings.CosmosDb));`

The samples default to MemoryStorage().  Could you try reproducing using CosmosDb?

**Comment by WueF** [comment] 2023-01-20 16:36
Yes, I confirm above's findings. Issue exists, when using CosmosDB for state and Microsoft.Bot.Builder.Azure >= 4.19. When upgraded other packages to 4.19, but remained this one on 4.18.1, bot works fine.

**Comment by anishprasad01** [comment] 2023-01-20 16:38
Thank you both for that information. I will attempt to repro with Cosmos for state.

**Comment by anishprasad01** [comment] 2023-01-23 19:23
I ran another test with [Sample 45.State Management](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/45.state-management) using Cosmos.

Interestingly, I do not get a NullReferenceException. However, the sample does not function correctly, and the CosmosDB state is indeed broken. I can therefore confirm and reproduce an issue with Bot.Builder.Azure versions 4.19.x. 

We will proceed to looking into a solution for this. In the meantime, please continue to use 4.18.1, as we have all confirmed that it is working.

**Comment by aroksa** [comment] 2023-01-26 02:32
Greetings,

I had the same issue with the blob storage provider as well.  I was able to resolve (at least for Cosmos) by passing in a custom serializer - I used the default, but had to add `DialogState` and `PromptOptions` to the `AllowedTypesSerializationBinder` [here](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs#L28)

In my case, the NRE was thrown on [this line](https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs#L396) because the [cast here](https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.Dialogs/ComponentDialog.cs#L388) was from JObject to DialogState.

**Comment by anishprasad01** [comment] 2023-01-26 16:21
@aroksa 

Thank you, I will update the issue to reflect that.

**Comment by anishprasad01** [comment] 2023-02-07 15:55
https://github.com/microsoft/botbuilder-dotnet/pull/6585 should fix this issue.

**Comment by anishprasad01** [comment] 2023-02-15 17:13
Fix merged, will be live in the next patch release.

**Closed by anishprasad01** 2023-02-15 17:13 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to

**Comment by sbiaudet** [comment] 2023-05-02 19:06
I've the same problem with MemoryStorage used in unit tests
