### ISSUE TITLE
authoringKey being used form .bot file instead of subscriptionKey

### ISSUE THREAD

**Issue by devedse** [Microsoft/botbuilder-dotnet#1476] opened 2019-03-15 10:25 UTC
## Version
4.3.2

## Describe the bug
I have the following bot file:
```
{
  "name": "ShellCato",
  "description": "",
  "services": [
    {
      "type": "endpoint",
      "appId": "123-123-123-123",
      "appPassword": "secret123",
      "endpoint": "http://localhost:3978/api/messages",
      "id": "1",
      "name": "LocalDev"
    },
    {
      "type": "luis",
      "appId": "123-123-123-123",
      "authoringKey": "123bbbbbbbbbbbbbbbbbbbbbbbb",
      "id": "34",
      "name": "ShellCatoLuis",
      "region": "westeurope",
      "subscriptionKey": "cbeaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "version": "0.1"
    }
  ],
  "padlock": "",
  "version": "2.0",
  "path": "C:\....",
  "overrides": null
}
```

When I make requests to LUIS using this it uses the authoring key when doing the requests. I would expect that it should make use of the subscriptionKey?

## To Reproduce
1. Create a new LUIS project using and enter a different authoring key from the subscription key
2. Make a request from the bot to LUIS and check what key is being sent using Fiddler

## Expected behavior
I would expect the bot to use the subscriptionKey instead of the authoringKey

## Screenshots
N/a

## Additional context
N/a

[bug]

**Comment by devedse** [comment] 2019-03-15 10:33
Edit, I think this is an issue in the CSharp template('s) for the bot:
https://github.com/Microsoft/BotBuilder-Samples/blob/729700252e71778eeded4b6cfd53e44bacdfecfd/generators/dotnet-templates/Microsoft.BotFramework.CSharp.CoreBot/content/BotServices.cs

**Comment by dmvtech** [comment] 2019-03-18 15:52
Hi @devedse.

This is by design. For our samples, [we have commented](https://github.com/Microsoft/BotBuilder-Samples/blob/ba4aeb136782154dffcab4ce6a0f795bdfcf295b/samples/csharp_dotnetcore/14.nlp-with-dispatch/Startup.cs#L179) on why this is the approach:

```
// CAUTION: Authoring key is used in this example as it is appropriate for prototyping.
// When implementing for deployment/production, assign and use a subscription key instead of an authoring key
```

So, yes; to implement using subscription key when moving from development to testing (or from testing to production, depending on your design paradigm), you will need to ensure that you have a subscription key and make the appropriate changes to the code to utilize that (of course you can change your code to have logic dynamically dynamically use one or the other).

Thank you for pointing out the lack of documentation/comments regarding this piece of code. We will work to remedy that.

**Comment by CoHealer** [comment] 2019-03-19 21:44
Closing as by design

**Closed by CoHealer** 2019-03-19 21:44 UTC
Labels: Support
