### ISSUE TITLE
V4 Template for Visual Studio doesn't build, gets stuck, 2 projects

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/botbuilder-dotnet#981] opened 2018-09-24 15:50 UTC
## Version
4.0.7

## Describe the bug
If you download and install the template https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4
and then open the template, there are two projects Basic Bot and Echo Bot.
When you try to build the solution it just hangs and gets stuck

## To Reproduce
1. Go to https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4 and add/install the template to Visual C# item templates
2. Open VS and create a new project starting from the template
3. Run or build the solution
4. See error (nothing happens, just gets stuck)

## Expected behavior
Should just be one project and it should build and run

[bug]

**Comment by amthomas46** [comment] 2018-09-24 16:00
After 3 attempts of cancelling deleting and starting over, it builds after 16 min. Still with two projects, which I think is confusing as a "template"

**Comment by amthomas46** [comment] 2018-09-24 16:12
Maybe it's just the first time it builds, because starting over again now it works normally. May want to add some notes about it to docs.

Thanks,
Anna

**Comment by cleemullins** [comment] 2018-09-27 20:30
Good point about the 2 templates in the single VSIX. We will consider moving this to 2 seperate VSIX projects in the next iteration.

**Comment by stevengum** [comment] 2018-10-02 22:40
@nyxsys can you take a look and see if you can repro? Thanks!

**Comment by nyxsys** [comment] 2018-10-03 18:49
This has been double checked on four systems over here, and currently we are unable to reproduce the 16 minute build time mentioned.

**Comment by stevengum** [comment] 2018-10-03 19:29
@amthomas46 at the moment we're not planning on splitting the projects into separate VSIX templates. 

Closing the issue as a non-repro.

**Closed by stevengum** 2018-10-03 19:29 UTC
Labels: Support
