### ISSUE TITLE
MicrosoftAppCredentials does not accept empty MicrosoftAppId and MicrosoftAppPassword

### ISSUE THREAD

**Issue by WizX20** [microsoft/botbuilder-dotnet#4402] opened 2020-08-06 09:08 UTC
## Version
Microsoft.Bot.Builder Version 4.9.4
_Microsoft.Bot.Builder.Azure Version 4.9.4
Microsoft.Bot.Builder.Dialogs Version 4.9.4
Microsoft.Bot.Builder.Integration.AspNet.Core Version 4.9.4
Microsoft.Bot.Configuration Version 4.9.4
Microsoft.Bot.Schema Version 4.9.4
Microsoft.Bot.Solutions Version 1.0.1_

## Describe the bug
The `Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials` does not accept empty MicrosoftAppId and MicrosoftAppPassword.

**Related**
[AdalAuthenticator does not accept empty MicrosoftAppId and MicrosoftAppPassword](https://github.com/Microsoft/BotBuilder-V3/issues/68)

**StackTrace**
```
System.ApplicationException: There was an exception wile trying to send the activity 'Microsoft.Bot.Schema.Activity' with text (optional) 'Test-Callback message from Postman' to conversation '35620e20-d7c1-11ea-be6a-b530f7586fc5|livechat' and user 'cd7dad39-17ed-4af7-8b7a-2d493e2b1935'!
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'clientId')
   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential..ctor(String clientId, String clientSecret)
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<BuildAuthenticator>b__14_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<BuildIAuthenticator>b__34_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.GetTokenAsync(Boolean forceRefresh)
   at Microsoft.Bot.Connector.Authentication.AppCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.Conversations.SendToConversationWithHttpMessagesAsync(String conversationId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.SendToConversationAsync(IConversations operations, String conversationId, Activity activity, CancellationToken cancellationToken)
```

## To Reproduce
1. Create a new connector-client:
    `var connectorClient = new Microsoft.Bot.Connector.ConnectorClient(baseUri, MicrosoftAppCredentials.Empty);`
2. Use it to send a pro-active message:
    `await connectorClient.Conversations.SendToConversationAsync(activity);`
3. See error

## Expected behavior
MicrosoftAppCredentials.Empty is valid, when no credentials are set; we are running the code locally, on our (dev) machine, with the `microsoftAppId` and `microsoftAppPassword` in the `appsettings.json` set to empty: `""`

[bug]

**Comment by WizX20** [comment] 2020-08-06 09:44
Using this for now so I can get on with it for now...
**Notice: Not properly tested, use at your own risk!**

```
using Microsoft.Bot.Connector.Authentication;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using System.Threading.Tasks;

namespace MyNameSpace.Authentication
{
    /// <summary>
    /// TODO: This is a HOTFIX, please check https://github.com/microsoft/botbuilder-dotnet/issues/4402 for any updates.
    /// </summary>
    public class MicrosoftAppCredentialsFix : MicrosoftAppCredentials
    {
        internal static readonly IDictionary<string, DateTime> TrustedHostNames = new Dictionary<string, DateTime>
        {
            // { "state.botframework.com", DateTime.MaxValue }, // deprecated state api
            { "api.botframework.com", DateTime.MaxValue }, // bot connector API
            { "token.botframework.com", DateTime.MaxValue }, // oauth token endpoint
            { "api.botframework.azure.us", DateTime.MaxValue }, // bot connector API in US Government DataCenters
            { "token.botframework.azure.us", DateTime.MaxValue }, // oauth token endpoint in US Government DataCenters
        };

        /// <summary>
        /// Authenticator abstraction used to obtain tokens through the Client Credentials OAuth 2.0 flow.
        /// </summary>
        private Lazy<IAuthenticator> _authenticator;

        public MicrosoftAppCredentialsFix(string appId, string password) : base(appId, password)
        {
        }

        public MicrosoftAppCredentialsFix(string appId, string password, HttpClient customHttpClient) : base(appId, password, customHttpClient)
        {
        }

        public MicrosoftAppCredentialsFix(string appId, string password, HttpClient customHttpClient, ILogger logger)
            : base(appId, password, customHttpClient, logger)
        {
        }

        public MicrosoftAppCredentialsFix(string appId, string password, string channelAuthTenant, HttpClient customHttpClient)
            : base(appId, password, channelAuthTenant, customHttpClient)
        {
        }

        public MicrosoftAppCredentialsFix(string appId, string password, HttpClient customHttpClient, ILogger logger, string oAuthScope)
            : base(appId, password, customHttpClient, logger, oAuthScope)
        {
        }

        public MicrosoftAppCredentialsFix(string appId, string password, string channelAuthTenant, HttpClient customHttpClient, ILogger logger = null)
            : base(appId, password, channelAuthTenant, customHttpClient, logger)
        {
        }

        public MicrosoftAppCredentialsFix(string appId, string password, string channelAuthTenant, HttpClient customHttpClient, ILogger logger = null, string oAuthScope = null)
            : base(appId, password, channelAuthTenant, customHttpClient, logger, oAuthScope)
        {
        }

        /// <summary>
        /// Apply the credentials to the HTTP request.
        /// </summary>
        /// <param name="request">The HTTP request.</param><param name="cancellationToken">Cancellation token.</param>
        /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
        public override async Task ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            if (this.ShouldSetToken(request, Logger))
            {
                var token = await this.GetTokenFixAsync().ConfigureAwait(false);
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            }

            if (_authenticator != null)
            {
                await base.ProcessHttpRequestAsync(request, cancellationToken).ConfigureAwait(false);
            }
        }

        /// <summary>
        /// Gets an OAuth access token.
        /// </summary>
        /// <param name="forceRefresh">True to force a refresh of the token; or false to get
        /// a cached token if it exists.</param>
        /// <returns>A task that represents the work queued to execute.</returns>
        /// <remarks>If the task is successful, the result contains the access token string.</remarks>
        public async Task<string> GetTokenFixAsync(bool forceRefresh = false)
        {
            _authenticator ??= this.BuildIAuthenticator();
            if (_authenticator == null)
            {
                Logger?.LogWarning($"{this.GetType().FullName}.ProcessHttpRequestAsync(): got empty authenticator from call to the configured IAuthenticator.");
                return string.Empty;
            }

            var token = await _authenticator.Value.GetTokenAsync(forceRefresh).ConfigureAwait(false);
            if (string.IsNullOrWhiteSpace(token.AccessToken))
            {
                Logger?.LogWarning($"{this.GetType().FullName}.ProcessHttpRequestAsync(): got empty token from call to the configured IAuthenticator.");
            }

            return token.AccessToken;
        }

        /// <summary>
        /// Builds the lazy <see cref="AdalAuthenticator" /> to be used for token acquisition.
        /// </summary>
        /// <returns>A lazy <see cref="AdalAuthenticator"/>.</returns>
        protected override Lazy<AdalAuthenticator> BuildAuthenticator()
        {
            if (string.IsNullOrWhiteSpace(MicrosoftAppId))
            {
                return null;
            }

            return new Lazy<AdalAuthenticator>(
                () =>
                new AdalAuthenticator(
                    clientCredential: new ClientCredential(MicrosoftAppId, MicrosoftAppPassword),
                    configurationOAuth: new OAuthConfiguration() { Authority = OAuthEndpoint, Scope = OAuthScope },
                    customHttpClient: this.CustomHttpClient,
                    logger: this.Logger),
                LazyThreadSafetyMode.ExecutionAndPublication);
        }

        /// <summary>
        /// Builds the lazy <see cref="IAuthenticator" /> to be used for token acquisition.
        /// </summary>
        /// <returns>A lazy <see cref="IAuthenticator"/>.</returns>
        protected override Lazy<IAuthenticator> BuildIAuthenticator()
        {
            return new Lazy<IAuthenticator>(
                () =>
                {
                    var lazyAuthenticator = this.BuildAuthenticator();
                    return lazyAuthenticator?.Value;
                },
                LazyThreadSafetyMode.ExecutionAndPublication);
        }

        private static bool IsTrustedUrl(Uri uri, ILogger logger)
        {
            lock (TrustedHostNames)
            {
                if (TrustedHostNames.TryGetValue(uri.Host, out var trustedServiceUrlExpiration))
                {
                    // check if the trusted service url is still valid
                    if (trustedServiceUrlExpiration > DateTime.UtcNow.Subtract(TimeSpan.FromMinutes(5)))
                    {
                        return true;
                    }

                    logger?.LogWarning($"{typeof(AppCredentials).FullName}.IsTrustedUrl(): '{uri}' found in TrustedHostNames but it expired (Expiration is set to: {trustedServiceUrlExpiration}, current time is {DateTime.UtcNow}).");
                    return false;
                }

                logger?.LogWarning($"{typeof(AppCredentials).FullName}.IsTrustedUrl(): '{uri}' not found in TrustedHostNames.");
                return false;
            }
        }

        private bool ShouldSetToken(HttpRequestMessage request, ILogger logger)
        {
            if (string.IsNullOrWhiteSpace(MicrosoftAppId))
            {
                logger?.LogWarning($"{this.GetType().FullName}.ShouldSetToken(): '{nameof(MicrosoftAppId)}' is not set (empty).");
                return false;
            }

            if (IsTrustedUrl(request.RequestUri, logger))
            {
                return true;
            }

            logger?.LogWarning($"{this.GetType().FullName}.ShouldSetToken(): '{request.RequestUri.Authority}' is not trusted and JwtToken cannot be sent to it.");
            return false;
        }
    }
}

```

**Comment by carlosscastro** [comment] 2020-08-06 18:06
Hey, we are throwing the exception on purpose, because we don't accept null client id or password. If you wnat empty credentials, use MicrosoftAppCredentials.Empty.

The question is, why do you want to pass null to the credentials? what are you trying to achieve. Closing since this is not a bug, it is by design, but happy to respond questions.

**Comment by carlosscastro** [comment] 2020-08-06 18:17
Hello, thanks for reporting. I understand that you are trying to achieve proactive messaging with empty credentials, is that correct?

Could you provide a full repro of the end to end scenario? For example, `start from the [proactive sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/16.proactive-messages), modify setting X, create a console application with this code and run it`.

**Comment by WizX20** [comment] 2020-08-12 08:35
@carlosscastro Hi, I will try and create an example repo, give me some time... 
I am indeed using proactive messaging with empty credentials (`MicrosoftAppCredentials.Empty`)

**Comment by lauren-mills** [comment] 2020-08-25 18:15
Closing due to inactivity. Please reopen as needed.

**Closed by lauren-mills** 2020-08-25 18:15 UTC
Labels: Bot Services, customer-replied-to, customer-reported
