### ISSUE TITLE
LuisRecognizer surpresses the start and end attributes for data type builtin.datetimeV2.daterange

### ISSUE THREAD

**Issue by bchen007** [Microsoft/botbuilder-dotnet#798] opened 2018-07-26 20:56 UTC
When I call the Recognize method and it does not return the start and end attributes in a LuisResult object for datetimeV2 data type which are available in the response.

recognizerResult = await luisRecognizer.Recognize(text, System.Threading.CancellationToken.None);

or 
var luisResult = context.Services.Get<RecognizerResult>(LuisRecognizerMiddleware.LuisRecognizerResultKey) as RecognizerResult

**Comment by vishwacsena** [comment] 2018-09-06 21:02
@carlosscastro ; @daveta - since you guys recently did samples with LUIS on the C# side, can you take a look a this to see if we continue to repro this with the latest bits?

**Comment by cleemullins** [comment] 2018-09-11 22:48
@Zerryth, can you please take a look and chase this down? This may require working with @chrimc62 to drive resolution.

**Comment by Zerryth** [comment] 2018-09-11 22:51
@cleemullins Will do, Chris! Investigating...

**Comment by cleemullins** [comment] 2018-09-12 21:19
@Zerryth Any updates?

**Comment by Zerryth** [comment] 2018-09-12 22:07
@bchen007 to clarify, you're saying that your language model is ok, correct? (And that there's no bug within the builtin entity itself)

When you test via luis portal (at luis.ai for example), your results do yield **start** and **end** values in **resolution** like below, for example:

```
 "entities": [
    {
      "entity": "tuesday to thursday",
      "type": "builtin.datetimeV2.daterange",
      "startIndex": 0,
      "endIndex": 19,
      "resolution": {
        "values": [
          {
            "timex": "(XXXX-WXX-2,XXXX-WXX-4,P2D)",
            "type": "daterange",
            "start": "2017-06-13",
            "end": "2017-06-15"
          },
          {
            "timex": "(XXXX-WXX-2,XXXX-WXX-4,P2D)",
            "type": "daterange",
            "start": "2017-06-20",
            "end": "2017-06-22"
          }
        ]
      }
    }
  ]
```

Also, could you let me know what utterances you're using to test? If you are able to [export the JSON of your model and share](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-how-to-manage-versions#export-version), that'd be even better.

For now I'm creating my own LUIS model with `builtin.datetimeV2.daterange` entity, and assume that things are golden on the LUIS end test `.Recognize()` from the bot framework specifically

**Comment by Zerryth** [comment] 2018-09-12 22:09
> When I call the Recognize method and it does not return the start and end attributes in a LuisResult object for datetimeV2 data type which are available in the response.

Also, could you please share what the response looks like for you as well?

**Comment by Zerryth** [comment] 2018-09-12 22:57
@cleemullins @chrimc62 I was able to repro the issue that the user posted:

in my Startup.cs under ConfigureServices method

```
                // Add LUIS recognizer as middleware
                var (modelId, subscriptionKey, url) = GetLuisConfiguration(Configuration);
                var model = new LuisModel(modelId, subscriptionKey, url);
                options.Middleware.Add(new LuisRecognizerMiddleware(model));  
```

In my EchoBot.cs

```
public async Task OnTurn(ITurnContext context)
        {
            // This bot is only handling Messages
            if (context.Activity.Type == ActivityTypes.Message)
            {
                var result = context.Services.Get<RecognizerResult>
                    (LuisRecognizerMiddleware.LuisRecognizerResultKey);
                var topIntent = result?.GetTopScoringIntent();
                switch ((topIntent != null) ? topIntent.Value.intent : null )
                {
                    case null:
                        await context.SendActivity("Womp womp. Failed to get results from LUIS.");
                        break;
                    case "None":
                        await context.SendActivity("Sorry, I don't understand. :(");
                        break;
                    case "Help":
                        await context.SendActivity("<here's some help>");
                        break;
                    case "Cancel":
                        // Cancel the process.
                        await context.SendActivity("<cancelling the process>");
                        break;
                    case "Weather":
                        await context.SendActivity("The weather today is sunny.");
                        break;
                    case "BookHotel":
                        await context.SendActivity("In BookHotel case");

                        break;
                    default:
                        // Received an intent we didn't expect, so send its name and score.
                        await context.SendActivity($"Intent: {topIntent.Value.intent} ({topIntent.Value.score})");
                        break;
                }
            }
        }
```
Luis service is called, and we hit the case for BookHotel sending in an utterance:

![image](https://user-images.githubusercontent.com/35248895/45457497-06379d80-b6a4-11e8-95c5-94a5d5b13a7d.png)


**result only contains values for "type": "daterange", and "timex": -- no "start" and "end" key-values**

![image](https://user-images.githubusercontent.com/35248895/45457553-5c0c4580-b6a4-11e8-912e-1ca6992dba30.png)


Also, it does not appear to be an issue on the LUIS endpoint side, as the JSON result from querying the endpoint directly actually does contain "start" and "end":

```
{
  "query": "book a room for tuesday thru thursday",
  "topScoringIntent": {
    "intent": "BookHotel",
    "score": 0.9016342
  },
  "intents": [
    {
      "intent": "BookHotel",
      "score": 0.9016342
    },
    {
      "intent": "Weather",
      "score": 0.0593839
    },
    {
      "intent": "Help",
      "score": 0.0123519311
    },
    {
      "intent": "None",
      "score": 0.008161762
    },
    {
      "intent": "OrderFood",
      "score": 0.006917159
    },
    {
      "intent": "Cancel",
      "score": 0.004559632
    },
    {
      "intent": "Greeting",
      "score": 0.00203509326
    }
  ],
  "entities": [
    {
      "entity": "tuesday thru thursday",
      "type": "builtin.datetimeV2.daterange",
      "startIndex": 16,
      "endIndex": 36,
      "resolution": {
        "values": [
          {
            "timex": "(XXXX-WXX-2,XXXX-WXX-4,P2D)",
            "type": "daterange",
            "start": "2018-09-11",
            "end": "2018-09-13"
          }
        ]
      }
    }
  ]
}
```

**Comment by carlosscastro** [comment] 2018-09-15 22:27
Closing this as it is not a bug. Timex resolution from the server to concrete start and end dates is not accurate generally because it does not have enough context. It is recommended to use the timex library to resolve the concrete dates in your application given the timex returned from LUIS.

**Closed by carlosscastro** 2018-09-15 22:27 UTC
Labels: Approved, Next-Iteration, bug

**Comment by AskYous** [comment] 2019-06-26 23:25
> It is recommended to use the **timex library** to resolve the concrete dates in your application

Hello @carlosscastro. Can you explain where I can get a Timex library? I am also suffering the same issue and I can't seem to find a Timex library in C#.

**Comment by AskYous** [comment] 2019-06-26 23:35
Nevermind. I think [this example](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/40.timex-resolution/Ranges.cs#L44) shows one.
