### ISSUE TITLE
Adaptive ForEachElement loop's incorrectly when changes cause ContinueDialogAsync to be recalled

### ISSUE THREAD

**Issue by Rich-biomni** [microsoft/botbuilder-dotnet#6428] opened 2022-08-01 11:28 UTC
## Version
c# 4.16.1

## Describe the bug
When looping using the ForEachElement, if something causes changes the ForEachElement runs the first action in its actions list rather the continuing with the next.

## To Reproduce
Use the ForEachElement with > 1 loops
In the Actions Property
 Ask a question
 Begin Dialog where the dialog is an adaptive dialog, and its action causes change (for example use EditAction)
 Show a message when the dialog starts
 Show the result of Question

Run the bot, notice on the 2nd time around the loop it jumps back to first action in its actions list

## Expected behavior
Each loop of the ForEachElement should carry out each action sequentially 

## Additional context
Just guessing, but because action changes cause ContinueDialogAsync to be recursively called the 'childDialogState' can get out of sync when the final pop of recursion returns from ContinueDialogAsync. Is the fix to reacquire the 'childDialogState' after ?

Attached is Simple Bot that shows it going wrong

[SimpleBot.zip](https://github.com/microsoft/botbuilder-dotnet/files/9233430/SimpleBot.zip)

**Comment by LeeParrishMSFT** [comment] 2022-08-01 18:19
Thanks for the issue details and repro project. We have some fixes for an issue related to this in the main branch here [Handle DialogEvents.RepromptDialog in ForEachElement](https://github.com/microsoft/botbuilder-dotnet/pull/6325) that will be part of an upcoming release. We will use your sample to test this and see if it will solve this issue.

**Comment by JamesSinclairBiomni** [comment] 2022-08-03 09:39
> Thanks for the issue details and repro project. We have some fixes for an issue related to this in the main branch here [Handle DialogEvents.RepromptDialog in ForEachElement](https://github.com/microsoft/botbuilder-dotnet/pull/6325) that will be part of an upcoming release. We will use your sample to test this and see if it will solve this issue.

Looks like this issue was reported against Bot Framework DotNet SDK 4.16.1 which includes the fix you're referring to but this issue is still broken

**Comment by stevkan** [comment] 2022-08-05 00:02
@Rich-biomni - Unfortunately, I am unable to test using your Simplebot project. I am getting dependency errors related to the BotFramework Solutions library you have included that I am unable to get around. The library was [marked as obscelete](https://github.com/microsoft/botframework-solutions#the-virtual-assistant-template-and-samples-have-been-replace-by-the-enterprise-assistant-template-in-bot-framework-composer-all-new-projects-should-use-this-template-instead-this-repo-will-be-archived-and-no-longer-actively-supported-on-march-31-2022-the-existing-assets-will-remain-for-reference-but-will-no-longer-be-available-in-the-visual-studio-marketplace-or-nuget-repository) on Mar 31, 2022 and is no longer supported. Additionally, its [docs](https://microsoft.github.io/botframework-solutions/index) state the same while adding that there is no guarantee it will work if used beyond v4.9.1 of the SDK.

Would you be able to provide a more stipped down version of your bot (or just a new project) that focuses on and reproduces the error?

**Comment by Rich-biomni** [comment] 2022-08-05 07:23
@stevkan - Dependency removed

[SimpleBot.zip](https://github.com/microsoft/botbuilder-dotnet/files/9266357/SimpleBot.zip)

**Comment by stevkan** [comment] 2022-08-05 23:52
@Rich-biomni - Thank you for the updated project. I have it working now, without issue, using a local build of the SDK. I have started testing and will let you know what I find. I've found a couple curiosities, but I haven't had a chance to dig into them just yet. I will let you know what I find when I know more.

**Comment by stevkan** [comment] 2022-08-09 18:15
@Rich-biomni - I was able to repro the issue using your sample. Unfortunately, I was unable to find a simple solution / workaround to help mitigate this for you.

Escalating to @JuanAr for continued support on this.

**Comment by Rich-biomni** [comment] 2022-08-15 13:35
@tracyboehrer 

Issue exists in 4.17.1 as well

**Comment by ceciliaavila** [comment] 2022-09-08 14:35
> This PR for this was reverted due to a breaking change. We will need to revisit.
> 
> Notes for SDK: This breaks Bot Designers (PVA) "SlotFillingTest" and some "IntentSwitchingTests". We will need to extract the tests to reproduce outside PVA.

Hi @tracyboehrer, the reverted PR was related to another issue ([#6430](https://github.com/microsoft/botbuilder-dotnet/issues/6430)). Which issue is causing problems with PVA?

**Closed** 2022-09-08 15:14 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to
