### ISSUE TITLE
Reprompt as Unrecognized prompt when interrupt back from another flow in one dialog

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-dotnet#2567] opened 2019-09-20 12:01 UTC
## Version
What package version of the SDK are you using.

## Describe the bug
In one dialog's prompt A, when it is interrupted back from another flow, the A prompt should do a simple reprompt with prompt text, but currently it repromt with unrecognizedPrompt.
![image](https://user-images.githubusercontent.com/16643193/65325412-53b4e780-dbe1-11e9-9176-e094f7e53917.png)

## To Reproduce
[CreateMeeting.dialog.txt](https://github.com/microsoft/botbuilder-dotnet/files/3635770/CreateMeeting.dialog.txt)

## Expected behavior
Repromt the prompt text, not the unrecognizedPrompt one.

## Screenshots
![image](https://user-images.githubusercontent.com/16643193/65324352-92956e00-dbde-11e9-89d5-b49c554a1506.png)

## Additional context

[bug]

**Comment by vishwacsena** [comment] 2019-09-20 22:24
This is by design. You have `allowInterruption = notRecognized` which means the active input should use its own recognizer before deciding to consult up. So in this case, `hahaha` was not recognized by the active input and so the unrecognized prompt was issued. 

Please reactivate the issue if you set `allowInterruption = Always` and continue to see this issue.

**Comment by DingmaomaoBJTU** [comment] 2019-09-23 01:16
Sorry, I think you misunderstood me. "hahaha" should be captured by meeting content only, but currently "hahaha" is not only captured by meeting content, but also send to the datetime prompt again, so it will result to an unrecognizedPrompt. "hahaha" should only take once by one prompt, that's what I mean.

**Comment by vishwacsena** [comment] 2019-09-23 17:44
@DingmaomaoBJTU can you help get a reduced repro as a zip file? What you did in the other bug was very helpful to narrow down the issue.

**Comment by DingmaomaoBJTU** [comment] 2019-09-24 02:54
Sure. Add composer version here: 
[testInterruptionLUIS.zip](https://github.com/microsoft/botbuilder-dotnet/files/3645001/testInterruptionLUIS.zip)

In current composer, its behavior looks like this:
![image](https://user-images.githubusercontent.com/16643193/65477557-4174cb00-deb9-11e9-937a-8d04a82a9992.png)

But in current SDK, its behavior is different but also incorrect. You can check screenshot I pasted in this issue. Lu can repro this successfully with the latest SDK enviorment.

**Comment by vishwacsena** [comment] 2019-10-13 21:52
Cannot repro this in the latest master branch. 

@DingmaomaoBJTU - can you please verify that the repro scenario below accurately reflects what you are trying? If not, please reactivate with a concise repro?

```C# 
var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
{
    Generator = new TemplateEngineLanguageGenerator(_templateEngine),
    Recognizer = new RegexRecognizer()
    {
        Intents = new List<IntentPattern>()
        {
            new IntentPattern()
            {
                Intent = "start",
                Pattern = "start"
            },
            new IntentPattern()
            {
                Intent = "cancel",
                Pattern = "cancel"
            },
            new IntentPattern() {
                Intent = "set_name",
                Pattern = "set name"
            }
        }
    },
    Triggers = new List<OnCondition>()
    {
        new OnConversationUpdateActivity()
        {
            Actions = WelcomeUserAction()
        },
        new OnIntent() {
            Intent = "set_name",
            Actions = new List<Dialog>() {
                new TextInput() {
                    Prompt = new ActivityTemplate("\\[set name]::What is your name?"),
                    Property = "$userName",
                    AlwaysPrompt = true
                },
                new SendActivity() {
                    Activity = new ActivityTemplate("\\[set name]I have {$userName} as your name")
                }
            }
        },
        new OnIntent()
        {
            Intent = "start",
            Actions = new List<Dialog>()
            {
                new TextInput() {
                    Prompt = new ActivityTemplate("\\[start]::What is your name?"),
                    Property = "$userName",
                    AllowInterruptions = "false"
                },
                new SendActivity() {
                    Activity = new ActivityTemplate("\\[start]::I have {$userName} as your name")
                },
                new DateTimeInput() {
                    Prompt = new ActivityTemplate("Give me date 1"),
                    Property = "$fromDate",
                    AllowInterruptions = "true"
                },
                new SendActivity() {
                    Activity = new ActivityTemplate("\\[start]:: I have {$fromDate} as date 1")
                },
                new DateTimeInput() {
                    Prompt = new ActivityTemplate("Give me date 2"),
                    Property = "$toDate",
                    AllowInterruptions = "true"
                },
                new SendActivity() {
                    Activity = new ActivityTemplate("\\[start]:: I have {$toDate} as date 2")
                }
            }
        },
        new OnIntent()
        {
            Intent = "cancel",
            Actions = new List<Dialog>()
            {
                new SendActivity("{WelcomeUser()}")
            }
        }
    }
};
```

**Comment by luhan2017** [comment] 2019-10-21 06:02
> Cannot repro this in the latest master branch.
> 
> @DingmaomaoBJTU - can you please verify that the repro scenario below accurately reflects what you are trying? If not, please reactivate with a concise repro?
> 
> ```cs
> var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
> {
>     Generator = new TemplateEngineLanguageGenerator(_templateEngine),
>     Recognizer = new RegexRecognizer()
>     {
>         Intents = new List<IntentPattern>()
>         {
>             new IntentPattern()
>             {
>                 Intent = "start",
>                 Pattern = "start"
>             },
>             new IntentPattern()
>             {
>                 Intent = "cancel",
>                 Pattern = "cancel"
>             },
>             new IntentPattern() {
>                 Intent = "set_name",
>                 Pattern = "set name"
>             }
>         }
>     },
>     Triggers = new List<OnCondition>()
>     {
>         new OnConversationUpdateActivity()
>         {
>             Actions = WelcomeUserAction()
>         },
>         new OnIntent() {
>             Intent = "set_name",
>             Actions = new List<Dialog>() {
>                 new TextInput() {
>                     Prompt = new ActivityTemplate("\\[set name]::What is your name?"),
>                     Property = "$userName",
>                     AlwaysPrompt = true
>                 },
>                 new SendActivity() {
>                     Activity = new ActivityTemplate("\\[set name]I have {$userName} as your name")
>                 }
>             }
>         },
>         new OnIntent()
>         {
>             Intent = "start",
>             Actions = new List<Dialog>()
>             {
>                 new TextInput() {
>                     Prompt = new ActivityTemplate("\\[start]::What is your name?"),
>                     Property = "$userName",
>                     AllowInterruptions = "false"
>                 },
>                 new SendActivity() {
>                     Activity = new ActivityTemplate("\\[start]::I have {$userName} as your name")
>                 },
>                 new DateTimeInput() {
>                     Prompt = new ActivityTemplate("Give me date 1"),
>                     UnrecognizedPrompt = new ActivityTemplate("Unrecognized, give me date 1"),
>                     Property = "$fromDate",
>                     AllowInterruptions = "true"
>                 },
>                 new SendActivity() {
>                     Activity = new ActivityTemplate("\\[start]:: I have {$fromDate} as date 1")
>                 },
>                 new DateTimeInput() {
>                     Prompt = new ActivityTemplate("Give me date 2"),
>                     Property = "$toDate",
>                     AllowInterruptions = "true"
>                 },
>                 new SendActivity() {
>                     Activity = new ActivityTemplate("\\[start]:: I have {$toDate} as date 2")
>                 }
>             }
>         },
>         new OnIntent()
>         {
>             Intent = "cancel",
>             Actions = new List<Dialog>()
>             {
>                 new SendActivity("{WelcomeUser()}")
>             }
>         }
>     }
> };
> ```

@vishwacsena , I updated your dialog by adding a "UnrecognizedPrompt = new ActivityTemplate("Unrecognized, give me date 1")," in the first DateTimeInput.

The expected scenario is:
user: start
bot: [start]::What is your name?
user: luhan
bot: [start]::I have luhan as your name
bot: Give me date 1
user: set name
bot: [set name]::What is your name?
user: qiong
bot: [set name]I have luhan as your name
bot: Give me date 1

the actual scenario is:
user: start
bot: [start]::What is your name?
user: luhan
bot: [start]::I have luhan as your name
bot: Give me date 1
user: set name
bot: [set name]::What is your name?
user: qiong
bot: [set name]I have luhan as your name
**bot: Unrecognized, give me date 1**


Currently interuptted utterance will always be recognized again. it seems like turn.interrupted is not taking effect.

**Comment by vishwacsena** [comment] 2019-10-21 21:39
Dupe of/ tracked via #2789 - resumption from interruption needs to be handled correctly both when interruption is multi-turn as well as in cases where interruption is across adaptive dialogs.

**Comment by Stevenic** [comment] 2019-10-22 01:43
@tomlm and I put our heads together and I believe we've worked out a solution. We need to replace the `turn.interrupted` flag with a `turn.activityProcessed` flag. This should be set by any component that handles the current activity and interrupted input dialogs can use this flag in much the same way they do `turn.interrupted`.

By default intent triggers and input dialogs will set this flag to indicate that the activity has been consumed.  You can clear this flag using a `SetProperty` step if you're in a trigger and would like the current input dialog to still process the current activity.

This should fix the above issue...

**Comment by vishwacsena** [comment] 2019-10-22 01:53
This is neat. Thanks @stevenic and @tomlm - @Stevenic could we not use the same logic for this DCR as well? #2782

**Closed** 2019-10-24 16:46 UTC
Labels: 4.6, P0, adaptive
