### ISSUE TITLE
Hitting max value of 64 when deserializing Bot state from CosmosDB using a sample Virtual Agent Bot.

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#6608] opened 2023-03-27 17:26 UTC
[PROBLEM DESCRIPTION]
<Describe the issue and be as specific as possible>

 

Bot setup – One bot created through Bot Framework SDK, which calls dialogs from bots created with composer.

o    Dev copies the code from the composer bot into the solution for the Bot Framework one.

·         Dev then reproduces the issue simply by running the bot on the Emulator, picking one of the desired composer bot dialogs, and then sets in motion a chain of clicks through Adaptive cards (where each option in the Adaptive card calls another dialog), thus leading to a large dialog stack.

·         At some point, the following error ensues: “The reader’s MaxDepth of 64 has been exceeded” – call stack is at the bottom of the email for brevity – bot name redacted.

 

Dev was initially on .NET Core 3.1 and Bot Builder 4.18.1 (Customer upgraded to both .NET 6.0 and Bot Builder SDK 4.19.2). Even then the issue was occurring.

Dev was also asked to follow the code change requested in Github issue #9458: [https://github.com/microsoft/BotFramework-Composer/issues/9458](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FBotFramework-Composer%2Fissues%2F9458&data=05%7C01%7CHugo.Durana%40microsoft.com%7C83201d8519104fe6a37408db2c6b9580%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638152612980451979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FBU1lPU4AL45M%2BJ46jmoKHVvxRnCGo5h0RVgrE3g7aQ%3D&reserved=0), which is the addition of the options.SerializerSettings.MaxDepth = HttpHelper.BotMessageSerializerSettings.MaxDepth; line to the ConfigureServices method.

 

 at Newtonsoft.Json.JsonReader.Push(JsonContainerType value)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Microsoft.Azure.Cosmos.CosmosJsonDotNetSerializer.FromStream[T](Stream stream)
   at Microsoft.Azure.Cosmos.CosmosJsonSerializerWrapper.FromStream[T](Stream stream)
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ToObjectpublic[T](ResponseMessage responseMessage)
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.<CreateItemResponse>b__8_0[T](ResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.CosmosResponseFactoryCore.ProcessMessage[T](ResponseMessage responseMessage, Func`2 createResponse)
   at Microsoft.Azure.Cosmos.ContainerCore.<UpsertItemAsync>d__57`1.MoveNext()
   at Microsoft.Azure.Cosmos.ClientContextCore.<RunWithDiagnosticsHelperAsync>d__38`1.MoveNext()
   at Microsoft.Bot.Builder.Azure.CosmosDbPartitionedStorage.<WriteAsync>d__10.MoveNext()
   at Microsoft.Bot.Builder.BotState.<SaveChangesAsync>d__5.MoveNext()
   at Microsoft.Bot.Builder.Dialogs.Memory.Scopes.BotStateMemoryScope`1.<SaveChangesAsync>d__4.MoveNext()
   at Microsoft.Bot.Builder.Dialogs.Memory.DialogStateManager.<SaveAllChangesAsync>d__33.MoveNext()
   at Microsoft.Bot.Builder.Dialogs.DialogExtensions.<InternalRunAsync>d__1.MoveNext()
   at Microsoft.Bot.Builder.Dialogs.DialogManager.<OnTurnAsync>d__30.MoveNext()

  ...

   at Microsoft.Bot.Solutions.Proactive.ProactiveStateMiddleWareTemplate`1.<OnTurnAsync>d__3.MoveNext()
   at Microsoft.Bot.Builder.SetSpeakMiddleware.<OnTurnAsync>d__3.MoveNext()
   at Microsoft.Bot.Solutions.Middleware.EventDebuggerMiddleware.<OnTurnAsync>d__0.MoveNext()
   at Microsoft.Bot.Solutions.Middleware.SetLocaleMiddleware.<OnTurnAsync>d__2.MoveNext()
   at Microsoft.Bot.Builder.ShowTypingMiddleware.<OnTurnAsync>d__4.MoveNext()
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.<OnTurnAsync>d__3.MoveNext()
   at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.<OnTurnAsync>d__7.MoveNext()
   at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.<OnTurnAsync>d__4.MoveNext()
   at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.<OnTurnAsync>d__0.MoveNext()
   at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext()
   at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__23.MoveNext()

[TROUBLESHOOTING STEPS]
During the initial session with the dev, we could clearly understand the following:

Using a negative number: NewtonSoft raises an ArgumentException with the message that value needs to be positive, which according to the code available on its repository, is correct.
Using any other number, or even null – we get the exception and error above.
 

Armed with this knowledge, the following question was posed: “Where, oh where, are we setting MaxDepth to 64 forcefully?”.

 

Given the call stack below, we were left with two places:

NewtonSoft repository (JsonReader class):        [https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonReader.cs#L332](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJamesNK%2FNewtonsoft.Json%2Fblob%2Fmaster%2FSrc%2FNewtonsoft.Json%2FJsonReader.cs%23L332&data=05%7C01%7CHugo.Durana%40microsoft.com%7C83201d8519104fe6a37408db2c6b9580%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638152612980451979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Pa5KdSQjptVM7AvjzAidPEpNFZLmlSkVOPy2C7yfor8%3D&reserved=0)
Azure CosmosDB repository ([https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L40](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-cosmos-dotnet-v3%2Fblob%2Fmaster%2FMicrosoft.Azure.Cosmos%2Fsrc%2FSerializer%2FCosmosJsonDotNetSerializer.cs%23L40&data=05%7C01%7CHugo.Durana%40microsoft.com%7C83201d8519104fe6a37408db2c6b9580%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638152612980451979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aTnp0Y%2FDLF8lXRjsp5mrNAAbGHyRxVKXwrEQzEtNcXc%3D&reserved=0))
 

These were the only places where we see the value 64 being set.

 

My suspicion at this moment is that the serializer settings that are added to NewtonSoft when running the ConfigureServices method do not appear to be trickled down to the right places, and thus this issue occurs.

 

There was also an email thread in the Bot Framework Discussions DL with the title regarding this exact case: [2302170030001489] - Question concerning "The reader’s MaxDepth of 64 has been exceeded" even though it is being set to values higher than that.

 

Had dev provide me with a sample bot where the issue is easily reproducible. In order to get this particular sample to work, I had to create both CosmosDB and BlobStorage accounts, then added all of the necessary details to the appSettings.json file, and finally use the Emulator (where I had to login using my App Id and App Password) to reproduce the issue which I can after a few clicks on options - there is no order to the clicks, the secret is to keep clicking on options as they appear and you will get the exception above soon.

**Comment by tracyboehrer** [comment] 2023-03-27 17:26
IcM:  https://portal.microsofticm.com/imp/v3/incidents/details/377776637/home

**Comment by tracyboehrer** [comment] 2023-03-27 17:26
@ceciliaavila Sharing bot code out-of-band

**Comment by ceciliaavila** [comment] 2023-03-29 14:03
Hi @tracyboehrer, we reproduced the error and noticed that the bot has the `Microsoft.Bot.Solutions` dependency. This package uses an old version of `Microsoft.Bot.Builder.Azure` (4.13.2), previous to the _newtonsoft_ upgrade (4.17.0).
The issue is solved by referencing the latest version of `Microsoft.Bot.Builder.Azure` (4.19.3) in the bot.
Let us know if you have any questions.
![image](https://user-images.githubusercontent.com/44245136/228563292-c053f6b5-9063-4dab-8973-7e4e931469f4.png)

**Comment by HugoDurana** [comment] 2023-03-29 15:16
@ceciliaavila, thank you for the feedback. this will be conveyed accordingly.

**Comment by ceciliaavila** [comment] 2023-04-20 15:02
Hi @tracyboehrer, this issue can be closed as it was a problem with the customer's configuration.
Thanks.

**Closed** 2023-04-20 15:03 UTC
Labels: bug
