### ISSUE TITLE
DialogContext is not corrected poped after EndOfDialog in children dialog

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3767] opened 2020-04-20 02:58 UTC
## Version
What package version of the SDK are you using.

241536bbf08d198c94ad4cd52955b4b8c0b89719

## Describe the bug
Give a clear and concise description of what the bug is.

See my branch https://github.com/xieofxie/botbuilder-dotnet/commit/b4465384ac113f66e67b315dfc2de95a8dc9b57b

![image](https://user-images.githubusercontent.com/2876650/79709794-b4caa800-82f5-11ea-834b-6830c1100cd4.png)

It seems when going back to LgBug dialog, the lg generator is still dialog2

Also TestBot.Json can't run due to no range.Path

## To Reproduce
1. clone my branch https://github.com/xieofxie/botbuilder-dotnet/tree/hualxie/lg_bug
2. start TestBot.Json
3. type 24
4. type test

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by boydc2014** [comment] 2020-04-20 04:13
Thanks @xieofxie can you share more about how you trigger this bug, how your LgBug.main and LgBug() is set? especially the generator field of your dialog.

And can you also create a seperate issue for TestBot.Json can't run without range.Path?

**Comment by xieofxie** [comment] 2020-04-20 04:14
OK, added steps

**Comment by boydc2014** [comment] 2020-04-20 04:15
@Danieladu can you help take a look at this one?

**Comment by xieofxie** [comment] 2020-04-20 04:23
Created here https://github.com/microsoft/botbuilder-dotnet/issues/3769.

**Comment by luhan2017** [comment] 2020-04-20 07:49
I did some investigation and found that this issue only happens when we added an "EndDialog" action in the sub-dialog. When call EndDialog, the dc is not correctly set.

**Comment by boydc2014** [comment] 2020-04-20 10:45
After more investigation, this appears to be DialogContext is not poped correctly after leaving children, the context is still pointing to children. 

Unassign hongyang, and put Tom and Vishwac on. 

@tomlm @vishwacsena i just label it P0 from my personal judgement, please triage again.

**Comment by Danieladu** [comment] 2020-04-20 12:38
I also made some investigation on this issue, found that when continuing the action, AdaptiveDialog would push the ScopedServices(language generator) into turn context, and at the end of ContinueActions, it would pop it up. But for some reason, the `SendActivity` action does not trigger the `ContinueActionsAsync` method, so, the current generator of turnContext is still the generator of the subdialog.

**Comment by vishwacsena** [comment] 2020-04-20 18:40
@Danieladu @boydc2014 I cannot repro this issue with the latest from master. 

Code based adaptive is [here][1]
Declarative adaptive is [here][2]. 

I do see a different error `No generator found for language en-us` after the end-dialog. Is that the manifestation of the issue? can you confirm that this is declarative only? Might help root cause the issue. 

[1]:https://github.com/microsoft/botbuilder-dotnet/tree/vishwac/R9-master-2/samples/TestBed/Dialogs/TestDialog
[2]:https://github.com/microsoft/botbuilder-dotnet/tree/vishwac/R9-master-2/samples/TestBed-Declarative/Dialogs/Repro3767

**Comment by boydc2014** [comment] 2020-04-21 00:47
> @Danieladu @boydc2014 I cannot repro this issue with the latest from master.
> 
> Code based adaptive is [here](https://github.com/microsoft/botbuilder-dotnet/tree/vishwac/R9-master-2/samples/TestBed/Dialogs/TestDialog)
> Declarative adaptive is [here](https://github.com/microsoft/botbuilder-dotnet/tree/vishwac/R9-master-2/samples/TestBed-Declarative/Dialogs/Repro3767).
> 
> I do see a different error `No generator found for language en-us` after the end-dialog. Is that the manifestation of the issue? can you confirm that this is declarative only? Might help root cause the issue.

Have you tried the user's branch: https://github.com/xieofxie/botbuilder-dotnet/tree/hualxie/lg_bug which can repro in me, Hongyang, and Lu's side. 

Hongyang did some inverstigation that, the DialogContext is not correctly poped up a certain setup of the actions, @Danieladu  can you detail on this, what's the condition (other than just EndOfDialog) to trigger this bug?

**Comment by Danieladu** [comment] 2020-04-21 02:13
> Have you tried the user's branch: https://github.com/xieofxie/botbuilder-dotnet/tree/hualxie/lg_bug which can repro in me, Hongyang, and Lu's side.
> 
> Hongyang did some inverstigation that, the DialogContext is not correctly poped up a certain setup of the actions, @Danieladu can you detail on this, what's the condition (other than just EndOfDialog) to trigger this bug?

@vishwacsena 
I have checked in the MVP re-pro of this issue on [issue3767](https://github.com/microsoft/botbuilder-dotnet/tree/issue3767) branch, link is here: https://github.com/microsoft/botbuilder-dotnet/tree/issue3767

Same re-pro step as hualiang's branch
1. checkout to issue3767 branch
2. start TestBot.Json
3. type 24
4. type test

**Comment by xieofxie** [comment] 2020-04-21 02:56
Hmm.. I will just write some observation here:
In this setup, the dialog stack is `main dialog <- begin dialog <- sub dialog <- end dialog`
In end dialog, it will end its parent dialog i.e. sub dialog and it will continue in begin dialog.
However, it will only pop lg in the end of continue of sub dialog.
So in the action after begin dialog, it will use lg from sub dialog.

One possible fix is end dialog will end itself and set a special flag. Then in sub dialog when it continues, it will end itself. However, then adaptive dialog mustn't be ended via end dialog function as it will not pop lg

**Comment by xieofxie** [comment] 2020-04-22 02:14
Another thought is popping lg in end dialog function.
Although it will be popped again in the end of continue, but it will only go back to continue function when the turn is ended and the continue will break any way. So pop again is no effect I guess?

**Comment by tomlm** [comment] 2020-04-22 02:51
this is a real bug. Working on fix

**Closed** 2020-04-24 07:49 UTC
Labels: Adaptive, P0, R9
