### ISSUE TITLE
Review SchemaMergeTests

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#4492] opened 2020-08-20 18:21 UTC
These tests might be better run nightly, or in a functional tests pipeline:

https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs

**Comment by mrivera-ms** [comment] 2020-09-17 17:29
@EricDahlvang , please document what the issues are and assign it.

**Comment by EricDahlvang** [comment] 2020-09-17 17:31
- test is running cmd.exe (this does not seem like a good practice for a ci pipeline test of this product)

- this test seems fragile

- this might be better in the cli library

- can we rewrite this test, or move it to a nightly/functional test pipeline?

**Comment by EricDahlvang** [comment] 2020-09-17 17:36
@chrimc62  some of us were reviewing this, and wondering if you would please address the issues raised above.

**Comment by chrimc62** [comment] 2020-09-17 23:50
The issue is that our schemas are defined and versioned with the SDK code.  Prior to having this check, bad schemas would often get checked-in and not be found until someone used them much later.  We could rely on developers installing the latest bf tool and manually build the schemas, but that requires a level of effort that has been problematic in the past.  With the current test we always install the latest bf tool as part of the tests and on windows we verify that all of the schemas are valid, pass verifications and can pass all the tests written against them.  We cannot put this in the CLI repo because the schemas are defined in the SDK.  We can't run the merge code directly because it is in another repo and written in typescript.  I think these tests are important and belong in this repo.

**Comment by EricDahlvang** [comment] 2020-09-19 03:12
@mrivera-ms do we close this?

I have no great suggestions for how to rearchitect these tests, and it looks like Chris addressed everything.

**Comment by chrimc62** [comment] 2020-09-28 23:39
I'm going to close this.  Please reopen if my arguments didn't sway you.

**Closed by chrimc62** 2020-09-28 23:39 UTC
Labels: Area: SDK, P0, Size: M, team-agility
