### ISSUE TITLE
High Latency (2-4 seconds) bot response time using DirectLine SDK with Xamarin.

### ISSUE THREAD

**Issue by jawand** [Microsoft/botbuilder-dotnet#1254] opened 2018-12-20 09:41 UTC
## Version
DirectLine 3.0.2 for .NET 

## Describe the bug
High Latency (2-4 seconds) bot response time using DirectLine SDK with Xamarin. We have created a Bot with LUIS which works fine with emulator for local and prod. But, when we use DirectLine to connect with Bot from a Xamarin.forms mobile application. It takes about 4-5 seconds to create a conversation using this (`BotConversation = await Client.Conversations.StartConversationAsync().ConfigureAwait(false);`) line of code.

and when we try to send a message by creating a Message Type Activity it takes about 2-3 seconds.
using this code.

` Activity userMessage = new Activity()`
`{`
	`From = new ChannelAccount(userId, userName),`
	`Text = message,`
	`Type = ActivityTypes.Message,`
	`Properties = new JObject(new JProperty("TenantCode", tenantCode),`
						`new JProperty("SiteCode", "1")),`
`};`
`await Client.Conversations.PostActivityAsync(BotConversation.ConversationId, userMessage).ConfigureAwait(false);`

## Expected behavior
It should not take this much time. response time should be less then 1 second. 

## Additional context

- Currently This Bot Web App is hosted on Azure platform with Web App in `Central Canada` and the LUIS is hosted in `West US` region.
- I am currently testing it from Pune, India. 
- After opening this issue on [stackoverflow ](https://stackoverflow.com/questions/53855384/high-latency-2-4-seconds-bot-response-time-using-directline-sdk-with-xamarin) I have deployed my Bot application in `Central India` which is nearest to me. But no effect. Same results.
- Then I created a `Echo Bot` application and in `Central India` and again same results.
- BTW i have a good internet connection.
[bug]

**Comment by EricDahlvang** [comment] 2018-12-20 18:17
Closing as a duplicate of https://stackoverflow.com/questions/53855384/high-latency-2-4-seconds-bot-response-time-using-directline-sdk-with-xamarin

**Closed by EricDahlvang** 2018-12-20 18:17 UTC
