### ISSUE TITLE
[Adaptive] do we have a while loop action?

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4663] opened 2020-09-16 09:12 UTC
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

It seems we only have ForEach for loop.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by boydc2014** [comment] 2020-10-08 00:23
Put this into backlog before we have a process to take new actions

**Comment by xieofxie** [comment] 2020-10-09 04:22
Current alternative: use ForEach on a non-empty array and change index to -1 in the loop.

**Comment by mrivera-ms** [comment] 2020-11-05 17:36
Closing as duplicate of https://github.com/microsoft/botbuilder-dotnet/issues/4862

**Closed by mrivera-ms** 2020-11-05 17:36 UTC
Labels: Area: Adaptive, backlog, feature-request, needs-triage
