### ISSUE TITLE
cannot recognize space

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#2174] opened 2019-07-03 03:26 UTC
**Is your feature request related to a problem? Please describe.**
Space will result in empty Intents in Microsoft.Bot.Builder.RecognizerResult. However, you can't test it on https://www.luis.ai.

**Describe the solution you'd like**
It should return None intent.

**Additional context**
Maybe it is a LUIS bug..

[enhancement]

**Comment by Zerryth** [comment] 2019-08-16 20:57
@xieofxie it does look like when testing the LUIS endpoint directly, you can see that sending a space returns essentially an empty result

`https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?verbose=true&timezoneOffset=-360&subscription-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&q=%20`

![image](https://user-images.githubusercontent.com/35248895/63197544-f8fdfe00-c02c-11e9-965b-81f6fe8dea53.png)

(Note that for the query I send in `%20` for URL encoded space)
___
Compare this to something that would return a `None` intent

`https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?verbose=true&timezoneOffset=-360&subscription-key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&q=;laksjf;askdl;asdkfa;skdfj`

![image](https://user-images.githubusercontent.com/35248895/63197716-63af3980-c02d-11e9-900b-3ab39cacf5d2.png)

___

> Space will result in empty Intents in Microsoft.Bot.Builder.RecognizerResult. 

So with the above being said, you can test it, and it looks like the SDK reflects what the LUIS API gives us

I'll ask the LUIS team to see if sending null intents back is the intention when sending a space on the API's end however

**Comment by Zerryth** [comment] 2019-08-16 22:31
@xieofxie ok, I got a response from the LUIS team directly, and the confirmed that the result with empty intent and entities arrays is intended behavior when sending a query with only space

Resolving this issue, as the SDK reflects what the LUIS API intends

**Closed by Zerryth** 2019-08-16 22:31 UTC
Labels: bug

**Comment by xieofxie** [comment] 2019-08-19 06:01
Hi, @Zerryth thanks for the investigation. But when I look at the [code](https://github.com/microsoft/botbuilder-dotnet/blob/a952922a48a3041df464cecf46cc6cb52847e502/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs#L339), it is a bit different.

It returns string.Empty now and it could not be converted to any enum Intent. One could use a TypeConverter in Newtonsoft.Json to solve this but it is somehow very complex.

I would suggest to return Intents = null here to follow the LUIS then one could use JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore } to handle this.

**Comment by Zerryth** [comment] 2019-08-19 15:49
Hi @xieofxie. I see what you mean. 
![image](https://user-images.githubusercontent.com/35248895/63279685-49a86d80-c25e-11e9-9142-964868bbd77c.png)
And LUIS API actually returns `[]` for `Intents`, not `null`, however in any case...
Unfortunately we cannot change this behavior--at least not right now in the SDK, as it would be a breaking change for those who've already built upon this. If this were to happen, it would need to be in the next version version (as in v5).

**Comment by xieofxie** [comment] 2019-08-20 02:35
@Zerryth Yeah.. my mistake. Then we will keep an eye on this. Thanks for the information~
