### ISSUE TITLE
Unable to Add skill to Power Automate SDK 4.10.3

### ISSUE THREAD

**Issue by Frazerunige** [microsoft/botbuilder-dotnet#4796] opened 2020-10-14 13:49 UTC
## Version
4.10.3

## Describe the bug
Unable to add Skill to powerautomate (microsoft chatbot)

## To Reproduce
1. Go to powerautomate
2. Click on skills --> add skill
3. paste the link of the manifest of your web App bot developed with bot framework (same Tenant)
4. The message is always: "This skill has not allow listed your bot."

## Expected behavior
With versione 4.10.2 the skill is correctly added to chatbot

**Comment by dmvtech** [comment] 2020-10-14 18:58
In your skill `appsettings.json` or `.env`, what do you have configured for `AllowedCallers`? See more info [here](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs#application-configuration).

**Comment by Frazerunige** [comment] 2020-10-16 08:08
Yes sure, i've tried to set AllowCallers in many ways:
- Empty Array
 - Array with only the ID of Powerautomate 
 - Array like ["*"]

> In your skill `appsettings.json` or `.env`, what do you have configured for `AllowedCallers`? See more info [here](https://docs.microsoft.com/en-us/azure/bot-service/skill-implement-skill?view=azure-bot-service-4.0&tabs=cs#application-configuration).

**Comment by dmvtech** [comment] 2020-10-19 16:36
Thanks. I'm checking to see if I can get it working myself.

**Comment by dmvtech** [comment] 2020-10-31 02:16
hi @Frazerunige My apologies. I'm having trouble figuring out the powerautomate side of things. Would you mind giving me a few more steps on how to reproduce (to the point where I can add the skill)?

**Comment by dmvtech** [comment] 2020-11-04 19:40
Hi @Frazerunige Just checking in. Can you help me get to a point to reproduce the issue you are having?

**Comment by dmvtech** [comment] 2020-11-10 16:46
Hi @Frazerunige I am closing this as I am unable to complete the setup to get this working/reproduced. Please let me know the complete steps if you still need assistance and I will reopen this.

**Comment by Pruzzo** [comment] 2020-11-11 12:44
To reproduce this bug just develop a bot with bot framework using the 4.10.3 version of the SDK, than upload it somewhere (in my case bot services on azure) than provide the manifest link to the add skill page in powerautomate chatbot.
The page will always give back an error. The manifest is correcly written and bot has in the appsettings the allowedcallers, but the page always give an error

To make it work i've just downgraded the sdk version 4.10.2 and it works fine.
Let me know if is clearer now

**Comment by Frazerunige** [comment] 2020-11-11 12:48
To reproduce this bug just develop a bot with bot framework using the 4.10.3 version of the SDK, than upload it somewhere (in my case bot services on azure) than provide the manifest link to the add skill page in powerautomate chatbot.
The page will always give back an error. The manifest is correcly written and bot has in the appsettings the allowedcallers, but the page always give an error

To make it work i've just downgraded the sdk version 4.10.2 and it works fine.
Let me know if is clearer now

**Comment by dmvtech** [comment] 2020-11-11 16:40
>Let me know if is clearer now

Unfortunately no. 

> than provide the manifest link to the add skill page in powerautomate chatbot.

_This_ is the part I do not understand. I have no experience with powerautomate. You need to give me more specific steps.

**Comment by Frazerunige** [comment] 2020-11-11 18:06
https://youtu.be/qvT89io3Gx0

Hope this video will help u to understand.
The first part i try to add the skill in PVA while the SDK is in 4.10.3 version.

**Comment by tonyanziano** [comment] 2020-12-11 20:36
@dmvtech given the above video, can you comment further? Or do you need more information.

**Comment by harika5** [comment] 2020-12-31 06:56
I tried downgrading the sdk version to 4.10.2 but I still get the same error "This skill has not allow listed your bot" when I try to add my skill to the PVA. 
I have already included the PVA ID in my AllowedCallers as well.

**Comment by dmvtech** [comment] 2021-01-11 22:05
hi @Frazerunige Apologies for the delay. Are you still experiencing this issue? We are investigating to see if we can get any backend information or steps on how to further troubleshoot this.

**Comment by dmvtech** [comment] 2021-01-11 22:17
@harika5 Are you still having issues as well?

**Comment by dmvtech** [comment] 2021-01-19 19:59
Closing due to inactivity. If this issue still persists, please let us know so that we can retrieve more information to investigate.

**Closed** 2021-01-19 20:00 UTC
Labels: Bot Services, Support, bug, customer-replied-to, customer-reported, needs-author-feedback

**Comment by v-susgupta** [comment] 2021-07-07 20:50
Hello, I am also facing the same issue. Is there any other solution? Thanks
