### ISSUE TITLE
Slack Adapter Fails on rendering context block

### ISSUE THREAD

**Issue by Anshul21** [microsoft/botbuilder-dotnet#3593] opened 2020-03-18 20:06 UTC
## Version
v 4.8

## Describe the bug
I am using the SlackAdapter ( .NET). It's is not able to deserialize the block Array, if one of the blocks is a "context".
Following is the error message 

Newtonsoft.Json.JsonSerializationException: Error converting value "Location: *Dogpatch*" to type 'SlackAPI.Text'. Path '[0].elements[1].text', line 12, position 38. ---> System.ArgumentException: Could not cast or convert from System.String to SlackAPI.Text.

## To Reproduce
1. checkout the https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/60.slack-adapter
2. follow the steps to connect slack channel to bot
3. add a context block in https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/60.slack-adapter/Resources/InteractiveMessage.json

## Expected behavior
Bot should be able to deserialize context block
## Additional context

[bug]

**Comment by v-kydela** [comment] 2020-03-19 20:15
Hello @Anshul21 

It looks like the current Slack adapter sample is referencing the 4.8 rc2 preview of the Slack adapter package, and that preview isn't available on NuGet so I cannot build the sample unless I configure Visual Studio to use MyGet. Are you using MyGet or are you using an earlier version of the sample?

**Comment by Anshul21** [comment] 2020-03-19 20:34
i am referencing to https://www.nuget.org/packages/Microsoft.Bot.Builder.Adapters.Slack/  version 4.8.0-rc0

**Comment by v-kydela** [comment] 2020-03-19 21:21
@Anshul21 - Okay but what version of the sample are you using? Do you have this commit? 9ac77d5f43c6316df440442843ba5e59381d551c

**Comment by Anshul21** [comment] 2020-03-19 22:22
@v-kydela pulled the latest code from repo for the sample. I do the commit # 9ac77d5f43c6316df440442843ba5e59381d551c in git log. It's still not able to process context. I used a simple block [
		```
{
			"type": "context",
			"elements": [
				{
					"type": "mrkdwn",
					"text": "Last updated: Jan 1, 2019"
				}
			]
		}
	]
```
but it still fails with `Newtonsoft.Json.JsonSerializationException: Error converting value "Last updated: Jan 1, 2019" to type 'SlackAPI.Text'. Path '[0].elements[0].text', line 7, position 43.`

**Comment by v-kydela** [comment] 2020-03-19 22:23
@Anshul21 - I can reproduce the issue using the [context block sample](https://api.slack.com/reference/block-kit/blocks#context), and it's looking like a problem with the Slack API package which you can report issues about here: https://github.com/Inumedia/SlackAPI

You can tell them that blocks cannot be deserialized using Newtonsoft and that they need to implement a custom JSON converter.

I tried making the sample work by deserializing the JSON as a JArray, but that doesn't work because [the Slack adapter is trying to cast it](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs#L57) as a `List<Block>` before sending it to Slack:

```c#
message.Blocks = (List<Block>)att.Content;
```

@garypretty - At minimum we should allow `NewSlackMessage.Blocks` to be `IEnumerable<IBlock>` because blocks like `ContextBlock` implement `IBlock` and don't derive from `Block`, but that still wouldn't fix our deserialization problem. I can see three possibilities on our side if the Slack API package isn't fixed:

1. We could have `NewSlackMessage.Blocks` accept `IEnumerable` or `IEnumerable<object>` so that a JArray would work
2. We could create our own JSON converter and expose that as part of the Slack adapter package for the bot to use
3. Since the Slack adapter just reserializes the blocks anyway, we could allow the bot to send the blocks through the adapter as a string

**Comment by Anshul21** [comment] 2020-03-19 22:34
opened the bug for SlackAPI team https://github.com/Inumedia/SlackAPI/issues/228 
@v-kydela @garypretty

**Comment by v-kydela** [comment] 2020-03-19 23:12
To clarify further, the issue occurs when the context block contains a text object. The JSON deserializer interprets each element in the block as an `Element` object, and that expects the text property to be a `Text` object. If the element is itself a `Text` object then its text property is a string.

The `ContextBlock` class has `IElement` elements which can be `Element` objects or `Text` objects, but in order to potentially deserialize blocks as context blocks we'd have to use `IBlock` and we can't deserialize interfaces. I suspect that means we wouldn't be able to deserialize the `IElement` elements in a context block anyway.

**Comment by cleemullins** [comment] 2020-03-30 18:59
@v-kydela, @garypretty  What should we do with this? If it's an open bug in Slack, we should close this out now that they're linked.

**Comment by v-kydela** [comment] 2020-03-30 19:59
@cleemullins - It's not a bug in Slack. The bug that the customer opened is in the Slack API package that our code is using, and the issue has remained unread for 11 days. It looks like a personal repo that's run by one person and I don't know that we can count on anything getting fixed unless we fix it ourselves. However, the author does provide some [contact information](https://github.com/Inumedia/SlackAPI#getting-in-touch) if one of us would like to get in touch.

I also outlined some work that should be done on our end regardless of whether or how that Slack API bug gets fixed:

> @garypretty - At minimum we should allow `NewSlackMessage.Blocks` to be `IEnumerable<IBlock>` because blocks like `ContextBlock` implement `IBlock` and don't derive from `Block`, but that still wouldn't fix our deserialization problem.

And also some work that we could do on our end if we assume the bug will not get fixed:

> I can see three possibilities on our side if the Slack API package isn't fixed:
> 
> 1. We could have `NewSlackMessage.Blocks` accept `IEnumerable` or `IEnumerable<object>` so that a JArray would work
> 2. We could create our own JSON converter and expose that as part of the Slack adapter package for the bot to use
> 3. Since the Slack adapter just reserializes the blocks anyway, we could allow the bot to send the blocks through the adapter as a string

**Comment by tonyanziano** [comment] 2020-04-20 18:04
@garypretty Can you provide an update on this issue? Thanks

**Comment by cleemullins** [comment] 2020-05-04 17:47
I've added this to our R10 release, which should land around the end of summer. This is a bit complex, as it's across dependency chains...

**Comment by garypretty** [comment] 2020-05-04 17:51
As @cleemullins has said, we will implement a workaround in our SDK adapter, given that there looks to be no movement on the underlying Slack SDK side.

**Comment by garypretty** [comment] 2020-06-15 15:50
There is now an open PR (just awaiting some resolution of failing tests) which implements some changes to the Slack adapter, including one that will address this issue - we have now changed the Blocks property to be a collection of object. You can see the PR at https://github.com/microsoft/botbuilder-dotnet/pull/4046.

I am going to close out this issue, but once the PR has been merged, this will be available in the nightly builds.

**Closed by garypretty** 2020-06-15 15:50 UTC
Labels: BF Customer Ask, Bot Services, R10, customer-replied-to, customer-reported
