### ISSUE TITLE
[DirectLine] Attachment ContentUrl contains placeholder URL after uploading image

### ISSUE THREAD

**Issue by RootOfAllEval** [microsoft/botbuilder-dotnet#3874] opened 2020-05-06 00:37 UTC
Repro Steps:

1. Upload image through DirectLine channel using URL: 
`https://directline.botframework.com/v3/directline/conversations/{CONVERSATION_ID}/upload?userId={USER_ID}`

2. Verify bot is able to receive attachment and download file from generated URL

3. User receives activity from DirectLine channel containing uploaded attachment, but attachment ContentUrl contains 
`"https://docs.botframework.com/static/devportal/client/images/bot-framework-default-placeholder.png"` instead of URL to image.

![image](https://user-images.githubusercontent.com/5480993/81128574-8bbe3000-8f0f-11ea-9064-55fae3af90aa.png)

The URL of the image is only seen by the bot, but any historical view of the activities will have it replaced with a placeholder URL. Is this by design? I assumed the URLs of attachments would be visible to users as well.

**Comment by dmvtech** [comment] 2020-05-07 18:29
@RootOfAllEval I'm not quite sure if this is by design or not. I'm looking into that and will let you know what I find.

**Comment by dmvtech** [comment] 2020-05-11 20:35
This is by design. I'll see if I can get some more info for you.

**Comment by dmvtech** [comment] 2020-05-11 23:01
This design is due to security.

To further explain; someone could upload an attachment with malicious content, have it echoed back to them from a URL that had `microsoft.com` in the URL, then copy THAT URL and share it with someone and make them think the malicious content was trustworthy because it had `microsoft.com` in the URL.

I am closing this as resolved, but please let us know if you have further questions.

**Closed by dmvtech** 2020-05-11 23:01 UTC
Labels: Bot Services, customer-replied-to, customer-reported
