### ISSUE TITLE
luisResult was always null when using LuisRecognizerOptionsV3

### ISSUE THREAD

**Issue by csnarain** [microsoft/botbuilder-dotnet#3520] opened 2020-03-09 05:51 UTC
See this sample code below. Here luisResult return null when using LuisRecognizerOptionsV3, however works fine when using LuisRecognizerOptionsV2.

```
var result = await _botServices.Dispatch.RecognizeAsync(stepContext.Context, cancellationToken);
 var luisResult = result.Properties["luisResult"] as LuisResult;
 var entities = luisResult.Entities;
 foreach (var entity in entities)
 {
   if (Common.BugTypes.Any(s => s.Equals(entity.Entity, 
   StringComparison.OrdinalIgnoreCase)))
   {
     await stepContext.Context.SendActivityAsync(
     MessageFactory.Text(String.Format("Yes! {0} is a Bug Type!", 
     entity.Entity)), cancellationToken);
   }
   else
   {
     await stepContext.Context.SendActivityAsync(
     MessageFactory.Text(String.Format("No! {0} is not a Bug Type!", entity.Entity)), cancellationToken);
   }
 }

return await stepContext.NextAsync(null, cancellationToken);

Here is how I'm building my recognizer

var luisApplication = new LuisApplication(
                configuration["LuisAppId"],
                configuration["LuisAPIKey"],
                $"https://{configuration["LuisAPIHostName"]}.api.cognitive.microsoft.com"
                );
            var recognizerOptions = new LuisRecognizerOptionsV3(luisApplication)
            {
                IncludeAPIResults = true,
                PredictionOptions = new Microsoft.Bot.Builder.AI.LuisV3.LuisPredictionOptions()
                {
                    IncludeInstanceData = true,
                    IncludeAllIntents = true
                }
            };
            Dispatch=new LuisRecognizer(recognizerOptions);

....

var result = await _botServices.Dispatch.RecognizeAsync(stepContext.Context, cancellationToken);
            var luisResult = result.Properties["luisResult"] as LuisResult;
```

**Comment by dmvtech** [comment] 2020-03-10 02:02
@csnarain Taking a look. Checking to see if I can repro/confirm.

**Comment by csnarain** [comment] 2020-03-16 06:16
@dmvtech - any update on this? did you manage to reproduce this?

**Comment by munozemilio** [comment] 2020-03-16 16:53
Hello @csnarain, I will be working on this today. I will get back to you ASAP on this.

**Comment by munozemilio** [comment] 2020-03-17 05:47
@csnarin, could you please share the nuget version and name of the LuisResult class you are casting to?

**Comment by csnarain** [comment] 2020-03-17 13:59
@munozemilio - I use the latest version 4.7.2

**Comment by cleemullins** [comment] 2020-03-30 19:02
@munozemilio Any updates on this? IF we can't reproduce, should we close this out?

**Comment by munozemilio** [comment] 2020-03-31 05:06
@csnarain the issue seems to be the LuisResult class you are casting too. If it is the same as the sample, then that one corresponds to the LuisResult of the V2 runtime. I will investigate which package is the one for the V3

**Comment by munozemilio** [comment] 2020-04-01 19:45
@csnarain the way you can cast the result is something like this:
```
                    var app = JsonConvert.DeserializeObject<PredictionResponse>(JsonConvert.SerializeObject(recognizerResult.Properties["luisResult"], new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
```
using [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.language.luis.runtime.models.predictionresponse?view=azure-dotnet) class from the Azure SDK

**Closed by munozemilio** 2020-04-01 19:45 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by icpmtech** [comment] 2021-01-18 09:37
Hi i have the same problem and fix it with the next sample of code here, i use the @munozemilio solution integrate with my code and works:
 // Retrieve LUIS result
   var luisResult_ = await _botServices.DispatchDetails.RecognizeAsync<DemoVirtualAssistant9Be3>(turnContext, cancellationToken);
            var result = JsonConvert.DeserializeObject<PredictionResponse>(JsonConvert.SerializeObject(luisResult.Properties["luisResult"], new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));

            var topIntent = result.Prediction.Intents[result.Prediction.TopIntent];
