### ISSUE TITLE
Bot throws error when new version has been deployed

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#5007] opened 2020-11-27 15:29 UTC
In existing conversations with bots, when a new version of the bot is deployed an error is thrown when the user continues the conversation. 

![image](https://user-images.githubusercontent.com/49873947/100464224-86078200-30cd-11eb-8764-3eef5147076c.png)

When this situation happens the bot should have a failback, as uploading a new version is part of continuous improvement and conversations can be long lasting, like in Teams for example.

**Comment by dmvtech** [comment] 2020-11-30 22:22
Hi @cxbuilders Can you give more info on exactly what are you updating to a new version? Is this just the .dialog/.lu files? Or the runtime (or perhaps just the botbuilder SDK version inside your runtime)?

**Comment by cxbuilders** [comment] 2020-11-30 23:14
@dmvtech only dialog changes

**Comment by dmvtech** [comment] 2020-12-03 01:28
I was able to reproduce easily. 


Just by changing:
```
{
"$kind": "Microsoft.SendActivity",
"$designer": {
"id": "5Q1ckx"
},
"activity": "${SendActivity_5Q1ckx()}"
},
```
```
# SendActivity_5Q1ckx()
- You like to eat ${dialog.food}
```

To:
```
{
"$kind": "Microsoft.SendActivity",
"$designer": {
"id": "5Q1ckx"
},
"activity": "${SendActivity_Food()}"
},
```
```
# SendActivity_Food()
- You like to eat ${dialog.food}
```

```
DialogContext.EndDialogAsync(): Can't resume previous dialog. A dialog with an id of 'ActionScope[TextInput,SendActivity(${SendActivity_5Q1ckx()}),T...CNNaW40WKHjE6wI/r3obAsbFDJTY3V/cV77F1/J9d60=]' wasn't found.
```

@hcyang Can I get your input here?

**Comment by cosmicshuai** [comment] 2020-12-10 07:55
Hi, @dmvtech, I am looking into this issue. Trying to reproduce it. 
Can you share some information about how to reproduce this issue.
My steps:
1. Create a new bot in Composer
2. Start the bot
3. Chat with the bot in Emulator
4. Edit the dialog file and LG file in VSCode, then save the changes
5. continue to chat with the bot || restart the bot and continue to chat with the bot
However I didn't see the error message. Could you provide some details of the steps? Thanks a lot!

**Comment by dmvtech** [comment] 2020-12-10 18:34
Hey @cosmicshuai 

The thing you need to add is a persistent state store.

So something like:

1. Create a new bot in Composer
2. Set state store to something persistent like cosmosDB or blob storage (I did cosmos). Local emulator should be fine.
3. Use bot memory/state to store some values (say something like `user.favoritecolor` and `user.favoriteshape`)
4. Start the bot
5. Chat with the bot in Emulator
6. Do not finish a dialog (say that the dialog asks for favorite color, then favorite shape. Just stop conversation after answering favorite color)
7. Edit the dialog file and LG file in VSCode, then save the changes
8. continue to chat with the bot || restart the bot and continue to chat with the bot

**Comment by boydc2014** [comment] 2020-12-14 06:48
> Hi, @dmvtech, I am looking into this issue. Trying to reproduce it.
> Can you share some information about how to reproduce this issue.
> My steps:
> 
> 1. Create a new bot in Composer
> 2. Start the bot
> 3. Chat with the bot in Emulator
> 4. Edit the dialog file and LG file in VSCode, then save the changes
> 5. continue to chat with the bot || restart the bot and continue to chat with the bot
> 
> However I didn't see the error message. Could you provide some details of the steps? Thanks a lot!

you should try to re-deploy the bot. Local editing in VS/VSCode won't simulate the environment, because your process is probably still the same. A re-deploy at least will create new process for it.

**Comment by cxbuilders** [comment] 2021-01-05 19:47
@gabog Why is this closed?

**Comment by gabog** [comment] 2021-01-05 19:56
Hi @cxbuilders, I thought that @boydc2014 was addressing your issue, I will reopen.

Can you provide more a response to @boydc2014 suggestion so he can continue to assist?

Thanks

**Comment by cxbuilders** [comment] 2021-01-05 20:22
@gabog not sure what I need to add? Seems @boydc2014 knows about the issue. Otherwise let me know what needs to be added?

**Comment by boydc2014** [comment] 2021-01-08 07:55
> @gabog not sure what I need to add? Seems @boydc2014 knows about the issue. Otherwise let me know what needs to be added?

@cosmicshuai was assigned to look at this, he should be back on this soon

**Comment by cosmicshuai** [comment] 2021-01-11 02:47
I investigated this issue and found the reason caused it. Currentlt, I am working on a fix to ensure the conversation can be long lasting.

**Comment by a-b-r-o-w-n** [comment] 2021-01-25 19:15
@cosmicshuai What is the status of #5106?

**Comment by cosmicshuai** [comment] 2021-01-26 15:38
@a-b-r-o-w-n 
I have a draft PR to solve this. However, I need to discuss with SDK team about the default behavior of resuming the dialog once it encounter this situation.

**Comment by Virtual-Josh** [comment] 2021-02-08 19:37
@cosmicshuai,

Can you drive this to completion?

**Comment by cosmicshuai** [comment] 2021-03-16 07:12
Hi, @dmvtech, could you try reproduce this using the latest Composer client (1.3.1)? I was able to reproduce this error before.
I am trying to write a unit test for my fix PR. However, I can't reproduce it now. Could you help verify does this error still exists?

**Comment by cleemullins** [comment] 2021-06-16 21:58
The core issue here is that the version may be encoded in the durable state that's serialized to the state store. @tracyboehrer Can you take a look at this? @johnataylor and @Stevenic both have context on different flavors of this issue.

**Comment by tracyboehrer** [comment] 2021-06-22 19:35
Pushing to R15.  This will require some more analysis.  I will schedule a meeting with the appropriate people so we can hash this out.

**Closed** 2022-02-14 18:30 UTC
Labels: P1, customer-reported, Bot Services, customer-replied-to, ExemptFromDailyDRIReport, Area: Adaptive

**Comment by SanKumar0632** [comment] 2024-06-19 10:14
I am facing this same issue, can someone explain what's the root cause of it and if it's by design at least mention what precautions should we take to eliminate this error popping up in the bot?

@gabog

**Comment by jamesemann** [comment] 2024-06-19 10:27
@SanKumar0632  you can reset the conversation state and have the conversation restart on error. To handle the error you can subclass the adapter and implement the onturnerror event

**Comment by SanKumar0632** [comment] 2024-06-19 10:31
> @SanKumar0632 you can reset the conversation state and have the conversation restart on error. To handle the error you can subclass the adapter and implement the onturnerror event

But that why does that error occur at the first place as I don't have any bugs or logical flaws in the new version of the bot deployed?

**Comment by jamesemann** [comment] 2024-06-19 10:33
I’m guessing it’s because the conversation design has changed, and it’s trying to resume from an action (probably a prompt) that doesn’t exist

**Comment by SanKumar0632** [comment] 2024-06-19 10:37
No, there was no change in the dialog in which this error was thrown, there were changes elsewhere @jamesemann.

**Comment by jamesemann** [comment] 2024-06-19 10:41
> No, there was no change in the dialog in which this error was thrown, there were changes elsewhere @jamesemann.

Ok, I’m not sure exactly what causes your specific issue. Just sharing something that works for me, there are a lot of situations where state is serialised so in my experience it’s best to assume that it will fail in a long lived conversation (e.g. teams chat) so design your bot so it can restart gracefully.

**Comment by SanKumar0632** [comment] 2024-06-19 10:44
The state management is achieved by persistent storage(cosmos db), so if the state remains persistent, is it the expected behavior for long lived conversations?

**Comment by tracyboehrer** [comment] 2024-06-19 13:05
The suggestion from @jamesemann is the recommended solution.  This is happening because Composer changes the dialog id's when saving after a change.  The state just doesn't match the dialogs anymore, and the dialog stack has no way to reconcile that. While perhaps not the most elegant solution, it is resilient in all cases of state issues.  i.e., Start the conversation over.
