### ISSUE TITLE
Update the LUIS V3 recognizer to support latest endpoint

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2853] opened 2019-10-24 23:31 UTC
There have been a few changes to the V3 LUIS endpoint API, in particular for geography.  We need to make sure the SDK code supports those changes.  We also need to make sure that we support multiple level intents that come back from LUIS dispatch models.  To do this we probably need to extend IntentScore to explicitly support children intents.  We also need to make sure LUISGen is updated as well.  This came out when Lauren tried to use dispatch with LUISGen.
[enhancement]

**Comment by cleemullins** [comment] 2019-11-15 21:39
Currently being worked by @munozemilio.

**Comment by cleemullins** [comment] 2019-11-15 22:06
Duplicate of #2111

**Closed by cleemullins** 2019-11-15 22:06 UTC
Labels: P0, R7
