### ISSUE TITLE
AttachmentPrompts within a Waterfall dialog err out

### ISSUE THREAD

**Issue by rob-derosa** [microsoft/botbuilder-dotnet#2456] opened 2019-08-29 17:16 UTC
## Version
4.5.1

## Describe the bug
When an AttachmentPrompt is added as a step in a waterfall dialog, an error is thrown

## To Reproduce
I modified the multi-turn .NET sample to add a middle step of AttachmentPrompt [gist here](https://gist.github.com/rob-derosa/f46b4becab6f5f463a8602bc5c0d32b5)
After selecting one of the adaptive cards, an error will be thrown:

`Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter:Error: Exception caught : Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path 'DialogState.DialogStack.$values[0].State.dialogs.DialogStack.$values[0].State.options.Prompt.attachments.$values[0].content.body'.`

## Expected behavior
No error should be thrown

[bug]

**Comment by v-kydela** [comment] 2019-08-30 16:44
@rob-derosa - To me that looks like the problem is related to Adaptive Cards and not attachment prompts. It looks like you modified the sample to use Adaptive Cards. There is a [longstanding bug](https://github.com/microsoft/AdaptiveCards/issues/2148) in the AdaptiveCards package that throws errors when the cards are serialized with type information, as they are in the Bot Builder dialog stack. You have to convert the card to a non-AdaptiveCard type like a JObject:

```c#
Content = JObject.FromObject(result.Card)
```

**Comment by v-kydela** [comment] 2019-09-04 15:56
Closing as not a real bug

**Closed by v-kydela** 2019-09-04 15:56 UTC

**Comment by PriyankTUV** [comment] 2019-10-03 08:37
> Closing as not a real bug

Solution Worked for me ...

public static Attachment ToAdaptiveCard(this AdaptiveCard card)
{
var adaptiveCardJson = JsonConvert.SerializeObject(card);
return new Attachment()
{
ContentType = "application/vnd.microsoft.card.adaptive",
Content = JsonConvert.DeserializeObject(adaptiveCardJson),
};
}

**Comment by hansmbakker** [comment] 2020-05-11 15:13
@v-kydela  Can you please reopen this?

This is a bug, because the card gets stored as conversation history the bot state.

When the bot tries to fetch the conversation state again, the JSON containing the adaptive cards will be part of the `previousBotResponses` property of the state.

When trying to load that, the bot automatically uses IgnoreEmptyItemsConverter which assumes an array for `previousBotResponse.$values[0].attachments.$values[0].content.body` while the list of `AdaptiveElement` is wrapped as an object.

**Comment by v-kydela** [comment] 2020-05-11 15:40
@hansmbakker - It sounds like you're describing [this bug](https://github.com/microsoft/AdaptiveCards/issues/2148), which I already linked to
