### ISSUE TITLE
Choice Prompt not behaving properly in Bot Framework V4

### ISSUE THREAD

**Issue by Monomoy88** [microsoft/botbuilder-dotnet#4619] opened 2020-09-10 11:25 UTC
## Version
Microsoft.Bot.Builder.Azure, Version=4.5.2.0
Microsoft.Bot.Builder.Dialogs, Version=4.5.2.0

I've updated the version to 4.10.3 but problem still exists.

## Describe the bug
I've created a Dialog bot which is responsible for showing ChoicePrompts based on QnAMaker contextual question answers.

```c#
var promptOptions = new PromptOptions
{
    Prompt = MessageFactory.Text(botResponse),
    Style = ListStyle.SuggestedAction,
    Choices = promptChoices
};

return await stepContext.PromptAsync(nameof(ChoicePrompt), promptOptions, cancellationToken);
```
As I'm using choice prompt so in the next waterfall step I'm trying to read the user choice using below code
`var response= ((FoundChoice)stepContext.Result).Value;`

In a certain case I've two options like below
![image](https://user-images.githubusercontent.com/53524292/92721253-50b48900-f355-11ea-93bc-5ccd924f0ee2.png)

While I'm choosing the 2nd option I'm getting 1st value in the `stepContext.Result` however `stepContext.Context.Activity.Text` is showing proper value that I've selected from bot.
![image](https://user-images.githubusercontent.com/53524292/92721959-68404180-f356-11ea-94b5-f6f51bd999dd.png)

Most of the cases its working fine i.e. value of `stepContext.Result` and `stepContext.Context.Activity.Text` are same.
Is it happening for the special characters >= and < ?
If so then what is the workaround regarding this?

## Expected behavior
`((FoundChoice)stepContext.Result).Value` & `stepContext.Context.Activity.Text` should return same value if ChoicePrompt is used to render prompt in previous waterfall step of a dialog bot.

**Comment by v-kydela** [comment] 2020-09-10 21:56
@Monomoy88 - I've tracked this bug down to [`Find.FindValues`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Find.cs#L97-L190). Apparently the code tokenizes the utterances and each of the choices by getting rid of all special characters, so your two choices look identical to the recognizer. Because the two choices are identical to each other and to the utterance, they'll both get a perfect score. The tie is resolved by picking the longer string because the choices get sorted by length in the beginning. You can reproduce this behavior in a console app like this:

```c#
var choices = new List<string>
{
    "!@#$foo bar",
    "foo  bar%^&*",
};

// Pick the shorter one as the user utterance
var utterance = choices[0];
var opt = new FindValuesOptions();
var results = Find.FindValues(
    utterance,
    choices.Select((value, index) => new SortedValue { Value = value, Index = index }).ToList(),
    opt);

Console.WriteLine(JToken.FromObject(results));
// The text has been reduced to just the word characters
// and the longer choice has been matched:
// [
//   {
//     "Text": "foo bar",
//     "Start": 4,
//     "End": 10,
//     "TypeName": "value",
//     "Resolution": {
//       "value": "foo  bar%^&*",
//       "index": 1,
//       "score": 1.0
//     }
//   }
// ]
```

You have a few options for how to resolve this on your end:

1. Name the choices differently in your knowledge base so that distinct choices always contain distinct word characters (you could for example say "less than" instead of "<")
1. Create the suggested actions in your prompt explicitly and make them send the choice as an index ("0" or "1") instead of the full choice text
1. Create your own [tokenizer function](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Tokenizer.cs#L15) for your prompt's [`RecognizerOptions`](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/ChoicePrompt.cs#L99) property so that it can recognize special characters as tokens

I will leave this open as a bug so the team can triage it properly. I'm considering it a bug because exact matches should always be preferred, and right now what's preferred is the longest choice with the highest score that disregards non-word characters.

**Comment by Monomoy88** [comment] 2020-09-14 07:09
Thanks for explaining the fact in details.
Our solution is very generic & client facing where we can't restrict user to put special characters as long its supported by QnA Maker. 
In QnA Maker if it can distinguish between these two option then recognizer should do that too.
As of now I guess the 3rd option is more appropriate for our solution however I think the approach you proposed in 3rd option should be it's default behavior.

**Comment by mrivera-ms** [comment] 2020-09-17 17:09
@v-kydela , are you able to take this bug? Please let us know if you have the availability.

**Comment by v-kydela** [comment] 2020-09-17 19:10
@mrivera-ms - Yes, I will take it. I'm not sure what the best solution is yet but I'll look into it further.

@Monomoy88 - I suspect option 2 will be better and easier for you than option 3, but once this bug is fixed you won't need to worry about it.

**Closed** 2020-09-22 17:43 UTC
Labels: Area: SDK, Bot Services, P1, Size: S, bug, customer-replied-to, customer-reported
