### ISSUE TITLE
Microsoft Bot Framework V4 Echo and Empty Bot Template Error

### ISSUE THREAD

**Issue by chinnivyshnavi** [Microsoft/botbuilder-dotnet#1291] opened 2019-01-17 07:02 UTC
Hello,

I installed the Microsoft Bot Famework V4 from the market place https://marketplace.visualstudio.com/items?itemName=BotBuilder.botbuilderv4 
Now I am able to see two templates under the Bot framework section of the Visual Studio i.e., Echo bot and Empty Bot.

I created a Echo Bot and No modifications done to the basic template.

When I run the solution and test in the emulator, I am always getting the error "Sorry, it looks like something went wrong" 

Not sure what is the problem and I haven't done any change to the echo bot template.

Ideally it should give me the turn count which is expected.

Detailed Error in emulator:

Sorry, it looks like something went wrong.Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'NotFound’
at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Connector\Conversations.cs:line 1121
at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Connector\ConversationsExtensions.cs:line 241
at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotFrameworkAdapter.cs:line 316
at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext() in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 267
— End of stack trace from previous location where exception was thrown —
at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 196
at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\TurnContext.cs:line 179
at EchoBot1.EchoBot1Bot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in D:\Chinni\Bot Projects\New SDK bots V4\EchoBot1\EchoBot1\EchoBot1Bot.cs:line 84
at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 55
at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in D:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167

**Comment by tdurnford** [comment] 2019-01-17 16:16
Closing this issue as it appears to be a duplicate of https://github.com/Microsoft/BotBuilder-Samples/issues/1160.

**Closed by tdurnford** 2019-01-17 16:16 UTC
