### ISSUE TITLE
Botbuilder-DotNet-Facebook-Functional-Tests fails consistently

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#5340] opened 2021-03-23 05:03 UTC
The pipeline fails in the Test stage. Please investigate.

**Comment by BruceHaley** [comment] 2021-11-02 20:27
Failing because Facebook blocks the test bot's messages when they fall outside the 24-hour time window of the user's last message. [Gabo's PR of a year ago](https://github.com/microsoft/botbuilder-dotnet/pull/4746) fixed this. However, it has become "unfixed".

**Comment by BruceHaley** [comment] 2021-11-20 01:28
My tests show our code is working correctly. Filed an issue with Facebook to get our app unblocked.

**Comment by BruceHaley** [comment] 2021-12-10 20:34
Facebook replied that our test method is not supported. They are treating support for our testing scenario as a future feature request. My dialog with Facebook on the subject can be found at the bugs link above.

Resources to explore if we want to develop a work-around are here: Message Tags documentation:
https://developers.facebook.com/docs/messenger-platform/send-messages/message-tags/
We might try alternating between different tags: CONFIRMED_EVENT_UPDATE, POST_PURCHASE_UPDATE, ACCOUNT_UPDATE.

Meanwhile we can test our Facebook adapter at any time using this by-hand process:

1) Go to this [FB Messenger Chats page](https://www.facebook.com/messages/t/109284330636041), logged in as Fuse Man.
2) Send a message, e.g. "Hello". Our test pipelines can then be run as often as needed, but only within the next 24 hours.
3) Either run [Botbuilder-DotNet-Facebook-Functional-Tests-yaml](https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=796&_a=summary) (takes 9 minutes)
Or run [[debug]BB-DotNet-Facebook-Functional-Tests-without-deploy](https://dev.azure.com/FuseLabs/SDK_v4/_build?definitionId=1112&_a=summary) (takes 5 minutes). Requires the test bot to be already deployed.

Per Monica, we may drop the current channel adapters, therefore it's not worth it to pursue this matter at this time. So I am closing this issue.

**Closed by BruceHaley** 2021-12-10 20:34 UTC
Labels: bug, P1, Area: Engineering
