### ISSUE TITLE
[Bug] [Important] Single Tenant bot is working in other tenants as well

### ISSUE THREAD

**Issue by SubbaReddi** [microsoft/botbuilder-dotnet#6084] opened 2022-01-03 11:39 UTC
## Version
Tried with 4.15.0 4.15.1 (.Net core)

## Describe the bug
Created app registration as Single tenant and azure bot service with Single tenant.
Deployed following sample: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/16.proactive-messages
But this bot is working in multiple tenants. As app registration and other configurations are referring as single tenant, why it is working in other tenants?

## To Reproduce
1. Create app registration with Single tenant option
2. Create Azure bot service with single tenant option
3. Update appsettings.json in following sample: https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/16.proactive-messages and run the solution
4. Install app manifest in main tenant where app registered. Bot should respond
5. Deploy sample app package to teams in other tenant user. Bot should not respond, because it is not same tenant user. but bot is working.

## Expected behavior
Deploying sample app package to teams in other tenant user. Bot should not respond, because it is not same tenant user. but bot is working.

**Comment by anishprasad01** [comment] 2022-01-05 20:30
Hi @SubbaReddi,

I am currently investigating this, and hope to have something for you soon.

**Comment by anishprasad01** [comment] 2022-01-17 16:19
Closing this issue due to inactivity. If you still require assistance, please comment and we can reopen the issue.

**Comment by SubbaReddi** [comment] 2022-01-18 08:56
Hi @anishprasad01,
Apologies for the delay in response. I can reproduce issue with SingleTenant configuration in app registration and azure bot service. Let me know, if any further details required.
![image](https://user-images.githubusercontent.com/69682598/149903718-66ffbe65-2e59-4c97-be39-4460a400647a.png)
![image](https://user-images.githubusercontent.com/69682598/149903775-1bedf6e0-83e4-42c1-ad45-2ec754cf9000.png)

**Comment by anishprasad01** [comment] 2022-01-28 19:10
Investigation is continuing. Once a final resolution is found, I will post the detail here.

**Comment by lauren-mills** [comment] 2022-02-07 22:48
Also, if you would like to restrict access to your bot for users in a specific tenant that can be done by adding an OAuth Connection in your bot configuration in the Azure Portal and adding in an OAuth Prompt or Input asking users to login.

**Comment by anishprasad01** [comment] 2022-02-14 20:39
Since this is expected behavior, I am going to go ahead and close this issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-02-14 20:39 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to, needs-triage
