### ISSUE TITLE
Use Recognizers Cultures in Choice & Confirm Prompt

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botbuilder-dotnet#2458] opened 2019-08-29 23:25 UTC
Please duplicate this work https://github.com/microsoft/botbuilder-js/pull/1121 in dotnet, for parity.

[bug]

**Comment by mdrichardson** [comment] 2019-08-29 23:27
I think most of it is there, minus tests but will be looking at this tomorrow to verify/update.

**Comment by mdrichardson** [comment] 2019-08-30 19:29
FYI for anybody curious: This is taking awhile because I'm doing some fairly heavy refactoring in order to get rid of duplicate code and provide some constants in ChoicePrompt, ConfirmPrompt, and each of their tests related to:

```csharp
{ Spanish, (new Choice("Sí"), new Choice("No"), new ChoiceFactoryOptions(", ", " o ", ", o ", true)) },
```

**Comment by cleemullins** [comment] 2019-09-25 21:06
Duplicate of #2463

**Closed by cleemullins** 2019-09-25 21:06 UTC
Labels: 4.6, parity with JS

**Comment by cleemullins** [comment] 2019-10-17 17:10
The PR that fixes this has been merged.
