### ISSUE TITLE
Exception shown when navigating to endpoint URL in browser

### ISSUE THREAD

**Issue by tompaana** [Microsoft/botbuilder-dotnet#195] opened 2018-02-26 15:27 UTC
This bug affects the developers familiar with Bot Framework 3.x. Launching bot projects built with v3 resulted in the browser automatically navigating to this URL that now, with v4, displays the exception. Do note that the bot project will keep up running fine, but because this GET operation now results in the exception, it interrupts your development when you start looking for the way to fix the issue.

Steps to reproduce:

0. Have any simple bot project (echo bot will do)
1. Launch the project (localhost)
2. When the project is running, in your browser, navigate to `localhost:<port>/api/<controller>` e.g. `localhost:1234/api/messages`
3. Be shocked to see an IoC exception "`InvalidOperationException`: Could not create an instance of type '`Microsoft.Bot.Builder.IBotContext`'."

**Comment by cleemullins** [comment] 2018-02-26 23:44
This is a great observation. I'll see what I can do about fixing it.

**Comment by RyanDawkins** [comment] 2018-02-27 02:17
@cleemullins are you tackling this or is it open?

**Comment by cleemullins** [comment] 2018-02-27 03:01
I'm not yet tackling it. If someone wanted to help, that would be awesome. 

For extra, extra credit, have the web site for the bot be (optionally) the WebChat control hosted via a <div/> ! 🥇

**Comment by tompaana** [comment] 2018-03-01 08:06
For details here's what the exception looks like: [Internal Server Error.html.txt](https://github.com/Microsoft/botbuilder-dotnet/files/1770298/Internal.Server.Error.html.txt)

**Comment by nrobert** [comment] 2018-03-08 09:45
Can this issue be reproduced now? I can't find a way to do it, localhost:<port>/api/<controller> is replying a blank page on samples projects

**Comment by cleemullins** [comment] 2018-03-08 10:07
I’m not sure. Drew’s changes to the WebApi and Asp.net core integration may have fixed this.

Room for improvement certainly remains. Click to launch the emulator, the WebChat Control, or even a live bot-stats page would all be awesome!

________________________________

**Comment by nrobert** [comment] 2018-03-08 10:55
Sure. I had a quick look to Drew's change, it's nice to be able to easily move the main bot's controller in `UseBotFramework`!

So for the improvement, do you really think this "quick access page" should be hosted on the api path? Wouldn't it be better to host it in the default page?

**Comment by cleemullins** [comment] 2018-03-08 11:20
Great point!

The default page is where I envision it, not on the API endpoint.

________________________________

**Comment by nrobert** [comment] 2018-03-08 13:49
I agree.

I like the idea of this quick access page, but at the moment I can't see how:
- Webchat Control =>it will be difficult to add a Webchat Control that will connect to the localhost bot as the Webchat needs that the bot to be deployed (and getting a DirectLine secret)
- Click to launch the emulator => can't launch it on user's computer without knowing the location, etc

**Comment by drub0y** [comment] 2018-03-08 17:07
> So for the improvement, do you really think this "quick access page" should be hosted on the api path? 

The samples currently have `UseStaticFiles()` as well, so for anything related to trying to use the WebChat control, I would suggest just making sure to include a `default.htm` and hosting the control in there. That said, it sounds like WebChat won't work for `localhost` dev? 🤔 

> Click to launch the emulator => can't launch it on user's computer without knowing the location, etc

This is probably a good issue to file over on the emulator's repo, but if they registered a protocol handler, say maybe `ms-bot-emulator:`, then other apps could just launch it via that without having to know where it's installed. Another approach would be for them to just set an environment variable on install (which seems to be coming back into favor these days)... maybe `MS_BOT_EMULATOR_PATH`. Or, finally, just add themselves to `PATH` itself on install so all people would ever have to do is set the command to the `botframework-emulator.exe` executable itself.

**Comment by cleemullins** [comment] 2018-04-16 02:58
The new Bot Emulator is registering a protocol handler, and once that's in we'll update the auto-generated pages to support that

Holding off on resolution until I can verify the behavior has been fixed.

**Comment by cleemullins** [comment] 2018-05-17 21:11
This was fixed in the last iteration of the ASP.Net Integration code.

**Closed** 2018-05-17 21:11 UTC
Labels: bug, good first issue, help wanted
