### ISSUE TITLE
Split() prebuilt function seems to be ignoring space delimiter

### ISSUE THREAD

**Issue by geoffsoper** [microsoft/botbuilder-dotnet#4694] opened 2020-09-24 13:59 UTC
The split function described at https://docs.microsoft.com/en-gb/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#split doesn't seem to be working correctly when using a space as a delimiter.

I'm deriving a user's first name from their full name using "Set a property" where the Value is the expression "=first(split(user.name, ' '))". This code was previously working but not seems not to be and the name is being split into individual characters as if no delimiter was set.

## Version

v1.1.1

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [X] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [X] Windows
- [ ] Ubuntu

## To Reproduce

1. Load [SplitTest_export.zip](https://github.com/microsoft/BotFramework-Composer/files/5276556/SplitTest_export.zip)
2. When prompted, type "John Smith" as your name
3. Observe that the entered string has been split into characters rather than two words.

## Expected behavior

I would expect two words to be produced, rather than individual characters.

## Screenshots

![image](https://user-images.githubusercontent.com/38555263/94154912-4a0a3380-fe76-11ea-9abf-cde3063676d0.png)

**Comment by dmvtech** [comment] 2020-09-24 18:02
I was able to reproduce this. It works with other character delimiters (tested with "**t**").

**Comment by dmvtech** [comment] 2020-09-24 21:47
Hi @ninggao This seems to be a bug in adaptive expressions and not something I would be able to resolve. Any ideas on a better owner?

**Comment by boydc2014** [comment] 2020-09-25 10:14
hi, @geoffsoper  @dmvtech this is a SDK issue and has been fixed in runtime, i believe it's in 4.10.2 (i will double check soon), in composer side, we will bring the fix with next minor version, 1.1.2.

**Comment by lzc850612** [comment] 2020-10-05 17:36
@boydc2014  do you have an update for this issue? has the change been cherry picked into 4.10 and what's the plan for the release of the fix? Thanks

**Comment by boydc2014** [comment] 2020-10-19 08:31
> @boydc2014 do you have an update for this issue? has the change been cherry picked into 4.10 and what's the plan for the release of the fix? Thanks

Sorry for the delay, the PR was cherry-picked 24 days ago, but there hasn't been a release after than (which i though we will have 4.10.4). So, if you need this in and need do a release (4.10.4) for this fix, can you bring this into SDK group? Or, i think 1 week later, 4.11 will come out and will contain this fix.

**Comment by chrimc62** [comment] 2020-10-30 18:19
Will be in 4..1l release

**Closed by chrimc62** 2020-10-30 18:19 UTC
Labels: Area: Adaptive expression, Bot Services, customer-replied-to, customer-reported
