### ISSUE TITLE
Add support for hyphen ("-") in LG template names

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4793] opened 2020-10-14 03:04 UTC
LG templates are currently allowed to have underscores but not hyphens. The LG based `Card Composer` framework I've been building lets you pass in the name of a style you want applied, like "card-title".  I've been following CSS naming conventions for these style names which is to use a hyphens as a separator.  

The issue is, the `Card Styler` tool I built to define the style sheet used by Card Composer maps all of the cards style names into LG templates.  That means that a style like "card-title" gets mapped into an LG template that looks like this:

```
# Styles.card_title
- ${{size: "medium", weight: "bold"}}
```

Since LG templates don't support hyphens I end up mapping "-" to "_".  This is largely hidden from the developer but results in a small performance hit as I have to dynamically map "-" into "_" at runtime. 

It does surface to the developer though as I let them define new styles on the fly using LG expressions but they now need to know the rule that "-" will get mapped to "_". It would be a lot easier all the way around if "-" was natively supported in template names.

**Comment by Danieladu** [comment] 2020-10-19 07:02
Thank @Stevenic . This is a known issue. (Or we could call it by design currently.) 
The reason is the hyphen would confuse the minus operator. 
Let me give an example to clarify the confusion.
```
# number1-getNumber2
- hi

# getNumber2
- ${5 * 2}

# someTemplate
> this is ambiguous between `number1` minus the value from `getNumber2()` and just call the function which name is `number1-getNumber`
- ${number1-getNumber2()}
```

Welcome the discussion.

**Comment by boydc2014** [comment] 2020-10-19 07:53
Closing this as "-" will be conflict with minus operations. Normal programming languages don't allow "-" in IDENTIFIER(variable name, function name, etc).

**Closed by boydc2014** 2020-10-19 07:53 UTC
Labels: Area: LG, feature-request, needs-triage
