### ISSUE TITLE
QnAMakerDialog Support for IBotTelelmetryClient

### ISSUE THREAD

**Issue by DavidStrickland0** [microsoft/botbuilder-dotnet#3688] opened 2020-04-06 23:24 UTC
**Is your feature request related to a problem? Please describe.**
QnaMaker Cognitive Service does not return Telemetry info. QnAMaker supports Telelmetry if an Implementation of the IBotTelelmetryClient is provided at time of Construction.

**Describe the solution you'd like**
Add a telelmetryClient  parameter of type IBotTelelmetryClient on Line 117 of The QnAMakerDialog.cs constructor signature defaulting it to null.

In the constructor store it to a local private field.
on Line 232 of QnAMakerDialog.cs add this private field as the 4th parameter of the initialization call changing
return new QnAMaker(endpoint, options, HttpClient);
 to
return new QnAMaker(endpoint, options, HttpClient,telelmetryClient);

**Describe alternatives you've considered**
Inherit and override GetQnAMakerClientAsync.

**Additional context**
none

[enhancement]

**Comment by igarcia7** [comment] 2020-04-07 15:41
We are also experiencing the same issue as above. We recently migrated to Bot.Builder Version 4.7.2 to be able to add skills to our VA, but our Power BI Dashboard for QnA Telemetry is no longer being recorded. 

In the EventTelemetry table in Power BI Dashboard -  QnA_knowledgeBasedId and QnA_Answer are no longer being recorded.

**Comment by pchoudhari** [comment] 2020-04-09 09:07
Hi, we are investigating this issue. Will update shortly.

**Comment by garypretty** [comment] 2020-04-09 09:15
@pchoudhari @vipeketi I will take this one.  It is related to the work I am doing today for adaptive telemetry.

**Comment by garypretty** [comment] 2020-04-09 15:36
Duplicate of #3472. Closing.

**Closed by garypretty** 2020-04-09 15:36 UTC
Labels: Bot Services, R9, customer-reported
