### ISSUE TITLE
QnAMakerDialog should create QnAMaker with more parameters

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#3472] opened 2020-03-02 07:26 UTC
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

QnAMakerDialog creates QnAMaker without parameters like IBotTelemetryClient telemetryClient, bool logPersonalInformation. So we could not control these.

**Describe the solution you'd like**

Could configure all parameters for QnAMaker.

**Describe alternatives you've considered**

**Additional context**

https://github.com/microsoft/botbuilder-dotnet/blob/5c71a77a732d33d15e84929e429c5104f63b477f/libraries/Microsoft.Bot.Builder.AI.QnA/Dialogs/QnAMakerDialog.cs#L143

[enhancement]

**Comment by cleemullins** [comment] 2020-04-08 19:32
@garypretty, I believe this is the QnA Maker telemetry issue.

**Comment by DavidStrickland0** [comment] 2020-04-09 13:33
dupe of #3688 or visa-versa

**Closed** 2020-04-16 16:44 UTC
Labels: P2, R9
