### ISSUE TITLE
[Adaptive] Adaptive dialogs + LG debuggability

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2385] opened 2019-08-08 00:12 UTC
Work here builds on top of the inspection middleware to enable improved debugging experience with adaptive dialogs.

1. Add support for ability in the runtime to break at a specific step in an adaptive dialog
2. Add ability to continue to next step and break once a break step has been encountered. 
3. Add ability to continue till next break point (if any) once a break step has been encountered.
4. Add debug break property for all steps and events.

**Comment by vishwacsena** [comment] 2019-12-18 19:39
Decision for R8
- Property (emitTrace with expression as value) for all actions that emit a trace when the action is executed

Emulator [?]: 
- DialogState inspector 
    - Trace output was a bit more structured and promote dialogState up if available in a trace
    - Add ability to eval expressions against dialog state

**Comment by vishwacsena** [comment] 2020-03-10 21:16
Decision R9
    - vs code, vs extension ships
    - lg hook up for debug protocol
    - debug protocol for composer

**Comment by cleemullins** [comment] 2020-04-08 19:47
@vishwacsena, this is a P0 bug from Aug 7, making it 9 months old. If we push to R10, we can celebrate it's 1-year birthday.

**Comment by boydc2014** [comment] 2020-04-09 06:43
@cleemullins 

The issue is old because that, this issue is initially created for tracking debugability for Adaptive, which is supported in R8 already, then in the end of R8 and starting of R9, we start talking about we should include LG debug ability as well. So the timeline changed to R9, but scope expanded.

**Comment by vishwacsena** [comment] 2020-04-13 17:10
@boydc2014 chatted with Scott this morning. Tagging as P1.

**Comment by cleemullins** [comment] 2020-04-20 17:31
There is already an implementation of this (per @tomlm) and a PR.

**Comment by cleemullins** [comment] 2020-04-28 16:45
@vishwacasena, @boydc2014 Updates?

**Comment by boydc2014** [comment] 2020-04-30 02:06
> @vishwacasena, @boydc2014 Updates?

The PR is referenced as above, going through a couple rounds review already, no issues on my side now, i would add Tom for review again, because it touched the dialog packages also.

**Comment by sgellock** [comment] 2020-04-30 22:25
given the national holiday and the fact that we're cutting RC builds, I'm moving this out of the R9 milestone and into R10.

**Comment by mrivera-ms** [comment] 2020-08-06 05:07
Discussed with @boydc2014 , this is blocked and being removed from R10 and pushed to R11.

**Closed** 2020-10-02 18:52 UTC
Labels: Area: LG, P1, triaged
