### ISSUE TITLE
TranscriptLoggerMiddleware exception when logging activities without ID like trace activities

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#4734] opened 2020-09-29 13:37 UTC
## Version
v4.10.3

## Describe the bug
The AzureBlobTranscriptStore throws the following exception when an activity in the transcript has no ID. This is the case for e.g. trace activities.

```
Transcript logActivity failed with Microsoft.WindowsAzure.Storage.StorageException: The argument must not be empty string.
 ---> System.ArgumentException: The argument must not be empty string.
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.AddMetadata(StorageRequestMessage request, String name, String value)
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.AddMetadata(StorageRequestMessage request, IDictionary`2 metadata)
   at Microsoft.WindowsAzure.Storage.Blob.Protocol.BlobHttpRequestMessageFactory.AddMetadata(StorageRequestMessage request, IDictionary`2 metadata)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass137_0.<PutBlockListImpl>b__1(RESTCommand`1 cmd, Uri uri, UriQueryBuilder builder, HttpContent cnt, Nullable`1 serverTimeout, OperationContext ctx)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](ExecutionState`1 executionState, String startLogMessage, CancellationTokenSource timeoutTokenSource)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.CommitAsync()
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Newtonsoft.Json.JsonTextWriter.CloseBufferAndWriter()
   at Newtonsoft.Json.JsonTextWriter.Close()
   at Newtonsoft.Json.JsonWriter.Dispose(Boolean disposing)
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.LogActivityAsync(IActivity activity, CloudBlockBlob blobReference)
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.LogActivityAsync(IActivity activity)
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.TryLogActivityAsync(ITranscriptLogger logger, IActivity activity)
```

## To Reproduce
1. Create an empty bot, e.g. using the Bot Framework Composer
2. Add a trace activity
3. Enable the TranscriptLoggerMiddleware using the AzureBlobTranscriptStore
4. Send a message to the bot to trigger the trace activity
5. See the exception in the output window in Visual Studio

## Expected behavior
Either one of the following options would resolve the issue. I prefer the first.
- the ID metadata parameter should not be set if it's an empty string
- an arbitrary ID should be generated if it's missing
- trace activities should be ignored by the transcript store

**Comment by jwiley84** [comment] 2020-10-06 17:41
Assigning to @v-kydela as I'm unable to run composer at the moment.

**Comment by v-kydela** [comment] 2020-10-06 22:49
@lzc850612 - This can be reproduced in a console app like this:

```c#
var store = new AzureBlobTranscriptStore(DataConnectionstring, ContainerName);

var activity = new Microsoft.Bot.Schema.Activity
{
    Id = "",
    ChannelId = Channels.Test,
    From = new ChannelAccount("me"),
    Recipient = new ChannelAccount("you"),
    Conversation = new ConversationAccount(id: "us"),
    Timestamp = DateTime.Now,
};

store.LogActivityAsync(activity).Wait();
```

@sschutten - I've observed that it's more than just metadata the activity ID is used for. The activity ID is also used to [name the blob](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs#L339):

> ```c#
> var blobName = $"{SanitizeKey(activity.ChannelId)}/{SanitizeKey(activity.Conversation.Id)}/{activity.Timestamp.Value.Ticks.ToString("x", CultureInfo.InvariantCulture)}-{SanitizeKey(activity.Id)}.json";
> ```

![blobs](https://user-images.githubusercontent.com/41968495/95266684-83cd2980-07e8-11eb-8d1f-7656bddd8b2a.png)

I don't know if the team will think changing that system is a good idea. I can see that you want something to be changed in the SDK, but I have to ask: would providing an ID to the trace activity yourself be an acceptable workaround?

You had said "e.g. using the Bot Framework Composer" as though it's not important whether or not Composer is being used, but Composer changes everything in most cases and I don't think this is an exception. If this problem is indeed caused by Composer neither providing an activity ID automatically nor allowing the developer to provide one manually, why not consider this a Composer bug rather than an SDK bug?

Then again, [I'm not sure if trace activities are meant to be seen outside of Emulator](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L545-L548).

> ```c#
> else if (activity.Type == ActivityTypes.Trace && activity.ChannelId != "emulator")
> {
>     // if it is a Trace activity we only send to the channel if it's the emulator.
> }
> ```

**Comment by abhi23arora** [comment] 2020-10-10 08:17
Hi Team,

I am facing the same problem. I am trying to enable transcript logging on blob storage. While everything works fine (successful logging of message, event and trace type) on local emulator, but I dont see trace type logs when I publish on the cloud. I need the trace type to see the confidence score and other metrices when customers chat with my bot.

Any idea how can I make this happen?

Thanks

**Comment by v-kydela** [comment] 2020-10-13 19:40
@abhi23arora - It sounds like you're facing a somewhat different problem. Your problem is that trace activities aren't logged. The original problem was that trace activities are causing errors, and a potential solution to that problem is to prevent trace activities from being logged. However, we can take your case into consideration by trying to fix the errors in a way that allows trace activities to be logged.

@lzc850612 - Since I have provided a repro, I am unassigning myself so the team can decide how to fix this.

**Comment by stevengum** [comment] 2020-10-23 18:29
@garypretty can you triage this for the R12 release?

**Comment by EricDahlvang** [comment] 2020-11-10 02:03
A PR has been submitted to check for IsNullOrEmpty while cloning the activity.

Thank you for bringing this to our attention @sschutten

**Closed** 2020-11-10 17:47 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported
