### ISSUE TITLE
[LG] Import fallback not working as it used to

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-dotnet#4309] opened 2020-07-22 12:48 UTC
## Version
4.9.3

## Describe the bug
In earlier versions, I believe 4.8.x, when importing LG files it used the following fallback rules: "en-us" -> "en" -> "". As of version 4.9.x it doesn't fallback to the last option with the empty language. It first tries to resolve "en-us" then "en" and then fails with the message `There is no matching LG resource for common.lg`.

## To Reproduce
1. Use the Bot Framework Composer to create a new bot using the `Echo Bot` example
2. Navigate to %AppData%\Roaming\BotFrameworkComposer\hostedBots\<bot id>\language-generation\en-us and rename `common.en-us.lg` to `common.lg`
3. Start the bot from the Bot Framework Composer and test it in the Bot Framework Emulator
4. Notice the error message `There is no matching LG resource for common.lg`

## Expected behavior
I would expect the LanguagePolicy to fallback to the empty language rule for imports, so I can share the same common.lg with all languages.

## Additional context
The [LanguagePolicy](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/LanguagePolicy.cs) class comments clearly describe that the output of the default policy for example "en-us" should be `["en-us", "en", ""]`. The actual output for example "en-us" is actually `["en-us", "en"]`, so it makes sense it would not fallback to "". However by looking at the history of the LanguagePolicy class I couldn't figure out why it worked using 4.8.x since it appears this logic hasn't really changed over time.

[bug]

**Comment by munozemilio** [comment] 2020-07-22 20:05
@chrimc62 @vishwacsena could you please take a look?

**Comment by chrimc62** [comment] 2020-07-22 21:37
This was broken by @boydc2014 with commit a457ec6d when he allowed specifying default languages.  He only added those if the language was empty which will never happen.  He should remove the lines below from LanguagePolicy.
```
              if (language.Length == 0)
                {
```

**Comment by munozemilio** [comment] 2020-07-23 18:05
@boydc2014 could you please take a look?

**Comment by boydc2014** [comment] 2020-07-27 15:31
@chrimc62 @sschutten sorry for the late response,  short summary is 

1. the import behavior of lg was impacted because of the language policy change
2. but the root cause is not language policy structure is wrongly updated, it's a by design change to support more flexible fallback behavior, more context is added in below
3. the root cause is LG importing is not using customized language policy

Also, in Composer, we were designing for giving every lg a locale, even for common.lg. I will work for a mitigation of this pattern and get back to you later @sschutten . 

TL, DR version

in 4.9.3 and before the policy class is like

en-us => en=> ""
fr-fr => fr => ""

it's a fixed list and user can't customize that, so in latest, we have some upgrade on the structure to support the scenario of Composer (which are moving to multi-locale support), we are removing the the trailing "", and add a specific entry "", so the new dict will look like 

en-us => en
fr-fr => fr 
"" => [list of default language(s) that user can specify]

If user don't set this list of default languages, it would work as same as before. 

####  LG import impact
The root issue is LG import resolving is happened before user even feed this customized language-policy, so LG import resolving is using a default language policy which don't have "" anymore in this change.

**Comment by sschutten** [comment] 2020-07-28 14:13
@boydc2014 thank you for the answer. I've read your answer but I fail to fully understand. Can you help me clear this up?

> Also, in Composer, we were designing for giving every lg a locale, even for common.lg.

Does this mean that a shared common.lg across all languages is no longer supported?

> in 4.9.3 and before the policy class is like
> en-us => en=> ""
> fr-fr => fr => ""

My issue is referring 4.9.3. In 4.9.3 the policy class is like:
en-us => en
fr-fr => fr
So the last "" is missing.

> we are removing the the trailing "", and add a specific entry "", so the new dict will look like
> en-us => en
> fr-fr => fr
> "" => [list of default language(s) that user can specify]

As I understand this won't help resolve a common.lg (without language) from any LG file with a language. Let me clarify.

E.g. I have the following two LG files:
- Main.en-us.lg
- common.lg
Main.en-us.lg imports common.lg

1. The LanguageGeneratorManager will load a list of LG resources grouped by language
https://github.com/microsoft/botbuilder-dotnet/blob/e469816cca0c3aaefa67b6207320534c5a8115e5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs#L34
This looks like:
[
  "en-us": ["Main.en-us.lg"],
  "": ["common.lg"]
]

2. This dictionary is then forwarded to the TemplateEngineLanguageGenerator
https://github.com/microsoft/botbuilder-dotnet/blob/e469816cca0c3aaefa67b6207320534c5a8115e5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs#L92

3. The TemplateEngineLanguageGenerator constructs a ResourceExplorerResolver with this dictionary
https://github.com/microsoft/botbuilder-dotnet/blob/e469816cca0c3aaefa67b6207320534c5a8115e5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs#L54

4. A user sends a message to the bot with locale 'en-us'

5. The ResourceExplorerResolver retrieves the fallback locale. Since 'en-us' exists as a locale in the dictionary keys, the locale is 'en-us'.
https://github.com/microsoft/botbuilder-dotnet/blob/e469816cca0c3aaefa67b6207320534c5a8115e5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs#L60

Since the ResourceExplorerResolver keeps using the locale 'en-us' for each resolve attempt, it will never find resources with language "".

Before the change the dictionary of LG resources grouped by language in step 1. would look like the following, which means it would be able to resolve the "common.lg".
[
  "en-us": ["Main.en-us.lg", "common.lg"],
  "": ["common.lg"]
]

I can specify a list of default languages, but those would only be added when language is "". I believe that's what @chrimc62 is referring to in their comment.

**Closed** 2020-08-04 00:52 UTC
Labels: Bot Services, customer-replied-to, customer-reported
