### ISSUE TITLE
all intents are not available in bot framework adaptive dialogs

### ISSUE THREAD

**Issue by maheshcm80** [microsoft/botbuilder-dotnet#4473] opened 2020-08-18 13:53 UTC
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
I have an issue in getting all intents in adaptive dialogs. i need all intents available in my child dialog to trigger second top scoring intent.

**Describe the solution you'd like**
Please include all the intents in adaptive dialog. 

**Describe alternatives you've considered**
Currently i have got the all intents by calling luis endpoint. this is a temporary solution.

**Additional context**

**Comment by peterinnesmsft** [comment] 2020-08-19 18:10
@maheshcm80 this is currently by design. Our support team can follow up to better understand your scenario and we can see what we can do to help address.

**Comment by maheshcm80** [comment] 2020-08-20 05:07
okay thank you, please provide me any work around solution for this.

**Comment by peterinnesmsft** [comment] 2020-08-20 05:27
Our Support team should be able to pick this up. We will keep this issue active and they will follow up soon and assign it to someone that can further supported. Stay posted!

**Comment by maheshcm80** [comment] 2020-08-20 05:32
> **okay thank you** 👍

**Comment by v-kydela** [comment] 2020-08-20 20:32
Thank you for the feature request, @maheshcm80

From a support perspective, I've already addressed this here: https://stackoverflow.com/a/63123545/2122672

From a feature request perspective I'm afraid this has been declined for now, but the team may reexamine it if we see more customers having this issue.

**Closed by v-kydela** 2020-08-20 20:32 UTC
Labels: Bot Services, Support, customer-reported, feature-request, needs-triage
