### ISSUE TITLE
HeroCard buttons don't works

### ISSUE THREAD

**Issue by TheSquiffy** [Microsoft/botbuilder-dotnet#221] opened 2018-03-01 09:35 UTC
I'm trying to send simple yes/no buttons following the documentation.

Here's my code:

                        var activity = MessageFactory.Attachment(
                            new HeroCard(
                                title: $"Are you sure you want to delete order '{ this.State.Order.OrderNumber }'",
                                buttons: new CardAction[] {
                                    new CardAction(title: "yes", text: "yes", value: "yes"),
                                    new CardAction(title: "no", text: "yes", value: "no")
                                }
                            ).ToAttachment());

                        // Send the activity as a reply to the user.
                        context.Reply(activity);

I'm expecting messages when clicking on them; nothing happens.

**Comment by JonathanFingold** [comment] 2018-03-02 17:32
@cleemullins , if this is not a bug in CardAction and you post the correct parameters to use, I will update the wiki page.

**Comment by cleemullins** [comment] 2018-03-02 18:05
@JonathanFingold : Can you try it an see? 👍 The code is only 5 minutes to write and test.

**Comment by Stevenic** [comment] 2018-03-02 18:37
@TheSquiffy you're not specifying the CardAction "type", should be "imBack", "postBack", or can be "messageBack" if using MS Teams

**Comment by TheSquiffy** [comment] 2018-03-02 19:11
@Stevenic yes, you are right. Using imBack it's working, thank you. I think the wiki page should better clarify this ;-)

**Comment by cleemullins** [comment] 2018-03-02 19:14
@JonathanFingold  - if you've a moment, could you update the Wiki, per this discusson? That change needs to be made across all the Wiki's...

**Comment by JonathanFingold** [comment] 2018-03-02 19:17
@cleemullins Currently updating and verifying the C# sample. I'll port my changes over to the other wikis shortly.

**Comment by Stevenic** [comment] 2018-03-02 19:17
While we're at it we should drop the `text` property from the samples. Only `messageBack` uses that field and `messageBack` is only supported on MS Teams.  The sample should use `type`, `title`, and `value`.

**Comment by JonathanFingold** [comment] 2018-03-02 19:32
Fixed in the -dotnet repo, so closing here.
- CardActions now all use `type: ActionTypes.ImBack`, `title`, and `value`.
- Suggested actions now uses `text` to avoid the _empty text bubble_ issue.

Will update the other repos presently.

**Closed by JonathanFingold** 2018-03-02 19:32 UTC
