### ISSUE TITLE
IStorage lacking information on what it is Reading and Writing

### ISSUE THREAD

**Issue by RamjotSingh** [Microsoft/botbuilder-dotnet#696] opened 2018-06-27 01:57 UTC
I hit a peculiar case where because I moved the class from one dll to another and the whole Storage abstraction blew. I digged and the issue stems from the fact that we use TypeNameHandling.All which is in turn due to StateMachine not passing the Type is expects when reading (by extension writing too, though that matters less). 
This means that once a class is written in one dll developers won't be able to change it's namespace, name of dll without the whole database retrieval blowing up for Json cases. 

If we now look at BotState class. It actually has the TState information on what can be retrieved and should pass this information to IStorage layer.

Thoughts?

@cleemullins , @Stevenic

**Comment by drub0y** [comment] 2018-06-27 17:15
Yeah, I don't think type name handling should be used at all... that's kind of an old school approach that I think we (the community) have learned over time leads to serious versioning issues. I purposefully got rid of that in my DCR (#375) and, instead, it deserializes to a `TState` you ask it for.

**Comment by RamjotSingh** [comment] 2018-06-28 00:15
@drub0y Thanks man!! I hit the issue where I tried to reuse the same C# class across 2 projects using linking. Thanks for taking care of this :)

**Comment by drub0y** [comment] 2018-06-28 14:35
Well, just to set expectations, that DCR is not being accepted, so for now we kind of have to hope whatever implementation does show up takes the same philosophy.

Let's leave this issue open so it is ultimately addressed one way or another.

**Comment by cleemullins** [comment] 2018-06-28 20:40
@Stevenic is working on this now and planning to have the Node code checked in today. Hopefully I can then get the same behavior working in C#.

**Comment by sgellock** [comment] 2018-08-21 22:58
@RamjotSingh thanks for the feedback.  we've made some design changes in our storage layer and API.  please take a look and if you feel we're not addressing your needs, please open a new ticket.

**Comment by drub0y** [comment] 2018-08-22 16:30
I can definitively say this was not addressed. In fact, the `IStorage` API has not been fundamentally changed since we did work to remove `dynamic` back in May. As a result, if you search the code base, you'll find that all the `XXXStorage` implementations are still using `TypeNameHandling.All` because, without it, they'd have no idea what type to deserialize to.

So, do you really want to open a new issue? It would literally include the exact same details. For now I'm just going to reopen this one. 

I just think there needs to be a final decision made here: either we call it "by design" and live with the ramifications or we acknowledge the design flaw and come up with a plan around how to address it.

**Comment by johnataylor** [comment] 2018-11-06 01:08
Compatibility of the shape of the JSON with anything other than the code that first produced is not a feature of this implementation. This has shipped now and for this storage model that is how it behaves and that can't change without breaking back compatibility.

However, implementing a different storage model, even one with very different semantics, is a relatively straight forward exercise requiring a relatively small amount of code. We have a new sample that demonstrates just that with a focus on how that can be plugged into the dialog framework.

In fact, by way of demonstration, the only aspect it owes to the storage framework that shipped in 4.0 is the accessor interface itself - and in that case it provides a generic solution.

The sample can be found here: 
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/42.scaleout

and an article here:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-custom-storage?view=azure-bot-service-4.0

**Closed by johnataylor** 2018-11-06 01:08 UTC
Labels: Backlog, state-management
