### ISSUE TITLE
New channel Viber

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [Microsoft/botbuilder-dotnet#1091] opened 2018-11-07 05:37 UTC
Hi!

You could add to the list of supported channels such as Viber ? :)

**Comment by stevengum** [comment] 2018-11-07 17:23
Closing as it is a duplicate of Microsoft/botframework-services#19. Please send all channel support requests to the [BotFramework-Services](https://github.com/Microsoft/BotFramework-Services/issues/new) repository.

**Closed by stevengum** 2018-11-07 17:23 UTC
Labels: Enhancement
