### ISSUE TITLE
[QnA Maker] Active learning lowVariationFilter function

### ISSUE THREAD

**Issue by gurvsing** [microsoft/botbuilder-dotnet#3705] opened 2020-04-08 09:49 UTC
## Describe the bug
Moving the check to call for LowScoreVariation, inside the function
For more detail: https://github.com/microsoft/botbuilder-dotnet/issues/3642

**Comment by vipeketi** [comment] 2020-04-13 10:35
Fixed with https://github.com/microsoft/botbuilder-dotnet/pull/3730

**Closed** 2020-04-13 10:35 UTC
Labels: P1, QnA Maker, R9

**Comment by vipeketi** [comment] 2020-04-13 12:41
Duplicate of https://github.com/microsoft/botbuilder-dotnet/issues/3642

**Comment by vipeketi** [comment] 2020-04-13 13:00
Duplicate of #3742
