### ISSUE TITLE
Adding additional content while sending Request-Id in headers

### ISSUE THREAD

**Issue by pvmraghunandan** [Microsoft/botbuilder-dotnet#1300] opened 2019-01-24 07:40 UTC
## Version
4.2.0

## Describe the bug
While sending request from direct line, we are populating Request-Id custom header with GUID Value. For example 97ccb5e1-c49c-4761-b337-df96498a1626. But, once received back to the Bot, the value is being changed to "|97ccb5e1-c49c-4761-b337-df96498a1626.7465a8c0_11." by adding additional "|" and some other data with ".". Should we remove them explicitly (or) any specific reason for adding additional content to Request-Id?

## To Reproduce
1. Send Request-Id as customer header while sending through direct line.
2. Observe Request-Id received in the BOT having additional content added in addition to the original Request-Id.

## Expected behavior
Request-Id should be sent as it is.

## Screenshots

**Request**

![image](https://user-images.githubusercontent.com/7496232/51662276-4e16eb80-1fd9-11e9-8023-82413a48996e.png)

**Once received in BOT**

![image](https://user-images.githubusercontent.com/7496232/51662180-0abc7d00-1fd9-11e9-802e-121b936334be.png)

**Comment by mdrichardson** [comment] 2019-01-24 18:48
Custom headers are stripped and don't reach the application, by design. If you're wanting to pass in a GUID, you can use the `ChannelData` attribute. You can use any schema you'd like for DirectLine (non-DirectLine channels require it fit certain schema). 

It was originally meant for [implementing channel-specific functionality](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-channeldata?view=azure-bot-service-3.0), but since none of it is stripped, it can be used to pass information.

If you're using DirectLine via WebChat, it might look something like this:

```
BotChat.App({
  botConnection: Object.assign({}, dl, {
     postActivity: activity => {
     var newActivity = Object.assign({}, activity, { channelData: { "GUID": "XYZ..." } });
     return dl.postActivity(newActivity);
    }
  }),
  bot: bot,
  user: user,
  resize: 'detect',
}, document.getElementById('bot'));
```

Or if you're sending it via HTTP requests, the body might look like this:

```
{
  "type": "message",
  "from": {
    "id": "123456789",
    "name": "myBot"
  },
  "recipient": {
    "id": "987654351",
    "name": "Customer"
  },
  "text": "This is test",
  "channelData": {
    "GUID": "XYZ...",
      }
}
```

**Comment by pvmraghunandan** [comment] 2019-01-25 05:37
@mdrichardson  Thanks for the reply. Got the point about custom headers and was aware of it. This issue is specifically about Request-Id for tracing. Based on my testing, if the sender sends value in Request-Id, BOT framework is considering that as Operation Id for App Insights and the issue is once it is forwarded to BOT code, the value is being changed to append few additional content which is actually Parent Operation Id in App Insights. Also, in response, x-ms-RequestId is also set to the same with same updated value. Screenshots shows the same. Is it by design?

Just for context, in our application BOT is just one component in App Eco System.

**Comment by mdrichardson** [comment] 2019-01-25 19:05
I see. My team and I are actually surprised Request-Id makes it through to your bot at all. If you can post your bot's `appId`, I can look into this further with your specific bot while I research how DirectLine works, in general.

**Comment by mdrichardson** [comment] 2019-01-25 23:24
Turns out this issue isn't with BotFramework. I dug through both BotFramework and DirectLine code and wasn't able to find anything that would change any variation of `request-id` or `parent-operation-id`. 

It looks like it's something that Application Insights does. It receives the headers [here](https://github.com/Microsoft/ApplicationInsights-node.js/blob/c298b263562b086117e715d0c61d24d1fd2e9b48/AutoCollection/HttpRequestParser.ts#L209) and then formats it [here](https://github.com/Microsoft/ApplicationInsights-node.js/blob/e040d04f44682e64b693c2ec0fe96f9a22e40959/Library/CorrelationIdManager.ts#L104). You can see that it would format your `abcd-xyz-123` format into something like the (roughly) `|abcd-xyz-123.234bk23` format you received.

If your issue is using the GUID with Application Insights, you can have DirectLine send the GUID in `channelData` as I showed above, then have the bot send it as Application Insights Telemetry. [This blog post should get you started](https://blog.botframework.com/2017/09/28/qna-maker-revisited-suggested-actions-app-insights/).

**Comment by mdrichardson** [comment] 2019-01-29 17:26
@pvmraghunandan Let me know if my comment above solves or appropriately addresses your issue and I'll close it. If not, let me know what else I can do to help. Thanks!

**Comment by mdrichardson** [comment] 2019-02-04 20:00
I am closing this issue as it doesn't seem to be a blocking issue. Feel free to reopen if you have need to get this resolved.

**Closed by mdrichardson** 2019-02-04 20:00 UTC
Labels: Support, Triaged
