### ISSUE TITLE
InputDialog increments turn count when an interruption has occured

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#5040] opened 2020-12-10 01:44 UTC
## Describe the bug

As identified in #1952 we're incrementing the turn count when an interruption occurs which isn't expected behavior. We should add logic [here](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs#L259) to only increment the count if `interrupted` is false.

**Comment by mrivera-ms** [comment] 2020-12-11 19:23
This is a duplicate of #5008.

**Closed by mrivera-ms** 2020-12-11 19:23 UTC
Labels: bug, needs-triage
