### ISSUE TITLE
Facebook Bot answering the same response multiple times each new session

### ISSUE THREAD

**Issue by igordevezas** [microsoft/botbuilder-dotnet#5097] opened 2021-01-13 20:13 UTC
## Version
I am using the Facebook Adapter version 4.11.0 and Composer 1.3.0

## Describe the bug
Each new session on Facebook (after 20 minutes without conversation or after a new deploy) the bot answer multiple times the same message.

## To Reproduce
1. Integrate your Bot using Composer and Facebook C# Adapter
2. Send a message 
3. Wait for 20 minutes
4. Send a message again and wait for bot's response
5. See error

## Expected behavior
Bot needs to answer just once each message.

## Screenshots
![print01](https://user-images.githubusercontent.com/1262003/104505287-f3bb2f00-55e3-11eb-901b-1f0b1645c772.png)
![log](https://user-images.githubusercontent.com/1262003/104505302-f87fe300-55e3-11eb-851c-44a90f30bf38.png)
![trigger](https://user-images.githubusercontent.com/1262003/104505313-fb7ad380-55e3-11eb-9495-037aad31b831.png)

**Comment by boydc2014** [comment] 2021-01-14 02:38
@igordevezas can you zip your bot and attach it here? 

@Danieladu can you help verify this one? looks like some other events are sent and processed by SDK

**Comment by igordevezas** [comment] 2021-01-14 08:54
Sure, here it is. This zip does not have the assets for Azure Functions that I am using, the file is too large to attach here. Let me know if you want to upload it on other platform

[CardDevezas_export.zip](https://github.com/microsoft/botbuilder-dotnet/files/5813327/CardDevezas_export.zip)

**Comment by boydc2014** [comment] 2021-01-14 09:47
> Sure, here it is. This zip does not have the assets for Azure Functions that I am using, the file is too large to attach here. Let me know if you want to upload it on other platform
> 
> [CardDevezas_export.zip](https://github.com/microsoft/botbuilder-dotnet/files/5813327/CardDevezas_export.zip)

Thanks, that will do for us for now, just to confirm is there special triggers are been configured to catch events and send back.

**Comment by Danieladu** [comment] 2021-01-20 09:37
Can not reproduce from local. I guess maybe it is related to Azure Functions
![fb](https://user-images.githubusercontent.com/7289268/105155807-008cd500-5b46-11eb-9fef-9e975a45ddf8.gif)

**Comment by igordevezas** [comment] 2021-01-20 15:00
Hi @Danieladu, tks for replying it. Are you using the Azure Web Apps version? Could you "mentor" me on what I am doing wrong with Azure Functions? I followed this tutorial from @zidaneymar: https://github.com/microsoft/BotFramework-Composer/issues/2705 and then I "translated" to Azure Functions... Thank you so much!

**Comment by Danieladu** [comment] 2021-01-21 07:06
Can not reproce from Azure Functions too. Maybe i missed something..

**Comment by Danieladu** [comment] 2021-01-21 07:58
Can not reproduce from Azure Functions too. Maybe i missed something.

https://github.com/microsoft/BotFramework-Composer/issues/2705#issuecomment-664230948 
This reference is aimed to add the Facebook adapter into web app. If you want to apply the Facebook adapter to Azure functions, 
 some similar code should added into `runtime` -> `azurefunctions`

@zidaneymar  Could you please take a look?

**Comment by igordevezas** [comment] 2021-01-21 10:22
Maybe its because I have 2 Adapters inside Startup.cs?

`
 // Create the credential provider to be used with the Bot Framework Adapter.
services.AddSingleton<ICredentialProvider, ConfigurationCredentialProvider>();
services.AddSingleton<BotAdapter>(sp => (BotFrameworkHttpAdapter)sp.GetService<IBotFrameworkHttpAdapter>());

// Adapter
services.AddSingleton<IBotFrameworkHttpAdapter, BotFrameworkHttpAdapter>(s =>
{
    // Retrieve required dependencies
    IStorage storage = s.GetService<IStorage>();
    UserState userState = s.GetService<UserState>();
    ConversationState conversationState = s.GetService<ConversationState>();
    TelemetryInitializerMiddleware telemetryInitializerMiddleware = s.GetService<TelemetryInitializerMiddleware>();

    var adapter = new BotFrameworkHttpAdapter(new ConfigurationCredentialProvider(config));

    adapter
      .UseStorage(storage)
      .UseBotState(userState, conversationState)
      .Use(new RegisterClassMiddleware<IConfiguration>(config))
      .Use(telemetryInitializerMiddleware);

    // Configure Middlewares
    ConfigureTranscriptLoggerMiddleware(adapter, settings);
    ConfigureInspectionMiddleWare(adapter, settings, s);
    ConfigureShowTypingMiddleWare(adapter, settings);

    adapter.OnTurnError = async (turnContext, exception) =>
    {
        await turnContext.SendActivityAsync(exception.Message).ConfigureAwait(false);
        await conversationState.ClearStateAsync(turnContext).ConfigureAwait(false);
        await conversationState.SaveChangesAsync(turnContext).ConfigureAwait(false);
    };

    return adapter;
});

// FacebookAdapter
services.AddSingleton<FacebookAdapter>(s =>
{
    // Retrieve required dependencies
    IStorage storage = s.GetService<IStorage>();
    UserState userState = s.GetService<UserState>();
    ConversationState conversationState = s.GetService<ConversationState>();
    TelemetryInitializerMiddleware telemetryInitializerMiddleware = s.GetService<TelemetryInitializerMiddleware>();

    var adapter = new FacebookAdapter(config);

    adapter
      .UseStorage(storage)
      .UseBotState(userState, conversationState)
      .Use(new RegisterClassMiddleware<IConfiguration>(config));

    adapter.OnTurnError = async (turnContext, exception) =>
    {
        await turnContext.SendActivityAsync(exception.Message).ConfigureAwait(false);
        await conversationState.ClearStateAsync(turnContext).ConfigureAwait(false);
        await conversationState.SaveChangesAsync(turnContext).ConfigureAwait(false);
    };

    return adapter;
});`

**Comment by Danieladu** [comment] 2021-01-25 06:36
Personal think It has nothing to do with this, I also have two adapters.
Could you share the CardDevezas/runtime/azurefunctions folder with me?
It may help to anchor the issue

**Comment by igordevezas** [comment] 2021-01-25 08:29
@Danieladu, tks once again for replying it. I believe we are almost there... I am attaching the folder as you requested.

Let me know if you need something else...

[azurefunctions.zip](https://github.com/microsoft/botbuilder-dotnet/files/5865212/azurefunctions.zip)

**Comment by Danieladu** [comment] 2021-01-26 07:31
I have used the `azureFunction` file you provided and still could not reproduce this issue. Is this possible that the TTL is too long that the bot has reconnected several times so that the Facebook channel gets many same messages? Because I notice that there are many calls that take a long time. (duration > 10s)
I suggest you change the AzureFunction Location or service plan to reduce the TTL, to see if this issue could be solved.

I would continue to follow up on this issue. Thanks.

**Comment by igordevezas** [comment] 2021-01-26 08:28
@Danieladu, this change (changing plan) can be done by the Azure Portal or only by code? Tks!

**Comment by Danieladu** [comment] 2021-01-26 09:07
This could be done by azure Portal.
You could create a `Function App` manually and select the location which is closest to yourself. Then copy the resource name to the settings. Example:
![1](https://user-images.githubusercontent.com/7289268/105823873-ac2b9e80-5ff8-11eb-83e2-02c23ef4cfa1.PNG)


Not surprisingly, the delay of TTL should be small. Here is my screenshot:
![Capture](https://user-images.githubusercontent.com/7289268/105824027-d3826b80-5ff8-11eb-9c68-e29aeac92469.PNG)

**Comment by igordevezas** [comment] 2021-01-26 09:26
I was inserting the name of my Function app "ngt-composer-dotnet" inside the field "name", not "hostname" on the publish profile. Maybe this is the issue? Or you are telling me to create another function app and mantain the "ngt-composer-dotnet" one?

**Comment by Danieladu** [comment] 2021-01-26 11:20
I have checked the code that `hostname ? hostname : name + (env ? '-' + env : '')`, so, if the environment property is empty, hostname equals to name.
I just suspect that the location of the Function app is the cause (TTL is tooo long. > 10s), but it cannot be changed directly, it needs to be deleted and rebuilt. So, maybe this is the cause.

**Comment by igordevezas** [comment] 2021-01-26 15:12
I created a new one with Elastic Premium plan, I changed the location to France Central (I am based on Barcelona, Spain) and nothing changed..

![image](https://user-images.githubusercontent.com/1262003/105863472-3839c800-5ff1-11eb-9578-4f156b62f1cc.png)

**Comment by Danieladu** [comment] 2021-01-27 02:03
Hmmm. I have no enough knowledge about how to reduce the delay time.
And, I just guess it is related to the retry policy of the Facebook channel.
@JonathanFingold You are the expert on Facebook Adapter, Could you take a look? Thanks.

**Comment by Danieladu** [comment] 2021-01-27 02:13
Also, I found this one: https://stackoverflow.com/questions/40842989/facebook-messenger-chatbot-gives-duplicate-replies
You could double-check whether you only subscribe to one bot to your Facebook page at most.

**Comment by igordevezas** [comment] 2021-01-27 09:12
Since I am using Facebook Workplace, there is no instance inside Facebook Developers, but I do have 2 events on my webhook

![image](https://user-images.githubusercontent.com/1262003/105969027-13dcfa80-6088-11eb-8b91-8a958656db67.png)

**Comment by Danieladu** [comment] 2021-01-28 01:40
I think I can try this "Facebook Workplace" first.

**Comment by igordevezas** [comment] 2021-01-28 08:58
@Danieladu igor.devezasdasilva@es.nestle.com

**Comment by Danieladu** [comment] 2021-01-28 09:29
I have scheduled the meeting. Feel free to contact me if there are any concerns.

**Comment by Danieladu** [comment] 2021-02-01 09:00
We have synced with this issue and basically locate the cause of the repeated messages. Which is latency. 

Would continue investigating.

**Comment by Virtual-Josh** [comment] 2021-02-11 18:34
Hey @Danieladu are there any updates on this ticket? Can we close it, or is there still more work to do?

**Comment by Danieladu** [comment] 2021-02-14 01:22
Close it. For we have provided a solution or possible cause for the customer. 
@igordevezas If there are more contexts, we can continue to discuss under this issue.

**Closed by Danieladu** 2021-02-14 01:22 UTC
Labels: Area: Adaptive, Bot Services, bug, customer-replied-to, customer-reported
