### ISSUE TITLE
[Adaptive] dynamic index does not work in all expressions - e.g. ArrayProperty in EditArray step

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2041] opened 2019-06-10 20:30 UTC
Expression language supports dynamic property index via foo[bar]. 

This works fine in LG but does not work in all places expressions are allowed. E.g. in ItemProperty of EditArray step. 

See [here](https://github.com/microsoft/botbuilder-dotnet/blob/9e42392ee992870023c5c834affe6210415d85f0/samples/Issue%20repros/Dynamic%20property%20in%20array/Dialogs/main.dialog#L18) for a sample. 

```user[user.listType]``` works in the LG expression but ```user.{user.listType}``` is what works in dialog property.

**Comment by carlosscastro** [comment] 2019-06-26 04:32
@boydc2014  and @tomlm please sync up on this one, seems like we havve to decide the right solution and then just execute.

**Comment by boydc2014** [comment] 2019-06-27 03:34
user.age[listType]
property(user.age, listType)

**Comment by carlosscastro** [comment] 2019-07-02 17:30
Notes from Dong

    there is no difference of expression in LG and expression engine
    LG depends on expression
    this issue is actually says
 what works in LG/ExpressionEngine (user[list.type]) is different what works in dialog property (user.{list.Type})
    the issue is for Tom, per my last check with Vishwac, the property fix to me, is remove the support of user.{list.type} in dialog, and stick to one syntax user[list.type]
    
user.{list.type} is not a valid expression in my understanding, but somehow we do some magic to support that in dialog

**Comment by tomlm** [comment] 2019-07-02 18:14
The issue is that we need to evaluate the property as an expression for both GET and SET operations. 

I think the right way to solve this is to add support **in the expression class only** for setting a value for an expression.


for expression **conversation[user.name]** 

```C#
    // get value
    var (result, error) = exp.TryEvaluate(state);

   // set value 
    exp.TrySet(state, value);
```

I don't think I can do this without writing my own expression parser.

**Comment by chrimc62** [comment] 2019-07-04 01:20
PR #2184 added setPathToValue and has been merged which should enable Tom to use it to fix this issue.

**Closed** 2019-07-07 18:32 UTC
Labels: 4.5, Adaptive, P1
