### ISSUE TITLE
When using the Log to Console action, using an expression only outputs that as literal text

### ISSUE THREAD

**Issue by dmvtech** [microsoft/botbuilder-dotnet#4988] opened 2020-11-17 21:58 UTC
## Describe the bug

Not sure if this is an issue with the SDK or Composer, so starting here.

If you use the `Log to Console` action, then set the Text property to an expression, it doesn't ever evaluate the expression. Additionally, when clicking into the Text field, it prompts/suggests that you can use an expression.

![image](https://user-images.githubusercontent.com/43397658/99454449-483f7800-28db-11eb-8284-49c5bf90ce95.png)

Using string interpolation works fine.

## Version

1.2.1

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Add a Log Action
2. Set the Text property to be a valid expression such as `=turn.activity.from.name`
3. Run and test, the value will only be that literal text: `=turn.activity.from.name`
4. String interpolation such as `${turn.activity.from.name}` works as expected/desired.

## Expected behavior

Either the expression gets evaluated to the value it should be, or it should not allow/suggest to use an expression. Additionally, information tool-tip should inform this should be only text.

## Screenshots

![console_log_1](https://user-images.githubusercontent.com/43397658/99454740-b08e5980-28db-11eb-8401-dd185800b294.png)
---------------------------------------------------------
![console_log_2](https://user-images.githubusercontent.com/43397658/99454745-b2581d00-28db-11eb-9ac1-1a9ba6a4a5ee.png)

Here is the action:
```
      "actions": [
        {
          "$kind": "Microsoft.LogAction",
          "$designer": {
            "id": "H0JjmG"
          },
          "label": "trace username",
          "traceActivity": true,
          "text": "=turn.activity.from.name"
        }
```
      ]

**Comment by tdurnford** [comment] 2020-11-19 21:29
Transferring to the dotnet repo so they can triage appropriately.

**Comment by mrivera-ms** [comment] 2020-12-05 06:44
@tdurnford, @dmvtech, this behavior is by design. The Text field of LogAction is meant to take a string or an LG expression: [LogAction.](https://github.com/microsoft/botbuilder-dotnet/blob/c7874ebd64fd6f910ea543a47f66adcbc431228d/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/LogAction.cs#L30) 

We can improve the description of the text field in the schema, but the sample expression below is not coming from the SDK: 
![image](https://user-images.githubusercontent.com/44449640/101235957-be84fe00-3681-11eb-9105-4df8a14820fe.png)

**Comment by tdurnford** [comment] 2020-12-07 14:55
@mrivera-ms  In the SDK Schema, `Microsoft.LogActions`'s `text` property is a string expression. Shouldn't it take a string or an expression that resolves to a string? Is there a difference between an expression and an LG expression - if so, we'd need a way to distinguish between the two in the SDK Schema?

**Comment by mrivera-ms** [comment] 2020-12-08 04:34
@tdurnford, yes the schema needs to be changed. I will submit a PR with the correction.

**Closed** 2020-12-11 22:58 UTC
Labels: Area: Adaptive expression, bug
