### ISSUE TITLE
MicrosoftAppCredentials doesn't utilize HttpClient set in BotFrameworkOptions

### ISSUE THREAD

**Issue by lynn-orrell** [Microsoft/botbuilder-dotnet#1242] opened 2018-12-14 20:29 UTC
## Version
4.2

## Overview
The `HttpClient` property that can be set in `BotFrameworkOptions` isn't honored in `MicrosoftAppCredentials`.

## Reference
Here is where the HttpClient is instantiated in `MicrosoftAppCredentials`
https://github.com/Microsoft/botbuilder-dotnet/blob/79339fe77935dc37bcd48df93a43f77596ea4048/libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs#L37

And here is where it is used 
https://github.com/Microsoft/botbuilder-dotnet/blob/79339fe77935dc37bcd48df93a43f77596ea4048/libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs#L327

## Suggested Solution
Update `BotFrameworkAdapter.GetAppCredentialsAsync()` to pass the `HttpClient` from `BotFrameworkOptions` into the constructor of `MicrosoftAppCredentials`
https://github.com/Microsoft/botbuilder-dotnet/blob/79339fe77935dc37bcd48df93a43f77596ea4048/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L862-L881

**Comment by cleemullins** [comment] 2019-01-07 21:42
I looked at this, and the code is wrong. This entire section of code is due to be repalced by @carlosscastro as part of integrating the AAD update changes. 

@carlosscastro Can you chime in with a time frame for when that will on the daily build server?

**Comment by cleemullins** [comment] 2019-01-29 20:00
@carlosscastro I believe this is now fixed in 4.2.1. Can you confirm, and close this?

**Comment by cleemullins** [comment] 2019-01-29 21:47
Confirmed fixed via @carlosscastro

**Closed by cleemullins** 2019-01-29 21:47 UTC
Labels: 4.3, Approved, Bug, Triaged
