### ISSUE TITLE
Empty LG template returns null instead of empty string

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4565] opened 2020-09-01 20:03 UTC
## Version
4.11.0-dev.20200901.8b7db50

## Describe the bug
An empty template returns "null" rather than an empty string.

## To Reproduce
With this template if you call test(), you will end with "This is null" rather than "This is".  If 'foo' is ${''} you get the same result, but if you make it ${' '} it will return a space.

```
# foo()
-

# blah(x)
- This is ${x}

# test()
- ${blah(foo())}
```

## Expected behavior
An empty template should be an empty string.

**Comment by Danieladu** [comment] 2020-09-04 02:30
Hi @chrimc62,  This issue supposed to be fixed in the latest daily package. The fix pr is here: #2710 Although this is a minor change in this PR.
The root cause is that LG misused the "null" judgment. `if(value)` should be `if (value !== undefined)`,
so, if the result is an empty result, LG would misjudge that this variable does not exist in the memory.

Anyway, this is a bug that only occurs when using the empty LG result as the parameter of another template and has no effect on direct calls.

**Closed** 2020-09-04 02:30 UTC
Labels: Area: LG, bug, needs-triage
