### ISSUE TITLE
Proactive Messaging ContinueConversationAsync is not usable without AppId

### ISSUE THREAD

**Issue by MarekLani** [Microsoft/botbuilder-dotnet#1401] opened 2019-02-26 15:56 UTC
## Version
4.2.2.0

## Describe the bug
Adapter.ContinueConversationAsync method requires AppId not to be empty. This behavior is not in pair with Node.js SDK where the proactive messaging works  without providing AppID when calling continueConvrrsationAsync. Based on investigation of Node.js SDK, AppID should even not be input parameter for ContinueConversationAsync, as it should be resolved by framework itself.

## To Reproduce
See above

## Expected behavior
Parity with Node.js SDK

[bug]

**Comment by ceciliaavila** [comment] 2019-03-15 18:12
Hi @Stevenic,
If you agree, we can help you tackle this issue.  We have been analyzing it and we found a possible solution that does not introduce breaking changes.

**Comment by Stevenic** [comment] 2019-04-11 22:17
This issue is on the C# side of things and has to do with the fact the C# adapter wants to support multiple bots for a single adapter.  The JS adapter is designed such that you need a separate adapter for each bot.

**Comment by cleemullins** [comment] 2019-04-22 21:24
I think the existing behavior here is Fine for us to live with for this iteration.

**Comment by cleemullins** [comment] 2019-04-22 21:28
As Steven said, the design goals of the adapters are different. I'm going to close this as "By Design" at this time.

**Closed by cleemullins** 2019-04-22 21:28 UTC
Labels: 4.4, Approved, Bug, Parity with JS Required, Triaged
