### ISSUE TITLE
[Adaptive] EndOfTrigger action

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3568] opened 2020-03-15 02:29 UTC
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by tomlm** [comment] 2020-03-15 21:28
this is just the template, I think this is a duplicate of #3569

**Closed** 2020-03-15 21:28 UTC
