### ISSUE TITLE
LUIS datetime parsing issue

### ISSUE THREAD

**Issue by KayMKM** [Microsoft/botbuilder-dotnet#1060] opened 2018-10-25 04:06 UTC
## Version
4.0.7

## Describe the bug
LUIS will return the start and end of time range:
`"entities": [
    {
      "entity": "may 2nd to may 5th",
      "type": "builtin.datetimeV2.daterange",
      "startIndex": 0,
      "endIndex": 17,
      "resolution": {
        "values": [
          {
            "timex": "(XXXX-05-02,XXXX-05-05,P3D)",
            "type": "daterange",
            "start": "2017-05-02",
            "end": "2017-05-05"
          },
          {
            "timex": "(XXXX-05-02,XXXX-05-05,P3D)",
            "type": "daterange",
            "start": "2018-05-02",
            "end": "2018-05-05"
          }
        ]
      }
    }
  ]`
But BF SDK didn't return the start and end property. Is this by design?

Edit:
Also the date/time/datetime have the same issue:
`"entities": [
    {
      "entity": "may 2nd",
      "type": "builtin.datetimeV2.date",
      "startIndex": 0,
      "endIndex": 6,
      "resolution": {
        "values": [
          {
            "timex": "XXXX-05-02",
            "type": "date",
            "value": "2017-05-02"
          },
          {
            "timex": "XXXX-05-02",
            "type": "date",
            "value": "2018-05-02"
          }
        ]
      }
    }
  ]`

**Comment by johnataylor** [comment] 2018-10-29 17:21
This looks like a bug in the LUIS recognizer.

Those values are in the LUIS response and should be available as they are with the DateTimePrompt.

An alternative (and more flexible) solution is to base your program logic on the TIMEX array. The problem is TIMEX can be awkward to deal with directly. To work with TIMEX values it is best to use the TimexExpression value.

For the TimexExpression library see:

https://github.com/Microsoft/Recognizers-Text/tree/master/.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression

(Documentation and samples are behind here. But there are many illustrative unit tests.)

The package is published here:

https://www.nuget.org/packages/Microsoft.Recognizers.Text.DataTypes.TimexExpression/

**Comment by johnataylor** [comment] 2018-10-31 00:10
We have also added a new sample showing TIMEX manipulation:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/40.timex-resolution

**Comment by johnataylor** [comment] 2018-11-06 21:10
The decision is that the missing fields in the results is "by design" and we think you should use the TIMEX library. If you can't easily create the missing fields you wanted in the result from the TIMEX values using the Timex Expression classes then open a bug on that.

Basically using the TIMEX library is going to lead to a much more robust implementation. There can be a lot of ambiguity even in the simplest of scenarios and working with the TIMEX is helpful.

Closing this issue now.

**Closed by johnataylor** 2018-11-06 21:10 UTC
Labels: 4.2, Bug, Triaged
