### ISSUE TITLE
invalid value for Date Prompt will cause infinite loop

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botbuilder-dotnet#3720] opened 2020-04-09 10:31 UTC
## Describe the bug
When I configure the default value as "30" for Date Prompt, it is a invalid value. But I this will cause an infinite loop when I chat with the bot.
![image](https://user-images.githubusercontent.com/44257569/78885945-04a4a600-7a90-11ea-8ce1-72bdf0e99217.png)
![image](https://user-images.githubusercontent.com/44257569/78886013-21d97480-7a90-11ea-8dee-c3b7152119b1.png)

## Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

**Comment by luhan2017** [comment] 2020-04-10 06:32
I tried to debug this and found this is actually an expected behavior in the current set up. 

The prompt will
1. check for this.Property.
2. then check for this.Value.
3. check for activity.text then activity.value. 

If this.Value is invalid in this round, it could become another value in next round....
The only thing we can do is to send an error message if the value is invalid? 

@vishwacsena , any thought on this?

**Comment by vishwacsena** [comment] 2020-04-10 16:42
@luhan2017 yes, I believe a reasonable way to catch this would be through validation. Resolving this since there is no product change expected here.

**Closed by vishwacsena** 2020-04-10 16:42 UTC
Labels: adaptive
