### ISSUE TITLE
Strange behavior of SetProperty and UtcNow

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4223] opened 2020-07-03 08:20 UTC
## Version
What package version of the SDK are you using.

ec8a15c5b177452e126ac0242ea28942bdea1a13

## Describe the bug
Give a clear and concise description of what the bug is.

When using SetProperty with utcNow, the saved value is not string as described in document here https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#utcnow

See demo code https://github.com/microsoft/botbuilder-dotnet/compare/master...xieofxie:hualxie/utcbug

## To Reproduce
1. Clone https://github.com/xieofxie/botbuilder-dotnet/tree/hualxie/utcbug
2. Run Action_SetProperty test
3. It should not work

## Expected behavior
Don't change type for datetime string when setproperty.

[bug]

**Comment by Danieladu** [comment] 2020-07-06 03:55
Yes. It is a known bug. Caused by the C# deserialization tool when deserializing the DateTime string.

**Comment by xieofxie** [comment] 2020-07-06 04:06
That's crazy.. Do we have an issue in dotnet library?

**Comment by compulim** [comment] 2020-07-13 18:10
@tomlm Could you look at this one?

**Comment by compulim** [comment] 2020-07-13 18:11
@vishwacsena Could you look at this one?

**Comment by xieofxie** [comment] 2020-07-14 02:08
Yeah.. The main issue is `SetProperty` will change the type of a DataTime string to DataTime as the following:
![image](https://user-images.githubusercontent.com/2876650/87372367-f1870200-c5b9-11ea-95d5-dc7cb2dffc86.png)

![image](https://user-images.githubusercontent.com/2876650/87372349-e502a980-c5b9-11ea-8b29-6bb56630b2f6.png)

**Comment by vishwacsena** [comment] 2020-07-15 19:34
@Danieladu can you comment on path to resolution here? Do we have a dependent bug/ issue we need to track?

**Comment by Danieladu** [comment] 2020-07-16 00:39
> @Danieladu can you comment on path to resolution here? Do we have a dependent bug/ issue we need to track?

I probably know the cause of this issue, but have no idea how to fix it appropriately. 
Maybe ban all DateTime parsing for the whole solution? Just use :
```
new JsonSerializer {
   DateParseHandling = DateParseHandling.None
});
```
Or make some patch up for the places with Serialization/Deserialization of `DateTime`?
Or other solutions...

Maybe @tomlm can participate in the discussion and give some comments.

**Comment by boydc2014** [comment] 2020-08-27 06:07
I will vote for disable the auto-conversion of json converter.  cc @tomlm

**Comment by mrivera-ms** [comment] 2020-09-17 17:55
@vishwacsena , please prioritize and assign this item to a milestone. We need to get a resolution on the best course of action. Thanks.

**Comment by mrivera-ms** [comment] 2020-09-29 03:20
This is a duplicate of #4522 . Closing issue.

**Closed by mrivera-ms** 2020-09-29 03:20 UTC
Labels: Area: Adaptive, bug, needs-team-attention
