### ISSUE TITLE
Enable TestingMiddleware to introduce randomization when writing declarative test transcripts

### ISSUE THREAD

**Issue by ryanlengel** [microsoft/botbuilder-dotnet#5202] opened 2020-10-30 20:24 UTC
microsoft/botframework-composer#3889 has the feature request to include a SetTestOptionsMiddleware in the default runtime. A convenient way to generate new tests is to create a transcript using the Emulator and turning that into a test script. However, randomness in bot responses make it impossible to replay the same transcript.
To resolve this, the SDK has:

> - Defined [TestingMiddleware](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/TestingMiddleware.cs) in Microsoft.Bot.Builder (Inspection) to pick up a SetTestOptions custom event and copy the payload into conversation.testOptions. We made the payload open ended.
>  - Defined [randomSeed](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/AdaptiveExpressions/Extensions.cs#L65) to seed a random number generator or randomValue to return a constant value from all calls to random and adjusted all users of random to make use of that.
> - Defined a bf plugin that converts a transcript into a test script that supports the history and mocking.

Evaluate enabling this in the Adaptive Runtime as a middleware to enable in runtime configuration, included in whatever block of work is focused on enabling bot unit tests.

**Comment by chrimc62** [comment] 2021-04-13 21:21
Big rocks agreed to rename it to TestingMiddleware in order to have a place to put testing stuff and treat it in the same way we do inspection middleware in terms of the package it is in and the namespace.

**Comment by clearab** [comment] 2021-06-01 19:46
I like the idea of making this a component to give developers additional control to turn this on/off. As a component, you could easily include it in dev/test environments, but not deploy to your production environment.

**Comment by tracyboehrer** [comment] 2021-06-05 17:47
#5077 has a PR.  That PR just moves this middles out of Adaptive.Testing (preview) and into Bot Builder.

This issue will need to resolve how to make it available to runtime.  I am leaning somewhat to adding a feature flag.  There is an issue of where to put the BotComponent if we want to go that route.  In either case, this middleware could be enabled in appsettings.development.json to avoid it being in a production bot.

**Comment by clearab** [comment] 2021-06-05 18:44
This definitely needs to be configurable - distributing as a package seems like a good way to accomplish that. If we want to leave it in the SDK, we'll need to make Composer UI changes to provide a toggle on the settings page, and update the CI/CD guidance to recommend using a JSON transform to disable it before deploying to production.

**Comment by cleemullins** [comment] 2021-06-16 22:04
We have agreed on multiple occasions to move away from transcript based testing. They are difficult to debug, hard to maintain,  and lead directly to huge PRs with hundreds of files changed. Are we sure adding more features to a story we're moving away from is the right choice? 

@johnataylor I'm assuming as this is both Middleware and Transcript Testing that you're in favor. Can you please add your reasoning here so we can discuss?

**Comment by johnataylor** [comment] 2021-06-19 04:04
Couple of things, yes absolutely the transcript based testing is absolutely not appropriate for the checkin tests or unit tests or anything at that level. They are no substitute for designing the code for testing, carefully crafting the test cases with mocks and injection and carefully make appropriate assertions. Perhaps there is a role in some functional test scenario. If the high level end to end functional test is what is desired then sure, that may be useful but lets not confuse that with regular testing. Can we completely decouple the functional tests, for example, aren't they in a completely different repo?

Specifically with regards to the middleware, we discussed this, its a couple of lines of code in the adaptive dialog bot to flip a setting, there is no need for the noise and complexity of making it a middleware. I realize its a simple middleware, but it is also pointless and these things just add up over time.

**Comment by tracyboehrer** [comment] 2021-06-21 13:27
This is likely a duplicate of https://github.com/microsoft/botbuilder-dotnet/pull/5628.  Will close this one if that issue/PR is agreed on.

**Comment by tracyboehrer** [comment] 2021-06-22 19:33
Closing.  No longer needed due to how #5077 was implemented.  SetTestOptions handling is always on in the AdaptiveDialogBot.

**Closed by tracyboehrer** 2021-06-22 19:33 UTC
Labels: Area: Runtime, P5, feature-request
