### ISSUE TITLE
[tracking] ConfirmPrompt not working in German, Chinese and French

### ISSUE THREAD

**Issue by PhilThome** [Microsoft/botbuilder-dotnet#823] opened 2018-08-07 14:44 UTC
Hi,

I use a ConfirmPrompt to use with German:

Dialogs.Add("confirmPrompt", new ConfirmPrompt(Culture.German));

and would expect it to understand "Ja" or "Nein" (which mean "Yes" or "No"). It doesn't. :-) 
Could you please tell me if it supports German? Or how it works? 

Thanks,
Phil

**Comment by johnataylor** [comment] 2018-08-16 15:44
It should support German and will do soon. The issue is that the _prompt_ delegates the parsing work to an underlying _recognizer_ component. (The _recognizer_ is the same code that is used internally in LUIS, that's important because you will see consistent results.)

Currently the recognizer does not support German, but it will do soon, the work is currently being done. I've contacted the team and I'll update this issue with a time line if I get one.

For reference the recognizer repo can be found here: https://github.com/Microsoft/recognizers-text

**Comment by johnataylor** [comment] 2018-08-16 17:37
The rcognizer repo issue is here https://github.com/Microsoft/Recognizers-Text/issues/796

**Comment by johnataylor** [comment] 2018-08-16 17:38
Added unit tests for localization - disabled the tests for German, Chinese and French

**Comment by johnataylor** [comment] 2018-10-10 00:11
Chinese and Dutch are added in Recognizers.Text 1.1.1 release.
Still missing German and French.

**Comment by johnataylor** [comment] 2018-10-18 18:29
fixed with #1034

**Closed by johnataylor** 2018-10-18 18:29 UTC
Labels: Next-Iteration, bug
