### ISSUE TITLE
IRecognizerConvert.TopIntent() returns wrong value

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#796] opened 2018-07-26 16:59 UTC
Against daily build v4.0.0.36972

The following code should return a top intent of **Reservation**; however, it is returning **None**.

```cs
// Use LUIS to extract intent from the user's input text.
var result = await this.Recognizer.RecognizeAsync<CafeLuisModel>(context, CancellationToken.None).ConfigureAwait(false);

// Handle the user's input based on the extracted intent.
var topIntent = result.TopIntent();
switch (topIntent.intent)
```

Here's runtime info from a breakpoint:

![image](https://user-images.githubusercontent.com/35047199/43276530-c968f85a-90b9-11e8-9142-3aa1006532fd.png)

**Comment by JonathanFingold** [comment] 2018-07-27 18:15
Narrowed this down further. It is an issue with the model I had generated from the LuisGen tool. **RecognizerResult** has changed.

**Comment by stevengum** [comment] 2018-07-30 21:37
@jonathanFingold what is your current status; are you still blocked? Are you using [`GetTopScoringIntent()`](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/RecognizerResultExtensions.cs#L18)?

**Comment by JonathanFingold** [comment] 2018-07-30 22:11
Maybe? The LuisGen tool doesn't produce a code file appropriate to the current state of the daily NuGets. I'll need a version that does so  in order to update the documentation that should go live when we update the public NuGets.

LuisGen currently produces a class that provides a `TopIntent()` method (which doesn't call `GetTopScoringIntent()`).

**Comment by cleemullins** [comment] 2018-09-11 22:49
@Zerryth Please take a look at this and see if you can resolve. You may have to work with @chrimc62 to drive resolution.

**Comment by Zerryth** [comment] 2018-09-11 22:51
@cleemullins Will do, Chris! Investigating...

**Comment by Zerryth** [comment] 2018-09-13 18:27
@JonathanFingold Could you please let me know what steps  you are doing precisely to yield the undesired results? 

I have done the following and **successfully got Reservation as an intent**, and have not be able to repro your issue

1. Using your example from [this branch here](https://github.com/Microsoft/BotFramework-Samples/tree/contosocafe-v4-dotnet/docs-samples/V4/dotnet/ContosoCafe/ContosoCafe-5-DialogsWithLUISEntities), I added packages from daily build v4.0.0.36972

2. Using the emulator I send in the utterance "book a table"
![image](https://user-images.githubusercontent.com/35248895/45507817-f1144a80-b747-11e8-9e44-8c076afa0666.png)

3. Both result has intent score for "Reservation" as the top-scoring intent as well as your variable "intent" is properly being set to "Reservation"

![image](https://user-images.githubusercontent.com/35248895/45507751-ce823180-b747-11e8-8952-91ecbf20af3c.png)

**Comment by Zerryth** [comment] 2018-09-13 18:33
One small note is that I did have to switch from `AI` to `Ai` though in a few `using `statements in  your sample code.
For example instead of `using Microsoft.Bot.Builder.AI.QnA` use using `Microsoft.Bot.Builder.Ai.QnA`

**Comment by JonathanFingold** [comment] 2018-09-13 18:42
@Zerryth , I will try to get to this today or tomorrow, but we're busy trying to get/keep the docs up to date for Ignite.

**Comment by carlosscastro** [comment] 2018-09-15 18:09
I tried to reproduce and everything seems to be working ok. @JonathanFingold if you have a specific model for which you see a repro with the latest bits, please attach it / link it to the bug and reactivate - we'll take a look. In the meantime, closing because we cannot repro the issue, since likely it was fixed since you first saw it. Thanks!

**Closed by carlosscastro** 2018-09-15 18:09 UTC
Labels: Approved, Next-Iteration, bug

**Comment by JonathanFingold** [comment] 2018-09-17 15:48
@carlosscastro , Sounds good, thanks.
