### ISSUE TITLE
Templates.ParseText returns an error for legit lg content

### ISSUE THREAD

**Issue by Robulane** [microsoft/botbuilder-dotnet#5514] opened 2021-04-21 18:05 UTC
## Version
What package version of the SDK are you using.
4.11.1.0

## Describe the bug
Templates.ParseText method returns an error for the following template:

```
# example()
> To learn more Adaptive Cards format, read the documentation at
> https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots
- ```
${json({
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "default text",
      "weight": "bolder"
    }
  ]
})}
{replace this with triple `}
```

## To Reproduce
1. Call Templates.ParseText() and inspect Diagnostics list

## Expected behavior
No errors

**Comment by Danieladu** [comment] 2021-04-22 07:20
Hi, @Robulane. I use your content but could not reproduce this issue. And the diagnostic list is empty. Could you provide the full LG file, lest I miss some special non-printable characters? Thanks.

**Comment by Robulane** [comment] 2021-04-22 14:07
Hm... strange, this is what I am getting:

![image](https://user-images.githubusercontent.com/55888168/115728407-c8837100-a384-11eb-8146-0ac50807860b.png)

This is the value of content:
"\r\n\r\n# example()\r\n> To learn more Adaptive Cards format, read the documentation at\r\n> https://docs.microsoft.com/en-us/adaptive-cards/getting-started/bots\r\n- ```\r\n${json({\r\n  \"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",\r\n  \"version\": \"1.2\",\r\n  \"type\": \"AdaptiveCard\",\r\n  \"body\": [\r\n    {\r\n      \"type\": \"TextBlock\",\r\n      \"text\": \"default text\",\r\n      \"weight\": \"bolder\"\r\n    }\r\n  ]\r\n})}\r\n```"

**Comment by Danieladu** [comment] 2021-04-23 03:22
hi @Robulane I found that there is a backslash after schema url:
```
 "$schema": "http://adaptivecards.io/schemas/adaptive-card.json\",
```
That would break the json.
Could you please remove it and try again?

**Comment by Danieladu** [comment] 2021-04-28 03:01
Another tips: there is no need to write `json()`, because the parameter itself is json.
`json` function originally aims to convert json string into a json structure.
So, your template could be 
```
# getJson
- ${json(example())}

# example()
- ```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "default text",
      "weight": "bolder"
    }
  ]
}```
```
or just simplified with:
```
# example()
- ${{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "default text",
      "weight": "bolder"
    }
  ]
}}
```

**Comment by Danieladu** [comment] 2021-05-11 23:01
yes. I think so.

**Comment by Danieladu** [comment] 2021-05-12 03:44
Close it. @Robulane If the solution has not solved your problem or need further discussion, please leave a message under this issue. Thanks！

**Closed by Danieladu** 2021-05-12 03:44 UTC
Labels: P1, PVA, Size: S, bug
