### ISSUE TITLE
Inject DialogContext to BoolExpression

### ISSUE THREAD

**Issue by melih154** [microsoft/botbuilder-dotnet#4795] opened 2020-10-14 09:07 UTC
**Is your feature request related to a problem? Please describe.**
On adaptive dialogs, I am trying to implement custom validation (eg. Calling external API with user input as parameter), custom retry message based on the response of API and store validation result on conversation state.

**Describe the solution you'd like**
I would like BoolExpression to have a method that accepts `Func<object, DialogContext, object>`, an addition of DialogContext to existing method [here](https://github.com/microsoft/botbuilder-dotnet/blob/3a0dcfee003a7fcd0271c6336ab2c166f9a74313/libraries/AdaptiveExpressions/ExpressionProperties/BoolExpression.cs#L56)

This way, I would be able to access `ConversationState `via `dc.Context.TurnState.Get<ConversationState>()` (not injecting ConversationState to dialog) and save validation result on `ConversationState `by creating property state accessors and calling `SetAsync` method

**Describe alternatives you've considered**
- Storing ConversationState to dialog class: Still does not have access to DialogContext and TurnContext.

Haven't tested storing DialogContext, as I thought changes on DialogContext between it is stored and custom validation not reflected on DialogContext.

**Comment by ryanlengel** [comment] 2020-10-14 18:33
@mrivera-ms can you please take a look at this issue? Thank you!

**Comment by stevengum** [comment] 2020-10-19 20:56
@mrivera-ms this seems like a reasonable request. Should this go into the R12 milestone? Or are there some combination of labels required to get it on the books for triaging/planning that would be preferred?

**Comment by chrimc62** [comment] 2020-10-21 18:25
@melih154 is there a reason you can't store the result of your API call by setting a value in the existing state memory contexts (turn, dialog, user, conversation) either directly using dc.State.SetProperty or declaratively through the SetProperty action and then have your boolean expression refer to those?  

There are two design considerations here:
1) AdaptiveExpressions are a lower level in the stack and by design know nothing about DialogContext--they just know about resolving memory paths in a state object.
2) AdaptiveExpressions are purposefully kept non-async to keep their evaluation as lightweight and side-effect free as possible.

**Comment by melih154** [comment] 2020-10-21 20:05
Thanks @chrimc62 . I understand design considerations.

Please find below my requirements, I think it is a common requirement.

- Bot should ask question
- User should answer question
- Answer should be validated from an external API or through a CodeAction (calling another class)
- If validation fails, then bot should repeat question for defined max turn count


I am trying to find a simple way to implement this behaviour as I have to implement this on 10+ dialogs with each having 2+ TextInput with external validation.

- Nice to have: As defined on original request for Text Input code validation to have access to DialogContext, so when validation succeed, additional data returned from External Validation API will be stored on Conversation Data. TextInput will have MaxTurnCount defined.

- Current implementation:  Within an adaptive dialog using below steps. MaxTurnCount behaviour not implemented yet. I guess have to implement with a conversation property storing turn count.

Step 1: Text Input
Step 2: Code Action (do validation external API call, store API result on conversation state)
Step 3: If Condition: conversation.validationResult.succeed != true => SendActivity and CancelAllDialogs

**Comment by chrimc62** [comment] 2020-10-21 23:10
@tomlm Could you comment on this?

**Comment by tomlm** [comment] 2020-10-23 22:03
Have you considered registering a custom function with adaptiveExpressions?

```
{
    validation: [
       "=myfunc(dialog.foo)"
...
}
```

**Comment by tomlm** [comment] 2020-10-23 22:10
You can't do this declaratively with our current classes, but you can do this easily with custom classes.

For example, if you create a new class which derives from NumberInput and overrides OnRecognizeInputAsync() then you have access exactly to what you need to do your validatation, the dc and async\<task>.

```c#
        /// <summary>
        /// Called when input has been received, override this method to customize recognition of the input.
        /// </summary>
        /// <param name="dc">dialogContext.</param>
        /// <param name="cancellationToken">the <see cref="CancellationToken"/> for the task.</param>
        /// <returns>InputState which reflects whether input was recognized as valid or not.</returns>
        protected abstract Task<InputState> OnRecognizeInputAsync(DialogContext dc, CancellationToken cancellationToken);
```

Something like this:

```
public class PartNumberInput : NumberInput
{
   // part number database connectionstring
   public StringExpression ConnectionString { get;set;} 
   
   protected override Task<InputState> OnRecognizeInputAsync(DialogContext dc, CancellationToken)
   {
       // call number database to validate
       return InputState;
   }
}
```

Register it as a custom component and now you have rich partnumber input with async validation.

**Closed** 2020-10-24 17:17 UTC
Labels: Bot Services, customer-replied-to, customer-reported, feature-request
