### ISSUE TITLE
Potential Breaking change: OnBeginDialogAsync gets invoked instead of OnContinueDialogAsync

### ISSUE THREAD

**Issue by dawwa** [microsoft/botbuilder-dotnet#5870] opened 2021-08-10 08:05 UTC
## Version
Upgrading from 4.12.3 to 4.13.2

## Describe the bug
This is observed from bots created from VA and Skill templates.
In Skill's `MainDialog.cs`, there are the `OnBeginDialogAsync` and `OnContinueDialogAsync` methods, after upgrading to 4.13.2 libs, the `OnBeginDialogAsync` gets invoked again when `OnContinueDialogAsync` is supposed to get called.

Could this behavior change be due to some potential breaking changes from 4.13.x version?

e.g.,
```cscharp
        // Runs when the dialog is started.
        protected override Task<DialogTurnResult> OnBeginDialogAsync(
            DialogContext innerDc,
            object options,
            CancellationToken cancellationToken = default) => this.OnBeginOrContinueDialogAsync(true, innerDc, options, cancellationToken);

        // Runs on every turn of the conversation.
        protected override Task<DialogTurnResult> OnContinueDialogAsync(
            DialogContext innerDc,
            CancellationToken cancellationToken = default) => this.OnBeginOrContinueDialogAsync(false, innerDc, null, cancellationToken);
```

## Behavior

For a scenario of asking Bot a question and then click a button on the card Bot responded.
 - Behavior on referencing  4.12.3 SDK libs:
   - the `OnBeginDialogAsync` gets called for posting the card.
   - the `OnContinueDialogAsync` gets called after user clicks the button on the posted card as a continuous action.
 - Behavior on referencing  4.13.2 SDK libs without any other code change:
   - the `OnBeginDialogAsync` gets called for posting the card.
   - the `OnBeginDialogAsync` gets called again instead of `OnContinueDialogAsync` after user clicks the button on the posted card as a continuous action.

## Additional Context
Based on my testing, the behavior change only happens when 4.13.x is referenced in VA project, e.g., as long as VA is with 4.12.x lib, even the Skill project upgrades the SDK to 4.13.x lib, everything behaves as before.

**Comment by lauren-mills** [comment] 2021-08-30 18:19
@mrivera-ms - @dawwa's issue is in the SDK code in 4.13.2+. Could you assign to someone who can help explain the behavior change he is seeing where OnBeginDialog is being called instead of the OnContinueDialog method? I'm not sure of the design from the SDK side so I can't explain why that change was made when the SkillIdConversationFactory code was moved over and how he might work around it. He is trying to update to the latest versions of the code, but can't because this skill behavior is not working as expected.

**Comment by EricDahlvang** [comment] 2021-08-30 19:25
Looks related to this change:

![image](https://user-images.githubusercontent.com/11055362/131393564-40dabe78-d3f2-4b0b-a65c-ce9a5a997153.png)

**Comment by gabog** [comment] 2021-08-31 16:38
Hi, I don't think this is a bug in the SDK, you should be getting a new conversation ID every time you start an interaction with a skill, even if it is a skill you already talked to or you are talking to, there may be an issue on MainDialog.cs or somewhere else. Do we have a small sample that reproduces the issue that I can look at?

**Comment by gabog** [comment] 2021-09-14 13:10
Reviewed the code with @dawwa and we determined that the issue was caused by how the main dialog in the root bot was calling the skill. The changes we introduced in the SkillConversationFactory were keeping maindialog from connecting to the same conversation ID with the skill in subsequent calls. 

Closing this one for now, Dawai will work on refactoring the main dialog so the skill conversation is started during the waterfall dialog steps in main dialog and not in the OnBeginConversation/OnContinueConversation overrides in maindialog.

**Closed by gabog** 2021-09-14 13:10 UTC
