### ISSUE TITLE
Throw clear exception when choice prompt strings are too long.

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#5759] opened 2021-07-01 17:39 UTC
re: bot-docs [issue 2102](https://github.com/MicrosoftDocs/bot-docs/issues/2102)
> Basically something breaks but doesn't really throw any Exception when instantiating choices with strings that are too long.
>
> When this happens, no actions get suggested, and during the context.PromptAsync(...) i get back a generic error.
>
> Now that i used shorter strings for choices, everything is correctly working(both in tests and in the live BOT).

Please throw an appropriate exception so this issue is easier for devs to discover and fix in their bots.
- at run-time, when the prompt is run.
- at creation time, when the problematic choices are added to the choice prompt.

**Describe alternatives you've considered**  
The ref docs could also be updated to make this constraint clearer.

**Additional context**  
See bot-docs issue.

**Comment by skommireddi** [comment] 2021-09-22 17:59
I contacted the developer who reported this issue originally and looks like he can't reproduce this issue anymore. Since the original issue Is there a way i can test for choices? MicrosoftDocs/bot-docs#2102 is not reproducible and we don't have any repro steps from the developer, closing this issue.  Please reopen if this occurs again.

**Closed by skommireddi** 2021-09-22 17:59 UTC
Labels: feature-request, needs-triage
