### ISSUE TITLE
Activity.Text is set to filename and not the message text when sending a Slack message with attachment

### ISSUE THREAD

**Issue by haacked** [microsoft/botbuilder-dotnet#4888] opened 2020-10-30 03:52 UTC
## Version
What package version of the SDK are you using. __4.10.3__

## Describe the bug
When sending a message in Slack with an attachment, the `turnContext.Activity.Text` property is populated with the file name and not the message text.

## To Reproduce
1. Create a bot and connect it to Slack using Azure Bot Service.
2. In Slack, type a message that also includes an attachment.
3. Check out the properties of `turnContext` in `OnMessageActivityAsync`

## Expected behavior
__Expected__ that `turnContext.Activity.Text` is populated with the Slack message ("hey there, here's an attachment" in the screenshot.)
__Actual:__ `turnContext.Activity.Text` is populated with the file name of the uploaded attachment.

## Screenshots
<img width="552" alt="Screen Shot 2020-10-29 at 8 45 06 PM" src="https://user-images.githubusercontent.com/19977/97657710-cb318900-1a27-11eb-8c7e-7a1b545fa40b.png">

## Additional context
I can see the message in `ChannelData`, but I think the current behavior is incorrect. `Text` should be the message. It's already possible to get the attachment filename via the `Attachments` property. For example, if I attach multiple files, the `Text` property is populated with just one of those file names.

**Comment by v-kydela** [comment] 2020-11-02 22:25
@CezaryMarcjan - I've reproduced and confirmed this Slack connector bug. I also tested this with the Slack adapter, and the Slack adapter sets the text to null so that's not any better. In both cases, the bot must check the channel data to get the actual message text that got sent with the attachment. This needs to be fixed in both the Slack connector and the Slack adapter. I'm unassigning myself so that your team can handle this issue.

**Comment by mrivera-ms** [comment] 2021-02-04 05:23
@JuanAr, could you please let us know if this item is in scope for R12?

**Comment by ceciliaavila** [comment] 2021-02-08 21:27
Hi @mrivera-ms,
We reviewed this issue and consider it should be moved to R13.
As @v-kydela mentions, there's a bug in the Slack Azure Bot Service that we can't address, but we can address a similar issue happening in the Slack Adapter.
The Slack Adapter, unlike the Slack Azure Bot Service, returns the messages with attachment as event activities ([IEventActivity](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/IEventActivity.cs)).
The EventActivity doesn't have a text property to populate with the message's text. Instead, it has the Value property, containing all the data from the Slack message. 
We created the draft PR #5175 to add the text property to the [EventType](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Model/EventType.cs#L14) class so it can be properly tracked in the Value and ChannelData properties of the EventActivity, giving the user an easier way of getting the message's text.
If we update the Slack Adapter to return this kind of message as MessageActivity, we could have the exact behavior the user is expecting, but this would represent a **_breaking change_** and we'd like your opinion on this first.

**Comment by v-kydela** [comment] 2021-02-08 22:37
@ceciliaavila - While it would be great to fix this in the adapter as well, shouldn't it also be fixed in ABS because that's what this customer is using?

@craigjensen 
@arturl 
@bwamie 

Can a work item be created to fix this in the Slack service?

**Comment by mrivera-ms** [comment] 2021-02-08 23:02
@v-kydela, I have created a separate issue to track the fix in ABS. Adding @arturl , @craigjensen @bwamie for visibility. 
Also, moving this issue out of the R12 release.

**Comment by compulim** [comment] 2021-02-19 19:20
Looks like there is an ongoing effort on fixing this bug. I am exempting it from DRI.

**Closed** 2021-03-25 20:12 UTC
Labels: Area: Custom adapters, Bot Services, ExemptFromDailyDRIReport, bug, customer-replied-to, customer-reported
