### ISSUE TITLE
LuisRecognizer returns Empty intent with perfect score when there is no utterance

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#4117] opened 2020-06-18 01:27 UTC
## Version
4.9.3

## Describe the bug
The `ValueRecognizer` class is used as a fallback to map submitted adaptive cards to intents for dispatch within your bot. Currently you get an empty string instead of the name of the cards intent due to a [bug on this line](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Recognizers/ValueRecognizer.cs#L61).  This line should be using `property.Name` instead of `property.Value`.

[bug]

**Comment by cleemullins** [comment] 2020-06-18 02:28
@vishwacsena, I'm not sure who to assign this to. Could you re-target as necessary?

**Comment by tomlm** [comment] 2020-06-18 07:39
The issue is the LuisV3Recognizer.

When it has an empty utterance it returns a recognizer result with
```
{
    Text = string.Empty,
    Intent = String.Empty 
    Score = 1.0
}
```

The RecognizerSet merges ValueRecognizer and LuisRecognizer together, but logic is expecting that there will be no intent, an intent, or a 'None' Intent.  Because it finds an EMPTYSTRING intent with a perfect score it ignores the perfect score for the intent that has from the card recognizer.

LuisRecognizerOptionsV3.cs line 112 should be returning a recognizer result with No intents and No Entities.  There is no recognition going on, and it should keep it's nose out of it.
```
                recognizerResult = new RecognizerResult
                {
                    Text = utterance
                };
```

**Closed** 2020-06-18 19:44 UTC
Labels: Adaptive, R10
