### ISSUE TITLE
Getting  'Something went wrong, please try again later.'  error message  after submit in `personal` scope of message extention action preview.

### ISSUE THREAD

**Issue by sudoaccessdenied** [microsoft/botbuilder-dotnet#5391] opened 2021-03-30 11:09 UTC
## Version
What package version of the SDK are you using.
4.12.2
## Describe the bug
I am getting `Something went wrong, please try again later.` Error while using message extension  action preview in personal scope.

## To Reproduce
1. Use the bot builder sample to produce it  [53.teams-messaging-extensions-action-preview](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/53.teams-messaging-extensions-action-preview)
2. Run the bot.
2. Install the manifest provided in the 'TeamsAppManifest'
3. Compose message in personal scope.
4. Submit the Adaptve card.

## Expected behavior
It should not show `Something went wrong, please try again later.` error message.

## Screenshots
![image](https://user-images.githubusercontent.com/30634773/112978307-cad32080-9174-11eb-9719-b0c94cee484c.png)

## Additional context
It is working fine in group and teams scope but it is showing error in personal scope.

**Comment by v-kydela** [comment] 2021-03-31 00:01
Thank you for the report, @sudoaccessdenied 

It looks like the Teams client is throwing an error in your browser. This is almost certainly unrelated to the Bot Builder .NET SDK and should be reported to Teams instead. However, I can still try to reproduce the problem if you clarify the repro steps for me.

In step 2 you say to run the bot and in step 3 you say to install the manifest, but are you filling out the missing information in appsettings.json and manifest.json first? Are you running the bot locally and connecting to Teams using ngrok? That is to say, are you following the instructions in the readme?

**Comment by sudoaccessdenied** [comment] 2021-03-31 06:04
@v-kydela Yes I am running the bot locally usign ngrok and following the instruction in readme.

**Comment by v-kydela** [comment] 2021-04-02 22:29
@sudoaccessdenied - All right, I can reproduce the problem. Despite the instructions in the readme, it looks like this sample is only supposed to work in a team channel and cannot be installed for a user.

@EricDahlvang 
@johnataylor 

Can you comment on whether this sample is meant to work in the personal scope?

**Comment by EricDahlvang** [comment] 2021-04-02 22:39
@v-kydela Please try installing the bot in a Team scope, then see if this functionality works from a personal scope.

**Comment by EricDahlvang** [comment] 2021-04-02 22:42
Actually, the sample does not have the personal scope in the manifest:

```json
  "bots": [
    {
      "botId": "<<YOUR-MICROSOFT-APP-ID>>",
      "scopes": [
        "team"
      ]
    }
  ],
```

**Comment by v-kydela** [comment] 2021-04-02 22:43
@EricDahlvang - Okay, I tried that now. The behavior is the same when attempting to install in personal scope regardless of whether or not the app is already instead in a team scope.

Team scope:

1. Install app
2. The app is installed, and can now be accessed in a team channel

Personal scope:

1. Start to install the app
2. A task module is immediately opened
3. The task module cannot be completed because of the error
4. The app remains uninstalled

**Comment by v-kydela** [comment] 2021-04-02 22:44
@EricDahlvang - Is the personal scope meant to be absent from the app manifest? What needs to be fixed here?

**Comment by sudoaccessdenied** [comment] 2021-04-04 19:23
@EricDahlvang @v-kydela  Scenario is that I created  bot that have personal , groupchat and team scope Because I am sending welcome message from bot to the user who installed the bot. The application works fine for groupchat and team scope. But I am getting error in personal scope as you can see in the screenshot. So I am unable to submit my bot in app source as it is throwing error.

**Comment by sudoaccessdenied** [comment] 2021-04-04 19:24
@EricDahlvang @v-kydela  Just add `personal` scope the the manifest and see the error.

**Comment by clearab** [comment] 2021-04-05 04:08
The "scope" is the types of conversations your bot can send messages to. In this case, I believe you're trying to send the message to a 1:1 chat between two users (not a 1:1 chat between the user and your bot). If this is the case, you'll actually need the `groupchat` scope. The bot would also need to be installed in that context (or you'd need to use the just-in-time-install option). 
@Wajeed-msft please correct me if any of the above is wrong!

**Comment by sudoaccessdenied** [comment] 2021-04-05 06:44
@clearab I am also using personal(user-bot) scope to send welcome message to the user who installed the app.

**Comment by Wajeed-msft** [comment] 2021-04-05 06:52
@sudoaccessdenied - Are you getting any exception in your C# backend code?

**Comment by sudoaccessdenied** [comment] 2021-04-05 06:54
@Wajeed-msft  No I am not getting any exception in the code but in the teams as you can seen in the screenshot.

**Comment by Wajeed-msft** [comment] 2021-04-05 09:04
@sudoaccessdenied - This looks like Teams specific issue, I have copied this one to Teams repo for tracking. 

https://github.com/MicrosoftDocs/msteams-docs/issues/3043

@clearab - Could you please help to close this one?

**Comment by clearab** [comment] 2021-04-06 15:34
Thanks @Wajeed-msft for jumping in on this!

**Closed by clearab** 2021-04-06 15:34 UTC
Labels: Bot Services, Support, bug, customer-replied-to, customer-reported, needs-triage
