### ISSUE TITLE
Unable to Deserialize json to abstract class

### ISSUE THREAD

**Issue by KoradaRajesh** [microsoft/botbuilder-dotnet#3612] opened 2020-01-30 07:26 UTC
I'm trying to Serialize and Deserialize Microsoft.Bot.Builder class ( DialogManager ) . It is Serializing and while Deserializing i'm getting error like
![Error in Deserialize DialogManager class](https://user-images.githubusercontent.com/51915291/73429053-b9b83500-4360-11ea-89f5-cbde933adea9.PNG)

**Comment by vishwacsena** [comment] 2020-03-24 22:00
Dupe of #3332

**Closed by vishwacsena** 2020-03-24 22:00 UTC
Labels: adaptive
