### ISSUE TITLE
It is seemingly impossible to retrieve/use binary data using the HTTP request action in Adaptive

### ISSUE THREAD

**Issue by benbrown** [microsoft/botbuilder-dotnet#4523] opened 2020-08-26 17:36 UTC
## Version
4.9

## Describe the bug
It is not possible to use the http request action to retrieve binary data and store it in a property.

When retrieving binary data, setting the response type to NONE will result in the property being NULL.
Setting the response type to JSON or leaving it blank results in garbled JSON.

## To Reproduce

1. Use an HTTP action to fetch a binary asset, for example an image or audio file, set this to dialog.binary
2. Set the response type to none.
3. Send an activity with { dialog.binary.content} -- it will result in "null"
4. Use a second HTTP action to try to send that binary asset to another API - it will not receive the binary as expected

## Expected behavior
Give a clear and concise description of what you expected to happen.

I expect dialog.binary.content to contain the binary asset, and for it to be able to be sent back out as a valid binary asset

## Additional context

This was reported by a customer who is attempting to load audio files and then use them with our speech apis

**Comment by vishwacsena** [comment] 2020-09-08 22:05
@boydc2014 can you help investigate/ address in R11?

**Comment by feich-ms** [comment] 2020-09-14 07:00
Hi @benbrown, I tried the latest released composer to verify this issue. I also checked the code. This feature was enabled in R10 recently. So the latest composer and SDK can support binary data for httpRequest action now(It seems 4.9 version was used when reporting this issue). Could you please use the latest composer or SDK to have a try. You can set the Response type to `binary` like below. Please let us know if the issue is still there

![image](https://user-images.githubusercontent.com/43032123/93053171-06efd980-f69a-11ea-8944-c0939b90fd0e.png)

**Comment by benbrown** [comment] 2020-09-14 13:51
Thanks for the update. I will validate with the customer.

**Comment by boydc2014** [comment] 2020-09-28 06:46
@benbrown closing this for now, feel free to reopen if this is not resolved.

**Closed by boydc2014** 2020-09-28 06:46 UTC
Labels: Area: Adaptive, bug, needs-triage
