### ISSUE TITLE
Alarm sample: add alarm flow doesn't work (see the screenshot)

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-dotnet#191] opened 2018-02-25 09:57 UTC
![image](https://user-images.githubusercontent.com/3801171/36640165-c4a86376-19ce-11e8-989c-2323c6a4b51c.png)

**Comment by garypretty** [comment] 2018-03-06 15:01
Just tested this to see if I could reproduce and it looks like it is working correctly.
![2018-03-06_6-59-32](https://user-images.githubusercontent.com/3900649/37039354-1d54faa4-210c-11e8-8b0a-ca8cb2f2796f.png)

**Comment by nrobert** [comment] 2018-03-12 09:15
@anastasiia-zolochevska , could you sync your repo, check again? This issue should be closed after the PR I submitted

**Comment by garypretty** [comment] 2018-03-12 11:45
@cleemullins @anastasiia-zolochevska As @nrobert said, I have retested this following #261 getting merged a few hours ago and this seems to be fixed, so I believe should be good to close now.

**Closed** 2018-04-17 00:33 UTC
Labels: bug, good first issue, help wanted
