### ISSUE TITLE
user state is causing user.name memory scope null.

### ISSUE THREAD

**Issue by som-nitjsr** [microsoft/botbuilder-dotnet#2597] opened 2019-09-24 16:49 UTC
## Version
What package version of the SDK are you using.

## Describe the bug
  **var test = _userState.CreateProperty<UserProfile>("UserProfile").GetAsync(turnContext, () => new UserProfile());**
after adding this line all the mapping with user scope is becoming null.
            return this.dialogManager.OnTurnAsync(turnContext, cancellationToken: cancellationToken);

## To Reproduce
added the userstate accessor in https://github.com/microsoft/botbuilder-dotnet/blob/4.Future/tests/Microsoft.Bot.Builder.TestBot.Json/TestBot.cs
run the 4 sample it will give null for user.name
## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by carlosscastro** [comment] 2019-09-24 18:09
Assigning to @stevenic as this is adaptive in 4.Future branch.

**Comment by som-nitjsr** [comment] 2019-09-30 02:39
is  there any work around for this bug. what is the ETA . let me know if you need any more info regarding this bug.

**Comment by tomlm** [comment] 2019-09-30 06:30
This doesn't repro on current branch.

**Comment by som-nitjsr** [comment] 2019-09-30 06:42
Hi @tomlm I am still able to reproduce with latest code.
in project **Microsoft.Bot.Builder.TestBot.Json**  in file TestBot.cs i have added only this line of code

var test = _userState.CreateProperty<UserProfile>("UserProfile").GetAsync(turnContext, () => new UserProfile());
let me know if i am missing something.
![image](https://user-images.githubusercontent.com/4559563/65854837-433c0400-e37b-11e9-9d67-4f4faf843055.png)

**Comment by stevengum** [comment] 2019-10-01 16:17
Reopening per @som-nitjsr's [comment](https://github.com/microsoft/botbuilder-dotnet/issues/2597#issuecomment-536424461)

Closing microsoft/botbuilder-dotnet#2636 as that is a dupe.

**Comment by tomlm** [comment] 2019-10-01 22:54
I finally was able to reproduce this, subtle bug, thanks for the persistence @som-nitjsr !

**Comment by som-nitjsr** [comment] 2019-10-02 03:00
Thanks @tomlm  fix is working.

**Comment by vishwacsena** [comment] 2019-10-08 19:19
Addressed via #2642

**Closed by vishwacsena** 2019-10-08 19:19 UTC
Labels: 4.6, Bot Services, P1, adaptive
