### ISSUE TITLE
Transient Unauthorized error every several hours

### ISSUE THREAD

**Issue by zhalu** [Microsoft/botbuilder-dotnet#1246] opened 2018-12-18 01:27 UTC
## Version
4.2.0

## Describe the bug
Every several hours, our Bot (built for Microsoft Teams) meet transient Unauthorized exception below. It just happens once every time (if we have only one instance in Azure App Service), and will disappear after next retry. Sometimes the error occurs when sending a message, sometimes it happens when sending a card, and sometimes it happens when getting conversation members, it's totally random.

Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Unauthorized'
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.BotFrameworkAdapter.<SendActivitiesAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass22_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<SendActivityAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.TurnContext.<SendActivityAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.XLivesite.StgBot.FrontEnd.Dialogs.BaseWaterfallDialog.<GetResultWithoutPromptAsync>d__12`1.MoveNext() in D:\gitroot\Storage\XInfrastructure\src\XLivesite\StgBot\StgBotFrontEnd\Dialogs\BaseWaterfallDialog.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.XLivesite.StgBot.FrontEnd.Dialogs.ActivityIdInfoDialog.<GetActivityIdStepAsync>d__9.MoveNext() in D:\gitroot\Storage\XInfrastructure\src\XLivesite\StgBot\StgBotFrontEnd\Dialogs\ActivityIdInfoDialog.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<OnStepAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<RunStepAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.<BeginDialogAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<BeginDialogAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.<BeginDialogAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.DialogContext.<BeginDialogAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.XLivesite.StgBot.FrontEnd.StgBot.<OnTurnAsync>d__13.MoveNext() in D:\gitroot\Storage\XInfrastructure\src\XLivesite\StgBot\StgBotFrontEnd\StgBot.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.ShowTypingMiddleware.<OnTurnAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.MiddlewareSet.<ReceiveActivityWithStatusAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.BotAdapter.<RunPipelineAsync>d__13.MoveNext()

## To Reproduce
1. Just wait several hours;
2. Talk to the Bot, and the error will happen;
3. If we talk to the Bot again immediately, the error won't happen again.

## Expected behavior
No such errors any more.

## Screenshots
![image](https://user-images.githubusercontent.com/6924750/50126172-c38af000-02a6-11e9-93cc-fe20b29ce54b.png)

## Additional context
Our Bot is built for Microsoft Teams channel, and it's published to Azure App Service as an ASP.NET Core App.

[bug]

**Comment by thomasmartinsen** [comment] 2018-12-18 18:39
I experience this as well in other channels (Skype etc.). I have blamed the App Plan so far - I'm currently running on very small instances that are not hot. When the bot tries to contact the Web App it simply needs to wake up and that takes some time.

**Comment by jwiley84** [comment] 2018-12-18 19:33
While this 'wake up' is not unexpected behaviour, receiving that error is. @zhalu, can I get your bot ID please? I'd like to see if there's something going on with your bot beyond the timeout.

**Comment by zhalu** [comment] 2018-12-18 23:32
> I experience this as well in other channels (Skype etc.). I have blamed the App Plan so far - I'm currently running on very small instances that are not hot. When the bot tries to contact the Web App it simply needs to wake up and that takes some time.

@thomasmartinsen I'm afraid "wake up" isn't my case. Though I'm also running on very small instances, I set "Always On" to true. As a result, the Web App will be on always and don't need to be waked up.

**Comment by zhalu** [comment] 2018-12-18 23:33
> While this 'wake up' is not unexpected behaviour, receiving that error is. @zhalu, can I get your bot ID please? I'd like to see if there's something going on with your bot beyond the timeout.

@jwiley84 My Bot Id is `306724f2-5354-4161-95c0-caefdcd089da`, thanks a lot for the prompt follow up!

**Comment by zhalu** [comment] 2019-01-07 02:30
Hi, is there any investigation progress for this bug? We're keeping seeing this every day.

**Comment by cleemullins** [comment] 2019-01-09 21:09
This is likley a dupe of #1251. It almost certainly has the same root cause - bugs in the token refresh logic. This work is expected to land this iteration (4.3) and should be on the daily build server next week. 

From that issue:
> The likely cause here is a token caching bug in the v4 SDK. Last release, in the V3 C# SDK, we moved away from our custom code and over to a turnkey solution offered by the AAD team. So far, that seems to have been working quite well, and we're comfortable with the solution. As a nice side effect of this work, performance under very high load is also quite a bit better.
> 
> The work is under way right now in the v4 C# SDK and is planned in the 4.3 release in mid Feb. I suspect it'll start showing up on the daily build server next week. @carlosscastro is driving this work.
> 
> I'm tagging this Issue as such, and we'll track it as part of Carlos's work.

**Comment by cleemullins** [comment] 2019-01-29 20:01
Fixed in 4.2.1.

https://github.com/Microsoft/botbuilder-dotnet/releases/tag/4.2.1

**Closed by cleemullins** 2019-01-29 20:01 UTC
Labels: 4.3, Approved, Bug, Duplicate, Triaged
