### ISSUE TITLE
SSO not working between my Root Bot and Skill Bot with OAuthPrompt

### ISSUE THREAD

**Issue by dingjianrui** [microsoft/botbuilder-dotnet#4317] opened 2020-07-23 09:24 UTC
## Version
Microsoft.Bot.Builder.* 4.9.3

## Describe the bug
I follow the steps "https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml" to configure the SSO environment, and with source code provided in the link, everything worked as expected.
Then i used the same configuration in my personal root bot(Virtual Assistant) and skill bot(Calendar Skill), the SSO process stuck in the skill bot when it got the "TokenExchangeInvokeRequest" from the root bot. 
![tcp 01](https://user-images.githubusercontent.com/1256355/88269180-2441a080-cd06-11ea-8eca-fb663b22b144.png)

Based on screenshot above (package captured)you can find that the root bot already sent the "TokenExchangeInvokeRequest" to the skill bot successfully.
![tcp 02](https://user-images.githubusercontent.com/1256355/88270497-5227e480-cd08-11ea-9c66-af9ca39704a0.png)

As the sequence diagram above, when the skill bot get the "TokenExchangeInvokeRequest", it should call the ABS to get a graph token, but nothing happened after that. Only the method "OnSignInInvokeAsync" method in the ActivityHandler of the skill bot get called.

It seems like that the OAuthPrompt dialog didn't get finished and the dialog after the OAuthPrompt didn't get fired. where can i find the source code for the package "Microsoft.Bot.Builder.* 4.9.3"? i can download the symbols file from nuget server, but the source code which is consist to this version of package cannot be found, I'd like to find out what really happened in the OAuthPrompt when it got the exchangeable token from the root bot, or maybe the request didn't get routed to the active OAuthPrompt dialog properly.

## To Reproduce
1. Create a virtual assistant with the VS template, and get it deployed.
2. Clone the calendar skill from the github and get it deployed.
3. Follow the steps mentioned above to configure the SSO apps for these two bot.
4. Tell the VA to check the calendar and the OAuth diagram will start.

## Expected behavior
1. Once the skill bot get the "TokenExchangeInvokeRequest" from the root bot, it should send a token exchange request to the ABS.
2. ABS return the graph token to the skill bot and OAuthPrompt dialog finished.
3. steps after the OAuthPrompt dialog get fired.

## Additional context

[bug]

**Comment by anusharavindrar** [comment] 2020-07-23 16:34
A similar issue was reported on SO https://stackoverflow.com/questions/63039371/bot-framework-sso-in-virtual-assistant-skills-scenario

**Comment by EricDahlvang** [comment] 2020-07-27 18:47
Hi @dingjianrui 

Which channel are you using?

Source code for the OAuthPrompt can be found here: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs

**Comment by carlosscastro** [comment] 2020-07-27 21:01
assigning to @lzc850612 since he'll take a look from a VA perspective.

**Comment by lzc850612** [comment] 2020-07-31 03:26
@carlosscastro it looks to me that there's incorrect behavior after calling ABS to get a token. This should be default behavior of OAuthPrompt as part of the core SDK so I don't think it's a VA/Skill issue. Have you tried to reproduce it?

**Comment by dingjianrui** [comment] 2020-08-01 01:50
@carlosscastro @lzc850612 thanks for your feedback, to share more information with you.
1. In the Calendar Skill bot, i replace the "MultiProviderAuthDialog" with the "OAuthPrompt", then the SSO process can work until the CalendarSkill get the "TokenExchangeInvokeRequest" from VA. The SSO process cannot event start if i use the MultiProviderAuthDialog dialog. (Probably the SSO mechanism for VA and Skills are designed in different way)
2. I check the DialogStack and DialogContext before the AuthPrompt dialog start, i think the dialog call stack is right, i can clearly find that the dialog stack like this: MainDialog -> ShowEventsDialog -> ShowEvents -> .... which is correct.
3. When the Calendar Skill get the "TokenExchangeInvokeRequest", i found that the DialogState retried from the storage is not the DialogState which is saved before, cause no DialogStack existing, the stack is empty. so the OAuthPrompt dialog cannot continue to finish the SSO process.

Question:
What could cause the Calendar Skill cannot find the DialogState it is saved before? it should persisted into the database along with the conversation state.

Thanks.

**Comment by dingjianrui** [comment] 2020-08-01 01:54
> Hi @dingjianrui
> 
> Which channel are you using?
> 
> Source code for the OAuthPrompt can be found here: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs

Hi @EricDahlvang , this version of the source code is not consist with the package "Microsoft.Bot.Builder.* 4.9.3" i used.

**Comment by dingjianrui** [comment] 2020-08-01 07:54
Hi @carlosscastro  @lzc850612 , 
Here are two methods in the Skill bot's ActivityHandler:
![ttt](https://user-images.githubusercontent.com/1256355/89097094-52ae3280-d40e-11ea-9fc7-6feb98b6c622.png)
Due to the "DialogState" changed in the "OnMessageActivityAsync" cannot be loaded in "OnSignInInvokeAsync",  It seems like that the "OnSignInInvokeAsync" always create a new "DialogState", instead of using the existing one. So the dialog cannot continue, and the SSO process cannot finish the last step.

Don't know what could cause this issue.

Thanks.

**Comment by EricDahlvang** [comment] 2020-08-08 03:45
@dingjianrui I'm sorry for the delay in answering.  Have you tried [4.9.4](https://www.nuget.org/packages/Microsoft.Bot.Builder/4.9.4) ?

**Comment by lauren-mills** [comment] 2020-08-25 18:19
@lzc850612 - can you give an update here?

**Comment by lzc850612** [comment] 2020-09-04 21:47
@dingjianrui 

The latest VA release uses something called TokenExchangeSkillHandler to handle OAuthCard coming from skill and send an activity with the retrieved token back to skill (because at the moment of the release the SDK doesn't natively support this yet @carlosscastro to see if this is natively supported now). And to be able to use this, you need to add values to this section in the appsettings in VA:

  "tokenExchangeConfig": {
    "connectionName": "",
    "provider": ""
  },

This setting was put in because at the time we shipped this we wanted to have a way of toggling SSO off as we were not advertising to let everyone use SSO at that moment, especially given we don't have it natively supported in SDK. Since then the provider property has changed so we need a fix to remove the logic to use this setting. We can get this fix out in the next release.

Question: when you say 
"In the Calendar Skill bot, i replace the "MultiProviderAuthDialog" with the "OAuthPrompt", then the SSO process can work until the CalendarSkill get the "TokenExchangeInvokeRequest" from VA. " Do you mean skill GETS this request or skill DOESN'T GET this request? I'm assuming the latter because of the description above. Please let me know otherwise

@carlosscastro please take a look at the SDK side to
decide whether or not SDK natively support token exchange now so we can remove the code from VA

**Comment by lzc850612** [comment] 2020-09-04 22:06
As I debug further, I found out that the TokenExchange operation actually fails:

https://github.com/microsoft/BotBuilder-Samples/blob/5fe18b89b238e3477247f5dbed874ffcd2ef8a28/experimental/sso-with-skills/RootBot/TokenExchangeSkillHandler.cs#L111

@carlosscastro i'm assuming you could help take a look at this as the code in VA also has the same code snippet.

**Comment by tdurnford** [comment] 2020-09-21 18:14
@carlosscastro @lzc850612 Any updates on this issue?

**Comment by lzc850612** [comment] 2020-10-05 17:33
@dingjianrui can you take a look at my previous reply and answer my question in there? Thanks.

**Comment by stevengum** [comment] 2020-10-19 18:56
Closing due to inactivity.

**Closed by stevengum** 2020-10-19 18:56 UTC
Labels: Area: Skills, Bot Services, customer-replied-to, customer-reported, needs-author-feedback
