### ISSUE TITLE
TurnContext.SendActivitiesAsync changes the activities' ID

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botbuilder-dotnet#2689] opened 2019-10-09 19:59 UTC
## Version
master

## Describe the bug
On [this line](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/TurnContext.cs#L274), we can see where the turn context modifies the ID of each outgoing activity:

```c#
activity.Id = responses[index].Id;
```

While outgoing activities are necessarily modified when a conversation reference is applied, modifying the ID based on the resource response creates strange behavior when the activity is saved and used again, like when it's a retry prompt. The Emulator for example will not display an activity if the ID is the same as an activity already in the conversation history. Several customers are running into issues because of this:
https://github.com/microsoft/BotFramework-Emulator/issues/1684
https://stackoverflow.com/questions/58082537/why-does-the-retry-prompt-only-show-once

The turn context in the Node SDK does not modify an outgoing activity's ID.

## Expected behavior
There is reason to think that simply sending an activity shouldn't modify it at all, even by applying the conversation reference. That is to say, the necessary modifications should be done on a *copy* of the activity that gets passed to `SendActivityAsync` for example. However, changing this now could be breaking behavior if some bots expect the activity to be modified. Also, an easy workaround is to send an activity through the adapter or the connector, so bot developers have a choice about whether they want outgoing activities to be modified automatically.

The ID in particular may be a special case for a few reasons. Not only is this modification causing the issues we see in Emulator, but the behavior is inconsistent between repos. Even if we don't want to change this ID-modifying behavior in the .NET SDK, we should still make sure the different SDK's work the same way.

[bug]

**Comment by EricDahlvang** [comment] 2019-11-22 19:43
It would likely break existing tests and bots if we were to change the behavior of setting the activity.id to resourceresponse.id.  However, to bring things more inline with the spec we are now ensuring the outgoing activity does not have an .id 

ref: [A2031: Clients and bots SHOULD NOT include an id field in activities they generate.](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#id)

[javascript](https://github.com/microsoft/botbuilder-js/commit/cdb8d6f0123175f526d935fefcac5db2b188d9aa#diff-cee27df6126434892e9a6747003fb69eR455)

[dotnet](https://github.com/microsoft/botbuilder-dotnet/pull/3012/files#diff-1f0c90c6fa85dfcad121531bcb2092edR411)

Finally, the emulator will also no longer respect ids sent to it: [emulator](https://github.com/microsoft/BotFramework-Emulator/pull/2003/files#diff-d7a390bc463ce1da33b33f25899020edL772)

**Comment by v-kydela** [comment] 2019-11-22 20:36
@EricDahlvang - If the Node SDK only applies the ID to the cloned activity then it won't be saved in the dialog state, right? Doesn't that mean it will behave differently from the .NET SDK? Are we going to leave it like that?

**Comment by EricDahlvang** [comment] 2019-11-22 21:54
@v-kydela  I think we will be leaving that difference.  The decision to stamp the resource response id over the currently sending activity instance (not a clone) in the dotnet sdk was made purposefully, as was the decision to NOT do the same in node.js  And, we have released both libraries this way ...

Nonetheless, the retry-prompt behavior will be the same for both libraries: since neither are sending an activity.id (dotnet still stores it with the dialog stack, but it will not use it when sending the activity).

**Comment by v-kydela** [comment] 2019-11-22 22:41
@EricDahlvang - If the decision was made purposefully then what was the purpose?

**Comment by EricDahlvang** [comment] 2019-11-26 08:17
I don't know, since i didn't write it. But I'm sure whoever did, did so on purpose.

The bug is fixed and the sdk is no longer sending ids for messages. Setting the id of the outgoing activity is by design, so closing this.

**Closed by EricDahlvang** 2019-11-26 08:17 UTC
Labels: Bot Services, R7, bug, customer-replied-to, customer-reported
