### ISSUE TITLE
When Skills are running locally, do not require channel registration & authentication.

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botbuilder-dotnet#4538] opened 2020-08-27 23:20 UTC
There should be a local development mode

**Comment by clearab** [comment] 2020-08-28 17:49
I think this might be a duplicate of: https://github.com/microsoft/botframework-sdk/issues/5726 (or at least have a lost of cross-over)

**Comment by mrivera-ms** [comment] 2020-11-05 18:02
Done in R11.

**Closed by mrivera-ms** 2020-11-05 18:02 UTC
Labels: Area: Adaptive, bug, needs-triage
