### ISSUE TITLE
AzureBlobTranscriptStore not working when bot file endpoint has no id value

### ISSUE THREAD

**Issue by martinoss** [microsoft/botbuilder-dotnet#2211] opened 2019-07-10 14:48 UTC
## Version
4.4.5

## Describe the bug
Not very high priority, but I ran into the issue that the TransscriptLoggerMiddleware was not writing any transcripts. Turned out to be due to a nulled "activity.Recipient.**Id**" caused by a missing attribute in the bot file (id of endpoint). Took me some time to find the relation between this "id" and the recipient.

## To Reproduce
1. Have the TransscriptLoggerMiddleware configured with AzureBlobTranscriptStore
2. Have a bot file with an endpoint that has no "id" property.
3. Connect to that endpoint and notice "System.ArgumentNullException: Value cannot be null." exceptions in the output pane when chatting. Transscript files are not being saved.

## Expected behavior
Error handling could be improved within AzureBlobTranscriptStore. Maybe add a check or omit the particular metadata. Or an error in a earlier stage would be helpful too (eg. validation of the endpoint service type). Another option would be to improve the documentation to tell about the purpose of the "id".

## Additional context

[bug]

**Comment by cleemullins** [comment] 2019-08-09 18:25
Thanks for reporting this. We'll fix this bug in 4.6.

**Comment by garypretty** [comment] 2019-09-24 10:52
@martinoss Thanks again for reporting this.  I have tried a bot with a bot file with no id, using an older version of the SDK, as well as the current 4.6 preview, but I am unable to reproduce this issue.  In all cases the transcript is logged correctly and the Recipient.Id is populated.

Could you elaborate a little more on the connection you have found between activity.Recipient.Id and   the bot file ID?

**Comment by martinoss** [comment] 2019-09-24 15:21
@garypretty Thanks for looking into this. Transcript logging fails silently in my case, but the error can be observed in Visual Studio's output window like this (v.4.5.1):

```
Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.Dev.xxx.RemoteDependency","time":"2019-09-24T14:56:40.2903946Z","iKey":"xxx","tags":{"ai.application.ver":"1.0.0.0","ai.cloud.roleInstance":"XXX","ai.operation.id":"5b7681f4170d664ca03ab87e93d3102e","ai.operation.parentId":"|5b7681f4170d664ca03ab87e93d3102e.b8cc5e93_","ai.operation.name":"POST Bot/PostAsync","ai.location.ip":"127.0.0.1","ai.internal.sdkVersion":"rdddsc:2.10.0-32157","ai.internal.nodeName":"xxx"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"PUT xxx","id":"|xxx.b8cc5e93_14.","data":"https://xxx.blob.core.windows.net:443/transcripts/emulator/7483ce71-dedb-11e9-81f6-2d01d376bd21%257Clivechat/xxx.json?comp=block&blockid=ODI1NTRmYjYyNDVhNDMxYmIxYjIzNjI4NzA1NjY0NGItMDAwMDAw","duration":"00:00:00.0597775","resultCode":"201","success":true,"type":"Azure blob","target":"xxx.blob.core.windows.net","properties":{"Blob":"8d740ff67d53183-83770410-dedb-11e9-bd44-5daa4dca4d27.json","Container":"transcripts/emulator/7483ce71-dedb-11e9-81f6-2d01d376bd21%257Clivechat","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')","AspNetCoreEnvironment":"Local","DeveloperMode":"true"}}}}
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action method MyBot.Api.Controllers.BotController.PostAsync (MyBot.Api), returned result Microsoft.AspNetCore.Mvc.EmptyResult in 3198.1739ms.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action MyBot.Api.Controllers.BotController.PostAsync (MyBot.Api) in 3217.979ms
Microsoft.AspNetCore.Routing.EndpointMiddleware:Information: Executed endpoint 'MyBot.Api.Controllers.BotController.PostAsync (MyBot.Api)'
MyBot.Api Error: 0 : Transcript logActivity failed with System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: value) ---> Microsoft.WindowsAzure.Storage.StorageException: Value cannot be null.
Parameter name: value ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.AddMetadata(StorageRequestMessage request, String name, String value) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\Common\Shared\Protocol\HttpRequestMessageFactory.cs:line 206
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.AddMetadata(StorageRequestMessage request, IDictionary`2 metadata) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\Common\Shared\Protocol\HttpRequestMessageFactory.cs:line 188
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass137_0.<PutBlockListImpl>b__1(RESTCommand`1 cmd, Uri uri, UriQueryBuilder builder, HttpContent cnt, Nullable`1 serverTimeout, OperationContext ctx) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 2876
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](ExecutionState`1 executionState, String startLogMessage, CancellationTokenSource timeoutTokenSource) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 297
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 71
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.CommitAsync() in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 388
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Dispose(Boolean disposing) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 332
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.LogActivityAsync(IActivity activity) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Azure\AzureBlobTranscriptStore.cs:line 98
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.<>c.<OnTurnAsync>b__3_3(Task task) in d:\a\1\s\libraries\Microsoft.Bot.Builder\TranscriptLoggerMiddleware.cs:line 122
---> (Inner Exception #0) Microsoft.WindowsAzure.Storage.StorageException: Value cannot be null.
Parameter name: value ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.AddMetadata(StorageRequestMessage request, String name, String value) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\Common\Shared\Protocol\HttpRequestMessageFactory.cs:line 206
   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpRequestMessageFactory.AddMetadata(StorageRequestMessage request, IDictionary`2 metadata) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\Common\Shared\Protocol\HttpRequestMessageFactory.cs:line 188
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.<>c__DisplayClass137_0.<PutBlockListImpl>b__1(RESTCommand`1 cmd, Uri uri, UriQueryBuilder builder, HttpContent cnt, Nullable`1 serverTimeout, OperationContext ctx) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 2876
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](ExecutionState`1 executionState, String startLogMessage, CancellationTokenSource timeoutTokenSource) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 297
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 71
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.CommitAsync() in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 388
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Dispose(Boolean disposing) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 332
   at System.IO.Stream.Close()
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Microsoft.Bot.Builder.Azure.AzureBlobTranscriptStore.LogActivityAsync(IActivity activity) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Azure\AzureBlobTranscriptStore.cs:line 98
Request Information
RequestID:
RequestDate:
StatusMessage:
ErrorCode:
<---
```

See this line here causing the issue:
https://github.com/microsoft/botbuilder-dotnet/blob/bfe475a0dbab4cd5aa840882e2fedfb5b8ff74ba/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs#L92

Id is null when the "id" property (not present at all) is missing in the properties of **an endpoint under services** in the bot file json, like:

```
{
    "name": "MyBot",
    "description": "My Bot",
    "services": [
        {
            "type": "endpoint",
            "appId": "",
            "appPassword": "",
            "endpoint": "http://localhost:3980/api/messages",
            "name": "DA - http://localhost:3980/api/messages",
            "id": "yoda-123"  <------------------ REMOVE THIS LINE
        }
    ],
    "padlock": "",
    "version": "2.0",
    "path": "C:\\Code\\VSTS\\MyBot\\MyBot.bot",
    "overrides": null
}
```

**Comment by garypretty** [comment] 2019-09-24 15:28
@martinoss Thanks for the additional info.  Obviously with all the sensitive keys removed etc.  I am unable to even make my bot fail silently, with the Recipient.Id property always populated, even if I have no id on my endpoint in the bot file. I am wondering if there is a difference between how the configuration is being read or the bot is being initialized that would explain this.

Is your bot in a state where you could zip / share it as a sample?

**Comment by martinoss** [comment] 2019-09-27 10:39
@garypretty I've reproduced the case in a new bot, see [https://github.com/martinoss/EchoBotTranscript](https://github.com/martinoss/EchoBotTranscript)

**Comment by garypretty** [comment] 2019-09-27 10:44
Thanks @martinoss I will take a look and get a fix implemented. Thanks again for reporting.

**Comment by garypretty** [comment] 2019-09-27 17:29
@martinoss I have just downloaded your EchoBotTranscript solution, populated a storage connection string and ran the bot - the transcript logging seems to be working as expected.  I see how errors thrown in the output window and the transcript logs are being recorded (see the screenshots below - Azure portal and downloaded JSON).

I left the bot file endpoint as it was. i.e. with no Id property at all.

![image](https://user-images.githubusercontent.com/3900649/65788809-d692f080-e153-11e9-9bd0-1e6d2329bb2b.png)

![image](https://user-images.githubusercontent.com/3900649/65788961-35586a00-e154-11e9-82b2-01af65d340ac.png)

**Comment by garypretty** [comment] 2019-10-04 14:34
@martinoss I have repeated my test using your sample code, plus I had two other colleagues do the same, but unfortunately we are unable to reproduce your issue and our transcripts are logged correctly. We suspect this might be a local issue specific to you.  

What was it that made you think that the specific line that was failing was the RecipientId?  The error is thrown on line 98, which is when there is an attempt to serialize the activity, so in theory it could be any of the properties or event the blob reference that are causing the issue.

**Comment by garypretty** [comment] 2019-10-08 14:46
Hi @martinoss.  As you have a workaround to get your solution working locally and we cannot reproduce without more details, I am going to close this for now.  Please do re-open it if you find any further information that could help us.

**Closed by garypretty** 2019-10-08 14:46 UTC
Labels: 4.6, Bot Services, bug, customer-replied-to, customer-reported

**Comment by martinoss** [comment] 2019-10-10 15:06
@garypretty It might have to do with the emulator version we're using. For some reason we're stuck with version 4.3.3.  [See this issue](https://github.com/microsoft/BotFramework-Emulator/issues/1568)
But it's ok for me to close this issue since it's unlikely some one else is omitting this id ;)
