### ISSUE TITLE
 SendToConversationAsync fails with NullReference Exception, HttpClient null in ConnectorClient.HttpClient

### ISSUE THREAD

**Issue by venkatesh-bhupathi** [microsoft/botbuilder-dotnet#3205] opened 2020-01-01 17:50 UTC
## Version
What package version of the SDK are you using.
4.5.3

## Describe the bug
We need to send an event from bot to the user webchat and we are using connectorClient.Conversations.SendToConversationAsync to send the event.

We are building the ConnectorClient with the following code,
`var connectorClient = new ConnectorClient(new Uri(serviceLink), "Bot App Id", "AppPassword"))`

I have added the conversation information we have about the Conversation Reference at the bottom of the email using which we are trying to send event with the following code,

```
var eventActivity = new Activity()
                    {
                        Type = ActivityTypes.Event,
                        Name = RequestDistributionEventEnum.RequestAgent.ToString(),
                        Value = new AgentRequest { ClientSession = chatRequest.ClientSession, RequestContext = chatRequest.RequestContext }, //Payload for the client to process the event
                    };

MicrosoftAppCredentials.TrustServiceUrl(user.Connection.ServiceLink); 
connectorClient.Conversations.SendToConversationAsync((Activity)eventActivity).ConfigureAwait(false);

```
I have taken the BotBuilder code locally and debugged through the call to SendToConversationAsync in ConversationsEx.cs. I see that following method is called from ConversationExtensions.cs,

`public static async Task<ResourceResponse> SendToConversationAsync(this IConversations operations, string conversationId, Activity activity, CancellationToken cancellationToken = default(CancellationToken))`

This internally calls SendToConversationWithHttpMessagesAsync, inside this method there is the following call to post the Event at Line # 536 in Conversations.cs, 

`_httpResponse = await Client.HttpClient.SendAsync(_httpRequest, cancellationToken).ConfigureAwait(false);`

I see that HttpClient property of the ConnectorClient is null, due to HttpClient being null, the call to ConnectorClient.Conversations.SendToConversationAsync throws null reference exception.

To work around for now, I have added the following code to initialize a new HttpClient in Conversations.cs file and tried to complete the call as follows,

```
var httpClient = new HttpClient();
httpClient.BaseAddress = _httpRequest.RequestUri;
              _httpResponse = await httpClient.SendAsync(_httpRequest, cancellationToken).ConfigureAwait(false);
```

I can see that the POST call is successful and we are able to successfully send the event to WebChat. 

## Expected behavior
We would like to understand how the HttpClient property of the ConnectorClient is being set to null which is breaking the SendToConversationAsync call. Please let us know, how this can be fixed in SDK? And let us know if you need any information further.

## Additional context

[bug]

**Comment by venkatesh-bhupathi** [comment] 2020-01-02 03:07
We used to construct the ConnectClient as follows in V3 and the SendToConversationAsync worked  without any issues,

`var connectorClient = new ConnectorClient(new Uri(serviceLink))`

However in V4, we are getting the exception with message, 

_Value cannot be null.\r\nParameter name: clientId_

Is there a change in V4 ConnectorClient implementation to include the AppId/Password during the construction of the ConnectorClient?

Following is the stack trace of the exception,

  ```
 at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential..ctor(String clientId, String clientSecret)
   at Microsoft.Bot.Connector.Authentication.MicrosoftAppCredentials.<BuildAuthenticator>b__14_0() in C:\Users\vebhupat\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Connector\Authentication\MicrosoftAppCredentials.cs:line 139
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<GetTokenAsync>d__32.MoveNext() in C:\Users\vebhupat\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Connector\Authentication\AppCredentials.cs:line 203
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.Authentication.AppCredentials.<ProcessHttpRequestAsync>d__31.MoveNext() in C:\Users\vebhupat\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Connector\Authentication\AppCredentials.cs:line 187
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.Conversations.<SendToConversationWithHttpMessagesAsync>d__7.MoveNext() in C:\Users\vebhupat\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Connector\Conversations.cs:line 528
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.ConversationsExtensions.<SendToConversationAsync>d__14.MoveNext() in C:\Users\vebhupat\source\repos\botbuilder-dotnet\libraries\Microsoft.Bot.Connector\ConversationsExtensions.cs:line 133
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ConnectMe.Conversations.BusinessV4.Managers.ConversationManager.<SendActivityToUser>d__26.MoveNext() in C:\Users\vebhupat\source\repos\EUS-Sup-OSEE-CMe-ConnectMeCore\ConnectMe\ConnectMe.Conversations.BusinessV4\Managers\ConversationManager.cs:line 695

```
This is blocking our progress to move to V4 and request urgent attention on this issue.

**Comment by venkatesh-bhupathi** [comment] 2020-01-02 11:44
We have tried using the constructor through which we can pass our own HttpClient as follows,

`public ConnectorClient(Uri baseUri, MicrosoftAppCredentials credentials, HttpClient customHttpClient, bool addJwtTokenRefresher = true, params DelegatingHandler[] handlers);`

```
var appCredentials = new MicrosoftAppCredentials(configProvider.GetSetting(Config.MicrosoftAppId), configProvider.GetSetting(Config.ProductionMicrosoftAppPassword));
            using (var httpClient = new HttpClient())
            {
#pragma warning disable SecurityIntelliSenseCS // MS Security rules violation
                httpClient.BaseAddress = new Uri("https://directline.botframework.com/");
#pragma warning restore SecurityIntelliSenseCS // MS Security rules violation
                using (var connectorClient = new ConnectorClient(new Uri(serviceLink), appCredentials, customHttpClient: httpClient))
                {
                    return new ConnectorBundle(connectorClient, activity);
                }
            }
```

Still it throws the Null reference exception.

**Comment by EricDahlvang** [comment] 2020-01-02 18:18
Closing.  Root cause of null HttpClient was due to using the ConnectorClient after it had been disposed.

**Closed by EricDahlvang** 2020-01-02 18:18 UTC
Labels: Bot Services, customer-reported
