### ISSUE TITLE
Json builtin function doesn't accept empty strings

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-dotnet#4418] opened 2020-08-07 21:17 UTC
Using the composer, I found out that we don’t accept empty string value:
Example:
```
This works: = json('{"SR":{"Q1":"1","Q2":"2"}}')
This fails:   = json('{"SR":{"Q1":"","Q2":"2"}}')
```

**Comment by boydc2014** [comment] 2020-08-24 03:21
Thanks @scheyal, we will look into this soon.

**Comment by boydc2014** [comment] 2020-08-24 03:29
Initial investigation showed SDK support empty fine, but it fails in Composer main branch.

**Comment by cosmicshuai** [comment] 2020-08-24 06:55
@scheyal @boydc2014 @Danieladu 
The error is caused by the parser of string interpolation. ${``} should yield an empty string but thorws an error. 
While evaluating a json expression, it will resolve the data bindings recursively. So once it encountered a empty string "". It will be resolved to an empty string interpolation ``. 
I created a PR to fix this issue. After it is merged, this issue will be fixed.

**Closed** 2020-08-24 09:59 UTC
Labels: Area: Adaptive expression
